package com.avnet.emasia.webquote.entity;

// Generated 2014-4-24 17:15:38 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * PricerTypeMapping generated by hbm2java
 */
@Entity
@Table(name = "PRICER_TYPE_MAPPING")
public class PricerTypeMapping implements java.io.Serializable
{
	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "mfr", column = @Column(name = "MFR", length = 10)),
			@AttributeOverride(name = "partNumber", column = @Column(name = "PART_NUMBER", length = 80)),
			@AttributeOverride(name = "bizUnit", column = @Column(name = "BIZ_UNIT", length = 10)) })
	private PricerTypeMappingId id;
	
	@Version
	@Column(name="\"VERSION\"")
	private Integer version;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "CREATE_DATE", length = 7)
	private Date createDate;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "UPDATE_DATE", length = 7)
	private Date updateDate;
	
	@Column(name = "HAS_NORMAL_FLAG", precision = 1, scale = 0)
	private Boolean hasNormalFlag;
	
	@Column(name = "HAS_CONTRACT_FLAG", precision = 1, scale = 0)
	private Boolean hasContractFlag;
	
	@Column(name = "HAS_PROGRAM_FLAG", precision = 1, scale = 0)
	private Boolean hasProgramFlag;
	
	@Column(name = "HAS_FUTURE_PRICER", precision = 1, scale = 0)
	private Boolean hasFuturePricer;

	public PricerTypeMapping()
	{
	}

	public PricerTypeMapping(PricerTypeMappingId id)
	{
		this.id = id;
	}


	public PricerTypeMappingId getId()
	{
		return this.id;
	}

	public void setId(PricerTypeMappingId id)
	{
		this.id = id;
	}


	public Integer getVersion()
	{
		return this.version;
	}

	public void setVersion(Integer version)
	{
		this.version = version;
	}


	public Date getCreateDate()
	{
		return this.createDate;
	}

	public void setCreateDate(Date createDate)
	{
		this.createDate = createDate;
	}


	public Date getUpdateDate()
	{
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate)
	{
		this.updateDate = updateDate;
	}


	public Boolean getHasNormalFlag()
	{
		return this.hasNormalFlag;
	}

	public void setHasNormalFlag(Boolean hasNormalFlag)
	{
		this.hasNormalFlag = hasNormalFlag;
	}


	public Boolean getHasContractFlag()
	{
		return this.hasContractFlag;
	}

	public void setHasContractFlag(Boolean hasContractFlag)
	{
		this.hasContractFlag = hasContractFlag;
	}


	public Boolean getHasProgramFlag()
	{
		return this.hasProgramFlag;
	}

	public void setHasProgramFlag(Boolean hasProgramFlag)
	{
		this.hasProgramFlag = hasProgramFlag;
	}


	public Boolean getHasFuturePricer()
	{
		return this.hasFuturePricer;
	}

	public void setHasFuturePricer(Boolean hasFuturePricer)
	{
		this.hasFuturePricer = hasFuturePricer;
	}

}
