package com.avnet.emasia.webquote.webservice.zwqrmtosap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.7.redhat-1
 * 2014-11-25T11:39:33.813+08:00
 * Generated source version: 2.7.7.redhat-1
 * 
 */
@WebService(targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", name = "ZWQRMTOSAP")
@XmlSeeAlso({ObjectFactory.class})
public interface ZWQRMTOSAP {

    @RequestWrapper(localName = "ZsdRecvWqmrpblkctl", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.avnet.emasia.webquote.webservice.zwqrmtosap.ZsdRecvWqmrpblkctl")
    @WebMethod(operationName = "ZsdRecvWqmrpblkctl")
    @ResponseWrapper(localName = "ZsdRecvWqmrpblkctlResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.avnet.emasia.webquote.webservice.zwqrmtosap.ZsdRecvWqmrpblkctlResponse")
    public void zsdRecvWqmrpblkctl(
        @WebParam(mode = WebParam.Mode.INOUT, name = "Return", targetNamespace = "")
        javax.xml.ws.Holder<TableOfZwqrmtosapMsg> _return,
        @WebParam(mode = WebParam.Mode.INOUT, name = "ZwqBlklst", targetNamespace = "")
        javax.xml.ws.Holder<TableOfZquoteBlklst> zwqBlklst
    );
}
