
package com.avnet.emasia.webquote.webservice.customer;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.4.6
 * 2014-05-26T16:37:42.872+08:00
 * Generated source version: 2.4.6
 */

@WebFault(name = "ZsdWqCrCustomer.Exception", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style")
public class ZsdWqCrCustomerException extends Exception {
    
    private com.avnet.emasia.webquote.webservice.customer.ZsdWqCrCustomerRfcException zsdWqCrCustomerException;

    public ZsdWqCrCustomerException() {
        super();
    }
    
    public ZsdWqCrCustomerException(String message) {
        super(message);
    }
    
    public ZsdWqCrCustomerException(String message, Throwable cause) {
        super(message, cause);
    }

    public ZsdWqCrCustomerException(String message, com.avnet.emasia.webquote.webservice.customer.ZsdWqCrCustomerRfcException zsdWqCrCustomerException) {
        super(message);
        this.zsdWqCrCustomerException = zsdWqCrCustomerException;
    }

    public ZsdWqCrCustomerException(String message, com.avnet.emasia.webquote.webservice.customer.ZsdWqCrCustomerRfcException zsdWqCrCustomerException, Throwable cause) {
        super(message, cause);
        this.zsdWqCrCustomerException = zsdWqCrCustomerException;
    }

    public com.avnet.emasia.webquote.webservice.customer.ZsdWqCrCustomerRfcException getFaultInfo() {
        return this.zsdWqCrCustomerException;
    }
}
