alter table TASK_INFO add ALL_NODE NUMBER default 0;
alter table TASK_HISTORY add ALL_NODE NUMBER default 0;
ALTER TABLE TASK_HISTORY  MODIFY (TASK_CLASS_NAME VARCHAR2(150 BYTE) );
ALTER TABLE TASK_INFO  MODIFY (TASK_CLASS_NAME VARCHAR2(150 BYTE) );
