
ALTER TABLE QUOTE_ITEM  ADD (DP_REFERENCE_LINE_ID VARCHAR2(20) );
ALTER TABLE QUOTE  ADD (DP_REFERENCE_ID VARCHAR2(20) );
ALTER TABLE QUOTE ADD (QUOTE_SOURCE VARCHAR2(20) );
ALTER TABLE QUOTE_ITEM_HIS  ADD (DP_REFERENCE_LINE_ID VARCHAR2(20) );
--------------------------------------------------------
--  DDL for Table DP_MESSAGE
--------------------------------------------------------

  CREATE TABLE "WEBQUOTE"."DP_MESSAGE" 
   (	"ID" NUMBER(18,0), 
	"CREATE_RFQ_MESSAGE" CLOB, 
	"UPDATE_RFQ_MESSAGE" CLOB, 
	"CREATE_RFQ_TIME" TIMESTAMP (6), 
	"UPDATE_RFQ_TIME" TIMESTAMP (6), 
	"VERSION" NUMBER(6,0), 
	"BAD_FORMED_CREATE_RFQ_MESSAGE" NUMBER(1,0)
   )  ;
   
   ALTER TABLE DP_MESSAGE ADD (BIZ_UNIT VARCHAR2(10) );

   ALTER TABLE DP_MESSAGE ADD CONSTRAINT DP_MESSAGE_FK1 FOREIGN KEY(  BIZ_UNIT )REFERENCES BIZ_UNIT(  NAME )ENABLE;

--------------------------------------------------------
--  DDL for Table DP_RFQ
--------------------------------------------------------

  CREATE TABLE "WEBQUOTE"."DP_RFQ" 
   (	"ID" NUMBER(18,0), 
	"DP_MESSAGE_ID" NUMBER(18,0), 
	"CONTACT_EMAIL_ADDRESS" VARCHAR2(256 BYTE), 
	"CONTACT_NAME" VARCHAR2(256 BYTE), 
	"CONTACT_PHONE_NO" VARCHAR2(32 BYTE), 
	"OPERATION" VARCHAR2(50 BYTE), 
	"REFERENCE_ID" NVARCHAR2(20), 
	"SALES_OFFICE" VARCHAR2(20 BYTE), 
	"SALES_ORGANIZATION" VARCHAR2(20 BYTE), 
	"SOLD_TO_CUSTOMER_ACCOUNT_NO" VARCHAR2(128 BYTE), 
	"SOLD_TO_CUSTOMERNAME" VARCHAR2(64 BYTE), 
	"SOURCE" VARCHAR2(20 BYTE), 
	"SALES_PERSON_ID" VARCHAR2(20 BYTE), 
	"CUSTOMER_TYPE" VARCHAR2(20 BYTE), 
	"SEGMENT" VARCHAR2(50 BYTE), 
	"QUOTE_TYPE" VARCHAR2(20 BYTE), 
	"QUOTE_ID" NUMBER(18,0), 
	"CREATION_TIME" DATE, 
	"LAST_UPDATE_TIME" DATE, 
	"RFQ_CREATION_TIMESTAMP" TIMESTAMP (6), 
	"VERSION" NUMBER(6,0)
   )  ;
--------------------------------------------------------
--  DDL for Table DP_RFQ_ITEM
--------------------------------------------------------

  CREATE TABLE "WEBQUOTE"."DP_RFQ_ITEM" 
   (	"ID" NUMBER(18,0), 
	"DP_RFQ_ID" NUMBER(18,0), 
	"QUANTITY" NUMBER, 
	"REFERENCE_LINE_ID" VARCHAR2(20 BYTE), 
	"REQUESTED_MANUFACTURER" VARCHAR2(64 BYTE), 
	"REQUESTED_PART" VARCHAR2(64 BYTE), 
	"TARGET_RESALE" NUMBER(20,5), 
	"CURRENCY" VARCHAR2(20 BYTE), 
	"LINE_ITEM_NUMBER" NUMBER(3,0), 
	"QUOTE_LINE_STATUS" VARCHAR2(100 BYTE), 
	"QUOTED_QTY" NUMBER, 
	"QUOTED_RESALE" NUMBER(20,5), 
	"REJECTION_REASON" VARCHAR2(254 BYTE), 
	"REMARKS" VARCHAR2(254 BYTE), 
	"EXPIRY_DATE" TIMESTAMP (6), 
	"QUOTE_ITEM_ID" NUMBER(18,0), 
	"PROC_STATUS" VARCHAR2(20 BYTE), 
	"INTERNAL_ERROR" VARCHAR2(200 BYTE), 
	"VERSION" NUMBER(6,0), 
	"REPROCESS_TIME" DATE, 
	"REPROCESS_COUNT" NUMBER(5,0)
   )  ;
--------------------------------------------------------
--  DDL for Index DP_MSG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBQUOTE"."DP_MSG_PK" ON "WEBQUOTE"."DP_MESSAGE" ("ID")  ;
--------------------------------------------------------
--  DDL for Index DP_RFQ_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBQUOTE"."DP_RFQ_PK" ON "WEBQUOTE"."DP_RFQ" ("ID") ;
--------------------------------------------------------
--  DDL for Index DP_RFQ_ITEM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBQUOTE"."DP_RFQ_ITEM_PK" ON "WEBQUOTE"."DP_RFQ_ITEM" ("ID")  ;
--------------------------------------------------------
--  Constraints for Table DP_MESSAGE
--------------------------------------------------------

  ALTER TABLE "WEBQUOTE"."DP_MESSAGE" MODIFY ("BAD_FORMED_CREATE_RFQ_MESSAGE" NOT NULL ENABLE);
  ALTER TABLE "WEBQUOTE"."DP_MESSAGE" MODIFY ("VERSION" NOT NULL ENABLE);
  ALTER TABLE "WEBQUOTE"."DP_MESSAGE" ADD CONSTRAINT "DP_MSG_PK" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "WEBQUOTE"."DP_MESSAGE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DP_RFQ
--------------------------------------------------------

  ALTER TABLE "WEBQUOTE"."DP_RFQ" MODIFY ("RFQ_CREATION_TIMESTAMP" NOT NULL ENABLE);
  ALTER TABLE "WEBQUOTE"."DP_RFQ" MODIFY ("QUOTE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "WEBQUOTE"."DP_RFQ" MODIFY ("SEGMENT" NOT NULL ENABLE);
  ALTER TABLE "WEBQUOTE"."DP_RFQ" MODIFY ("CUSTOMER_TYPE" NOT NULL ENABLE);
  ALTER TABLE "WEBQUOTE"."DP_RFQ" MODIFY ("SALES_PERSON_ID" NOT NULL ENABLE);
  ALTER TABLE "WEBQUOTE"."DP_RFQ" MODIFY ("SOURCE" NOT NULL ENABLE);
  ALTER TABLE "WEBQUOTE"."DP_RFQ" MODIFY ("SOLD_TO_CUSTOMERNAME" NOT NULL ENABLE);
  ALTER TABLE "WEBQUOTE"."DP_RFQ" MODIFY ("SOLD_TO_CUSTOMER_ACCOUNT_NO" NOT NULL ENABLE);
  ALTER TABLE "WEBQUOTE"."DP_RFQ" MODIFY ("SALES_ORGANIZATION" NOT NULL ENABLE);
  ALTER TABLE "WEBQUOTE"."DP_RFQ" MODIFY ("SALES_OFFICE" NOT NULL ENABLE);
  ALTER TABLE "WEBQUOTE"."DP_RFQ" MODIFY ("REFERENCE_ID" NOT NULL ENABLE);
  ALTER TABLE "WEBQUOTE"."DP_RFQ" MODIFY ("OPERATION" NOT NULL ENABLE);
  ALTER TABLE "WEBQUOTE"."DP_RFQ" MODIFY ("CONTACT_PHONE_NO" NOT NULL ENABLE);
  ALTER TABLE "WEBQUOTE"."DP_RFQ" MODIFY ("CONTACT_NAME" NOT NULL ENABLE);
  ALTER TABLE "WEBQUOTE"."DP_RFQ" MODIFY ("CONTACT_EMAIL_ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "WEBQUOTE"."DP_RFQ" MODIFY ("DP_MESSAGE_ID" NOT NULL ENABLE);
  ALTER TABLE "WEBQUOTE"."DP_RFQ" MODIFY ("LAST_UPDATE_TIME" NOT NULL ENABLE);
  ALTER TABLE "WEBQUOTE"."DP_RFQ" MODIFY ("CREATION_TIME" NOT NULL ENABLE);
  ALTER TABLE "WEBQUOTE"."DP_RFQ" ADD CONSTRAINT "DP_RFQ_PK" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "WEBQUOTE"."DP_RFQ" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DP_RFQ_ITEM
--------------------------------------------------------
ALTER TABLE DP_RFQ ADD CONSTRAINT DP_RFQ_UK1 UNIQUE (  REFERENCE_ID )ENABLE;
ALTER TABLE DP_RFQ_ITEM ADD CONSTRAINT DP_RFQ_ITEM_UK1 UNIQUE (  REFERENCE_LINE_ID )ENABLE;

  ALTER TABLE "WEBQUOTE"."DP_RFQ_ITEM" ADD CONSTRAINT "DP_RFQ_ITEM_PK" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "WEBQUOTE"."DP_RFQ_ITEM" MODIFY ("QUANTITY" NOT NULL ENABLE);
  ALTER TABLE "WEBQUOTE"."DP_RFQ_ITEM" MODIFY ("DP_RFQ_ID" NOT NULL ENABLE);
  ALTER TABLE "WEBQUOTE"."DP_RFQ_ITEM" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "WEBQUOTE"."DP_RFQ_ITEM" MODIFY ("REPROCESS_COUNT" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table DP_RFQ
--------------------------------------------------------

  ALTER TABLE "WEBQUOTE"."DP_RFQ" ADD CONSTRAINT "DP_RFQ_FK1" FOREIGN KEY ("DP_MESSAGE_ID")
	  REFERENCES "WEBQUOTE"."DP_MESSAGE" ("ID") ENABLE;
  ALTER TABLE "WEBQUOTE"."DP_RFQ" ADD CONSTRAINT "DP_RFQ_FK2" FOREIGN KEY ("QUOTE_ID")
	  REFERENCES "WEBQUOTE"."QUOTE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DP_RFQ_ITEM
--------------------------------------------------------

  ALTER TABLE "WEBQUOTE"."DP_RFQ_ITEM" ADD CONSTRAINT "DP_RFQ_ITEM_FK1" FOREIGN KEY ("DP_RFQ_ID")
	  REFERENCES "WEBQUOTE"."DP_RFQ" ("ID") ENABLE;
  ALTER TABLE "WEBQUOTE"."DP_RFQ_ITEM" ADD CONSTRAINT "DP_RFQ_ITEM_FK2" FOREIGN KEY ("QUOTE_ITEM_ID")
	  REFERENCES "WEBQUOTE"."QUOTE_ITEM" ("ID") ENABLE;
	  
	  

Insert into quote_number (DOC_TYPE,DESCRIPTION,NUMBER_PATTERN,NEXT_NUMBER,BIZ_UNIT) values ('DPQ',null,'DP#######',0000001,'EM ASIA');
Insert into quote_number (DOC_TYPE,DESCRIPTION,NUMBER_PATTERN,NEXT_NUMBER,BIZ_UNIT) values ('DPF',null,'DD#######',0000001,'EM ASIA');


update quote t set t.quote_source = 'INTERNAL' where t.quote_source is null;
update quote t set t.quote_source = 'DP' where t.id  in(select quote_id from quote_item t where t.quote_number like '%DP%')
ALTER TABLE QUOTE  MODIFY (QUOTE_SOURCE NOT NULL);


INSERT INTO "WEBQUOTE"."APP_PROPERTY" (PROP_KEY, PROP_VALUE, PROP_RESERVED) VALUES ('DP_INBOUND_PATH', '/app/eap62/webquote/dp/ecom2wq', '1');
INSERT INTO "WEBQUOTE"."APP_PROPERTY" (PROP_KEY, PROP_VALUE, PROP_RESERVED) VALUES ('DP_INBOUND_BACKUP_PATH', '/app/eap62/webquote/dp/ecom2wq/backup', '1');
INSERT INTO "WEBQUOTE"."APP_PROPERTY" (PROP_KEY, PROP_VALUE, PROP_RESERVED) VALUES ('DP_OUTBOUND_PATH', '/app/eap62/webquote/dp/wq2ecom', '1');
INSERT INTO "WEBQUOTE"."APP_PROPERTY" (PROP_KEY, PROP_VALUE, PROP_RESERVED) VALUES ('DP_INBOUND_FILE_NAME', 'CreateRFQRequest_', '1');
INSERT INTO "WEBQUOTE"."APP_PROPERTY" (PROP_KEY, PROP_VALUE, PROP_RESERVED) VALUES ('DP_OUTBOUND_FILE_NAME', 'UpdateRFQRequest_', '1');
INSERT INTO "WEBQUOTE"."APP_PROPERTY" (PROP_KEY, PROP_VALUE, PROP_RESERVED) VALUES ('DP_MAX_REPROCESS_COUNT', '10', '1');



ALTER TABLE quote_item  MODIFY (CUSTOMER_TYPE VARCHAR2(50 BYTE) );
ALTER TABLE quote_item_his  MODIFY (CUSTOMER_TYPE VARCHAR2(50 BYTE) );
ALTER TABLE quote  MODIFY (CUSTOMER_TYPE VARCHAR2(50 BYTE) );
ALTER TABLE DP_RFQ  MODIFY (CUSTOMER_TYPE VARCHAR2(50 BYTE) );
ALTER TABLE AUDIT_QUOTE_ITEM  MODIFY (CUSTOMER_TYPE_OLD VARCHAR2(50 BYTE) );
ALTER TABLE AUDIT_QUOTE_ITEM  MODIFY (CUSTOMER_TYPE_NEW VARCHAR2(50 BYTE) );