//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.13 at 05:07:46 PM CST 
//


package com.avnet.emasia.webquote.dp.xml.requestquote;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.avnet.emasia.webquote.dp.xml.requestquote package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName WEB_QUOTE_LINE_REQUEST_QUANTITY2_QNAME = new QName("http://remoting.qrt.avnet.com", "quantity2");
    private final static QName WEB_QUOTE_LINE_REQUEST_QUANTITY1_QNAME = new QName("http://remoting.qrt.avnet.com", "quantity1");
    private final static QName WEB_QUOTE_LINE_REQUEST_COMMENTS_QNAME = new QName("http://remoting.qrt.avnet.com", "comments");
    private final static QName WEB_QUOTE_LINE_REQUEST_REFERENCE_LINEID_QNAME = new QName("http://remoting.qrt.avnet.com", "referenceLineID");
    private final static QName WEB_QUOTE_LINE_REQUEST_REQUESTED_MANUFACTURE_QNAME = new QName("http://remoting.qrt.avnet.com", "requestedManufacturer");
    private final static QName WEB_QUOTE_LINE_REQUEST_TARGET_RESALE_QNAME = new QName("http://remoting.qrt.avnet.com", "targetResale");
    private final static QName WEB_QUOTE_LINE_REQUEST_REQUESTED_PARTS_QNAME = new QName("http://remoting.qrt.avnet.com", "requestedPart");
    private final static QName WEB_QUOTE_LINE_REQUEST_REQUESTED_DESCRIPTION_QNAME = new QName("http://remoting.qrt.avnet.com", "requestedDescription");
    private final static QName WEB_QUOTE_LINE_REQUEST_LINE_STATUSDESC_QNAME = new QName("http://remoting.qrt.avnet.com", "lineStatusDesc");
    private final static QName WEB_QUOTE_LINE_REQUEST_REQUESTED_TLA_QNAME = new QName("http://remoting.qrt.avnet.com", "requestedTLA");
    private final static QName WEB_QUOTE_LINE_REQUEST_QUANTITY3_QNAME = new QName("http://remoting.qrt.avnet.com", "quantity3");
    private final static QName WEB_QUOTE_LINE_REQUEST_LINE_STATUS_CODE_QNAME = new QName("http://remoting.qrt.avnet.com", "lineStatusCode");
    private final static QName WEB_REQUEST_OBJECT_SHIP_TO_ADDRESS_1ST_LINE_QNAME = new QName("http://remoting.qrt.avnet.com", "shipToAddress1stLine");
    private final static QName WEB_REQUEST_OBJECT_END_USER_ACCOUNTNO_QNAME = new QName("http://remoting.qrt.avnet.com", "endUserAccountNo");
    private final static QName WEB_REQUEST_OBJECT_REFERENCEID_QNAME = new QName("http://remoting.qrt.avnet.com", "referenceID");
    private final static QName WEB_REQUEST_OBJECT_SHIP_TO_ADDRESS_CITY_QNAME = new QName("http://remoting.qrt.avnet.com", "shipToAddressCity");
    private final static QName WEB_REQUEST_OBJECT_SHIP_TO_ADDRESS_2ND_LINE_QNAME = new QName("http://remoting.qrt.avnet.com", "shipToAddress2ndLine");
    private final static QName WEB_REQUEST_OBJECT_CUSTOMER_QUOTE_QNAME = new QName("http://remoting.qrt.avnet.com", "customerQuote");
    private final static QName WEB_REQUEST_OBJECT_SHIP_TO_ADDRESS_COUNTERY_QNAME = new QName("http://remoting.qrt.avnet.com", "shipToAddressCountry");
    private final static QName WEB_REQUEST_OBJECT_SALES_OFFICE_QNAME = new QName("http://remoting.qrt.avnet.com", "salesOffice");
    private final static QName WEB_REQUEST_OBJECT_SOLD_TO_CUSTOMER_ACCOUNT_NO_QNAME = new QName("http://remoting.qrt.avnet.com", "soldToCustomerAccountNo");
    private final static QName WEB_REQUEST_OBJECT_DATE_DUE_TO_COSTUMER_QNAME = new QName("http://remoting.qrt.avnet.com", "dateDuetoCustomer");
    private final static QName WEB_REQUEST_OBJECT_QUOTE_STATUS_QNAME = new QName("http://remoting.qrt.avnet.com", "quoteStatus");
    private final static QName WEB_REQUEST_OBJECT_SOLD_TO_ADDRESS_2ND_LINE_QNAME = new QName("http://remoting.qrt.avnet.com", "soldToAddress2ndLine");
    private final static QName WEB_REQUEST_OBJECT_CONTACT_EMAIL_ADDRESS_QNAME = new QName("http://remoting.qrt.avnet.com", "contactEmailAddress");
    private final static QName WEB_REQUEST_OBJECT_SOLD_TO_CUSTOMER_NAME_QNAME = new QName("http://remoting.qrt.avnet.com", "soldToCustomerName");
    private final static QName WEB_REQUEST_OBJECT_OPERATION_QNAME = new QName("http://remoting.qrt.avnet.com", "operation");
    private final static QName WEB_REQUEST_OBJECT_SOLD_TO_ATTENTION_QNAME = new QName("http://remoting.qrt.avnet.com", "soldToAttention");
    private final static QName WEB_REQUEST_OBJECT_SHIP_TO_ADDRESS_STATE_QNAME = new QName("http://remoting.qrt.avnet.com", "shipToAddressState");
    private final static QName WEB_REQUEST_OBJECT_HEADER_STATUS_DESC_QNAME = new QName("http://remoting.qrt.avnet.com", "headerStatusDesc");
    private final static QName WEB_REQUEST_OBJECT_SHIP_TO_ADDRESS_ZIPCODE_QNAME = new QName("http://remoting.qrt.avnet.com", "shipToAddresszipCode");
    private final static QName WEB_REQUEST_OBJECT_SHIP_TO_ADDRESS_1STLINE_QNAME = new QName("http://remoting.qrt.avnet.com", "soldToAddress1stLine");
    private final static QName WEB_REQUEST_OBJECT_SHIP_ACCOUNT_NO_QNAME = new QName("http://remoting.qrt.avnet.com", "shipToAccountNo");
    private final static QName WEB_REQUEST_OBJECT_COSTOMER_TYPE_QNAME = new QName("http://remoting.qrt.avnet.com", "customerType");
    private final static QName WEB_REQUEST_OBJECT_SHIP_TO_ATTENTION_QNAME = new QName("http://remoting.qrt.avnet.com", "shipToAttention");
    private final static QName WEB_REQUEST_OBJECT_SHIP_TO_ADDRESS_3RD_LINE_QNAME = new QName("http://remoting.qrt.avnet.com", "shipToAddress3rdLine");
    private final static QName WEB_REQUEST_OBJECT_SHIP_TO_CUSTOMER_NAME_QNAME = new QName("http://remoting.qrt.avnet.com", "shipToCustomerName");
    private final static QName WEB_REQUEST_OBJECT_CUSTOMER_ON_DOCK_DATE_QNAME = new QName("http://remoting.qrt.avnet.com", "customerOnDockDate");
    private final static QName WEB_REQUEST_OBJECT_QUOTEID_QNAME = new QName("http://remoting.qrt.avnet.com", "quoteId");
    private final static QName WEB_REQUEST_OBJECT_SOLD_TO_ADDRESS_ZIPCODE_QNAME = new QName("http://remoting.qrt.avnet.com", "soldToAddresszipCode");
    private final static QName WEB_REQUEST_OBJECT_SOLD_TO_ADDRESS_STATE_QNAME = new QName("http://remoting.qrt.avnet.com", "soldToAddressState");
    private final static QName WEB_REQUEST_OBJECT_SOLD_TO_ADDRESS_3RD_LINE_QNAME = new QName("http://remoting.qrt.avnet.com", "soldToAddress3rdLine");
    private final static QName WEB_REQUEST_OBJECT_CONTACT_PHONE_NO_QNAME = new QName("http://remoting.qrt.avnet.com", "contactPhoneNo");
    private final static QName WEB_REQUEST_OBJECT_HEADER_STATUS_CODE_QNAME = new QName("http://remoting.qrt.avnet.com", "headerStatusCode");
    private final static QName WEB_REQUEST_OBJECT_SALES_ORGANIZATION_QNAME = new QName("http://remoting.qrt.avnet.com", "salesOrganization");
    private final static QName WEB_REQUEST_OBJECT_INPUT_METHOD_QNAME = new QName("http://remoting.qrt.avnet.com", "inputMethod");
    private final static QName WEB_REQUEST_OBJECT_SOLD_TO_ADDRESS_CITY_QNAME = new QName("http://remoting.qrt.avnet.com", "soldToAddressCity");
    private final static QName WEB_REQUEST_OBJECT_SOLD_TO_ADDRESS_COUNTERY_QNAME = new QName("http://remoting.qrt.avnet.com", "soldToAddressCountry");
    private final static QName WEB_REQUEST_OBJECT_END_COSTUMER_ACCOUNT_NO_QNAME = new QName("http://remoting.qrt.avnet.com", "endCustomerAccountNo");
    private final static QName WEB_REQUEST_OBJECT_CONTACT_NAME_QNAME = new QName("http://remoting.qrt.avnet.com", "contactName");
    private final static QName WEB_REQUEST_OBJECT_SOURCE_QNAME = new QName("http://remoting.qrt.avnet.com", "source");
    private final static QName WEB_REQUEST_OBJECT_DATE_DUE_TO_SALE_QNAME = new QName("http://remoting.qrt.avnet.com", "dateDuetoSales");
    private final static QName WEB_REQUEST_OBJECT_QUOTE_PROJECT_ON_BOARD_NAME_QNAME = new QName("http://remoting.qrt.avnet.com", "quoteProjectOrBoardName");
    private final static QName WEB_RESPONSE_OBJECT_REFERENCE_ID_QNAME = new QName("http://remoting.qrt.avnet.com", "referenceId");
    private final static QName WEB_RESPONSE_OBJECT_LINE_ERROR_DESC_QNAME = new QName("http://remoting.qrt.avnet.com", "lineErrorDesc");
    private final static QName WEB_RESPONSE_OBJECT_RESPONCE_CODE_QNAME = new QName("http://remoting.qrt.avnet.com", "responseCode");
    private final static QName WEB_RESPONSE_OBJECT_HEADER_ERROR_CODE_QNAME = new QName("http://remoting.qrt.avnet.com", "headerErrorCode");
    private final static QName WEB_RESPONSE_OBJECT_LINE_ERROR_CODE_QNAME = new QName("http://remoting.qrt.avnet.com", "lineErrorCode");
    private final static QName WEB_RESPONSE_OBJECT_HEADER_ERROR_DESC_QNAME = new QName("http://remoting.qrt.avnet.com", "headerErrorDesc");
    private final static QName WEB_RESPONSE_OBJECT_RESPONSE_DESC_QNAME = new QName("http://remoting.qrt.avnet.com", "responseDesc");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.avnet.emasia.webquote.dp.xml.requestquote
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link WebRequestObject }
     * 
     */
    public WebRequestObject createWebRequestObject() {
        return new WebRequestObject();
    }

    /**
     * Create an instance of {@link WebQuoteLineRequest }
     * 
     */
    public WebQuoteLineRequest createWebQuoteLineRequest() {
        return new WebQuoteLineRequest();
    }

    /**
     * Create an instance of {@link WebResponseObject }
     * 
     */
    public WebResponseObject createWebResponseObject() {
        return new WebResponseObject();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://remoting.qrt.avnet.com", name = "quantity2", scope = WebQuoteLineRequest.class)
    public JAXBElement<String> createWebQuoteLineRequestQuantity2(String value) {
        return new JAXBElement<String>(WEB_QUOTE_LINE_REQUEST_QUANTITY2_QNAME, String.class, WebQuoteLineRequest.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://remoting.qrt.avnet.com", name = "quantity1", scope = WebQuoteLineRequest.class)
    public JAXBElement<String> createWebQuoteLineRequestQuantity1(String value) {
        return new JAXBElement<String>(WEB_QUOTE_LINE_REQUEST_QUANTITY1_QNAME, String.class, WebQuoteLineRequest.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://remoting.qrt.avnet.com", name = "comments", scope = WebQuoteLineRequest.class)
    public JAXBElement<String> createWebQuoteLineRequestComments(String value) {
        return new JAXBElement<String>(WEB_QUOTE_LINE_REQUEST_COMMENTS_QNAME, String.class, WebQuoteLineRequest.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://remoting.qrt.avnet.com", name = "referenceLineID", scope = WebQuoteLineRequest.class)
    public JAXBElement<String> createWebQuoteLineRequestReferenceLineID(String value) {
        return new JAXBElement<String>(WEB_QUOTE_LINE_REQUEST_REFERENCE_LINEID_QNAME, String.class, WebQuoteLineRequest.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://remoting.qrt.avnet.com", name = "requestedManufacturer", scope = WebQuoteLineRequest.class)
    public JAXBElement<String> createWebQuoteLineRequestRequestedManufacturer(String value) {
        return new JAXBElement<String>(WEB_QUOTE_LINE_REQUEST_REQUESTED_MANUFACTURE_QNAME, String.class, WebQuoteLineRequest.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://remoting.qrt.avnet.com", name = "targetResale", scope = WebQuoteLineRequest.class)
    public JAXBElement<String> createWebQuoteLineRequestTargetResale(String value) {
        return new JAXBElement<String>(WEB_QUOTE_LINE_REQUEST_TARGET_RESALE_QNAME, String.class, WebQuoteLineRequest.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://remoting.qrt.avnet.com", name = "requestedPart", scope = WebQuoteLineRequest.class)
    public JAXBElement<String> createWebQuoteLineRequestRequestedPart(String value) {
        return new JAXBElement<String>(WEB_QUOTE_LINE_REQUEST_REQUESTED_PARTS_QNAME, String.class, WebQuoteLineRequest.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://remoting.qrt.avnet.com", name = "requestedDescription", scope = WebQuoteLineRequest.class)
    public JAXBElement<String> createWebQuoteLineRequestRequestedDescription(String value) {
        return new JAXBElement<String>(WEB_QUOTE_LINE_REQUEST_REQUESTED_DESCRIPTION_QNAME, String.class, WebQuoteLineRequest.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://remoting.qrt.avnet.com", name = "lineStatusDesc", scope = WebQuoteLineRequest.class)
    public JAXBElement<String> createWebQuoteLineRequestLineStatusDesc(String value) {
        return new JAXBElement<String>(WEB_QUOTE_LINE_REQUEST_LINE_STATUSDESC_QNAME, String.class, WebQuoteLineRequest.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://remoting.qrt.avnet.com", name = "requestedTLA", scope = WebQuoteLineRequest.class)
    public JAXBElement<String> createWebQuoteLineRequestRequestedTLA(String value) {
        return new JAXBElement<String>(WEB_QUOTE_LINE_REQUEST_REQUESTED_TLA_QNAME, String.class, WebQuoteLineRequest.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://remoting.qrt.avnet.com", name = "quantity3", scope = WebQuoteLineRequest.class)
    public JAXBElement<String> createWebQuoteLineRequestQuantity3(String value) {
        return new JAXBElement<String>(WEB_QUOTE_LINE_REQUEST_QUANTITY3_QNAME, String.class, WebQuoteLineRequest.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://remoting.qrt.avnet.com", name = "lineStatusCode", scope = WebQuoteLineRequest.class)
    public JAXBElement<String> createWebQuoteLineRequestLineStatusCode(String value) {
        return new JAXBElement<String>(WEB_QUOTE_LINE_REQUEST_LINE_STATUS_CODE_QNAME, String.class, WebQuoteLineRequest.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://remoting.qrt.avnet.com", name = "shipToAddress1stLine", scope = WebRequestObject.class)
    public JAXBElement<String> createWebRequestObjectShipToAddress1StLine(String value) {
        return new JAXBElement<String>(WEB_REQUEST_OBJECT_SHIP_TO_ADDRESS_1ST_LINE_QNAME, String.class, WebRequestObject.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://remoting.qrt.avnet.com", name = "endUserAccountNo", scope = WebRequestObject.class)
    public JAXBElement<String> createWebRequestObjectEndUserAccountNo(String value) {
        return new JAXBElement<String>(WEB_REQUEST_OBJECT_END_USER_ACCOUNTNO_QNAME, String.class, WebRequestObject.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://remoting.qrt.avnet.com", name = "referenceID", scope = WebRequestObject.class)
    public JAXBElement<String> createWebRequestObjectReferenceID(String value) {
        return new JAXBElement<String>(WEB_REQUEST_OBJECT_REFERENCEID_QNAME, String.class, WebRequestObject.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://remoting.qrt.avnet.com", name = "shipToAddressCity", scope = WebRequestObject.class)
    public JAXBElement<String> createWebRequestObjectShipToAddressCity(String value) {
        return new JAXBElement<String>(WEB_REQUEST_OBJECT_SHIP_TO_ADDRESS_CITY_QNAME, String.class, WebRequestObject.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://remoting.qrt.avnet.com", name = "shipToAddress2ndLine", scope = WebRequestObject.class)
    public JAXBElement<String> createWebRequestObjectShipToAddress2NdLine(String value) {
        return new JAXBElement<String>(WEB_REQUEST_OBJECT_SHIP_TO_ADDRESS_2ND_LINE_QNAME, String.class, WebRequestObject.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://remoting.qrt.avnet.com", name = "customerQuote", scope = WebRequestObject.class)
    public JAXBElement<String> createWebRequestObjectCustomerQuote(String value) {
        return new JAXBElement<String>(WEB_REQUEST_OBJECT_CUSTOMER_QUOTE_QNAME, String.class, WebRequestObject.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://remoting.qrt.avnet.com", name = "shipToAddressCountry", scope = WebRequestObject.class)
    public JAXBElement<String> createWebRequestObjectShipToAddressCountry(String value) {
        return new JAXBElement<String>(WEB_REQUEST_OBJECT_SHIP_TO_ADDRESS_COUNTERY_QNAME, String.class, WebRequestObject.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://remoting.qrt.avnet.com", name = "salesOffice", scope = WebRequestObject.class)
    public JAXBElement<String> createWebRequestObjectSalesOffice(String value) {
        return new JAXBElement<String>(WEB_REQUEST_OBJECT_SALES_OFFICE_QNAME, String.class, WebRequestObject.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://remoting.qrt.avnet.com", name = "soldToCustomerAccountNo", scope = WebRequestObject.class)
    public JAXBElement<String> createWebRequestObjectSoldToCustomerAccountNo(String value) {
        return new JAXBElement<String>(WEB_REQUEST_OBJECT_SOLD_TO_CUSTOMER_ACCOUNT_NO_QNAME, String.class, WebRequestObject.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://remoting.qrt.avnet.com", name = "dateDuetoCustomer", scope = WebRequestObject.class)
    public JAXBElement<XMLGregorianCalendar> createWebRequestObjectDateDuetoCustomer(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(WEB_REQUEST_OBJECT_DATE_DUE_TO_COSTUMER_QNAME, XMLGregorianCalendar.class, WebRequestObject.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://remoting.qrt.avnet.com", name = "quoteStatus", scope = WebRequestObject.class)
    public JAXBElement<String> createWebRequestObjectQuoteStatus(String value) {
        return new JAXBElement<String>(WEB_REQUEST_OBJECT_QUOTE_STATUS_QNAME, String.class, WebRequestObject.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://remoting.qrt.avnet.com", name = "soldToAddress2ndLine", scope = WebRequestObject.class)
    public JAXBElement<String> createWebRequestObjectSoldToAddress2NdLine(String value) {
        return new JAXBElement<String>(WEB_REQUEST_OBJECT_SOLD_TO_ADDRESS_2ND_LINE_QNAME, String.class, WebRequestObject.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://remoting.qrt.avnet.com", name = "contactEmailAddress", scope = WebRequestObject.class)
    public JAXBElement<String> createWebRequestObjectContactEmailAddress(String value) {
        return new JAXBElement<String>(WEB_REQUEST_OBJECT_CONTACT_EMAIL_ADDRESS_QNAME, String.class, WebRequestObject.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://remoting.qrt.avnet.com", name = "soldToCustomerName", scope = WebRequestObject.class)
    public JAXBElement<String> createWebRequestObjectSoldToCustomerName(String value) {
        return new JAXBElement<String>(WEB_REQUEST_OBJECT_SOLD_TO_CUSTOMER_NAME_QNAME, String.class, WebRequestObject.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://remoting.qrt.avnet.com", name = "operation", scope = WebRequestObject.class)
    public JAXBElement<String> createWebRequestObjectOperation(String value) {
        return new JAXBElement<String>(WEB_REQUEST_OBJECT_OPERATION_QNAME, String.class, WebRequestObject.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://remoting.qrt.avnet.com", name = "soldToAttention", scope = WebRequestObject.class)
    public JAXBElement<String> createWebRequestObjectSoldToAttention(String value) {
        return new JAXBElement<String>(WEB_REQUEST_OBJECT_SOLD_TO_ATTENTION_QNAME, String.class, WebRequestObject.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://remoting.qrt.avnet.com", name = "shipToAddressState", scope = WebRequestObject.class)
    public JAXBElement<String> createWebRequestObjectShipToAddressState(String value) {
        return new JAXBElement<String>(WEB_REQUEST_OBJECT_SHIP_TO_ADDRESS_STATE_QNAME, String.class, WebRequestObject.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://remoting.qrt.avnet.com", name = "headerStatusDesc", scope = WebRequestObject.class)
    public JAXBElement<String> createWebRequestObjectHeaderStatusDesc(String value) {
        return new JAXBElement<String>(WEB_REQUEST_OBJECT_HEADER_STATUS_DESC_QNAME, String.class, WebRequestObject.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://remoting.qrt.avnet.com", name = "shipToAddresszipCode", scope = WebRequestObject.class)
    public JAXBElement<String> createWebRequestObjectShipToAddresszipCode(String value) {
        return new JAXBElement<String>(WEB_REQUEST_OBJECT_SHIP_TO_ADDRESS_ZIPCODE_QNAME, String.class, WebRequestObject.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://remoting.qrt.avnet.com", name = "soldToAddress1stLine", scope = WebRequestObject.class)
    public JAXBElement<String> createWebRequestObjectSoldToAddress1StLine(String value) {
        return new JAXBElement<String>(WEB_REQUEST_OBJECT_SHIP_TO_ADDRESS_1STLINE_QNAME, String.class, WebRequestObject.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://remoting.qrt.avnet.com", name = "shipToAccountNo", scope = WebRequestObject.class)
    public JAXBElement<String> createWebRequestObjectShipToAccountNo(String value) {
        return new JAXBElement<String>(WEB_REQUEST_OBJECT_SHIP_ACCOUNT_NO_QNAME, String.class, WebRequestObject.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://remoting.qrt.avnet.com", name = "customerType", scope = WebRequestObject.class)
    public JAXBElement<String> createWebRequestObjectCustomerType(String value) {
        return new JAXBElement<String>(WEB_REQUEST_OBJECT_COSTOMER_TYPE_QNAME, String.class, WebRequestObject.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://remoting.qrt.avnet.com", name = "shipToAttention", scope = WebRequestObject.class)
    public JAXBElement<String> createWebRequestObjectShipToAttention(String value) {
        return new JAXBElement<String>(WEB_REQUEST_OBJECT_SHIP_TO_ATTENTION_QNAME, String.class, WebRequestObject.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://remoting.qrt.avnet.com", name = "shipToAddress3rdLine", scope = WebRequestObject.class)
    public JAXBElement<String> createWebRequestObjectShipToAddress3RdLine(String value) {
        return new JAXBElement<String>(WEB_REQUEST_OBJECT_SHIP_TO_ADDRESS_3RD_LINE_QNAME, String.class, WebRequestObject.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://remoting.qrt.avnet.com", name = "shipToCustomerName", scope = WebRequestObject.class)
    public JAXBElement<String> createWebRequestObjectShipToCustomerName(String value) {
        return new JAXBElement<String>(WEB_REQUEST_OBJECT_SHIP_TO_CUSTOMER_NAME_QNAME, String.class, WebRequestObject.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://remoting.qrt.avnet.com", name = "customerOnDockDate", scope = WebRequestObject.class)
    public JAXBElement<XMLGregorianCalendar> createWebRequestObjectCustomerOnDockDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(WEB_REQUEST_OBJECT_CUSTOMER_ON_DOCK_DATE_QNAME, XMLGregorianCalendar.class, WebRequestObject.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://remoting.qrt.avnet.com", name = "quoteId", scope = WebRequestObject.class)
    public JAXBElement<String> createWebRequestObjectQuoteId(String value) {
        return new JAXBElement<String>(WEB_REQUEST_OBJECT_QUOTEID_QNAME, String.class, WebRequestObject.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://remoting.qrt.avnet.com", name = "soldToAddresszipCode", scope = WebRequestObject.class)
    public JAXBElement<String> createWebRequestObjectSoldToAddresszipCode(String value) {
        return new JAXBElement<String>(WEB_REQUEST_OBJECT_SOLD_TO_ADDRESS_ZIPCODE_QNAME, String.class, WebRequestObject.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://remoting.qrt.avnet.com", name = "soldToAddressState", scope = WebRequestObject.class)
    public JAXBElement<String> createWebRequestObjectSoldToAddressState(String value) {
        return new JAXBElement<String>(WEB_REQUEST_OBJECT_SOLD_TO_ADDRESS_STATE_QNAME, String.class, WebRequestObject.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://remoting.qrt.avnet.com", name = "soldToAddress3rdLine", scope = WebRequestObject.class)
    public JAXBElement<String> createWebRequestObjectSoldToAddress3RdLine(String value) {
        return new JAXBElement<String>(WEB_REQUEST_OBJECT_SOLD_TO_ADDRESS_3RD_LINE_QNAME, String.class, WebRequestObject.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://remoting.qrt.avnet.com", name = "contactPhoneNo", scope = WebRequestObject.class)
    public JAXBElement<String> createWebRequestObjectContactPhoneNo(String value) {
        return new JAXBElement<String>(WEB_REQUEST_OBJECT_CONTACT_PHONE_NO_QNAME, String.class, WebRequestObject.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://remoting.qrt.avnet.com", name = "headerStatusCode", scope = WebRequestObject.class)
    public JAXBElement<String> createWebRequestObjectHeaderStatusCode(String value) {
        return new JAXBElement<String>(WEB_REQUEST_OBJECT_HEADER_STATUS_CODE_QNAME, String.class, WebRequestObject.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://remoting.qrt.avnet.com", name = "salesOrganization", scope = WebRequestObject.class)
    public JAXBElement<String> createWebRequestObjectSalesOrganization(String value) {
        return new JAXBElement<String>(WEB_REQUEST_OBJECT_SALES_ORGANIZATION_QNAME, String.class, WebRequestObject.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://remoting.qrt.avnet.com", name = "inputMethod", scope = WebRequestObject.class)
    public JAXBElement<String> createWebRequestObjectInputMethod(String value) {
        return new JAXBElement<String>(WEB_REQUEST_OBJECT_INPUT_METHOD_QNAME, String.class, WebRequestObject.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://remoting.qrt.avnet.com", name = "soldToAddressCity", scope = WebRequestObject.class)
    public JAXBElement<String> createWebRequestObjectSoldToAddressCity(String value) {
        return new JAXBElement<String>(WEB_REQUEST_OBJECT_SOLD_TO_ADDRESS_CITY_QNAME, String.class, WebRequestObject.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://remoting.qrt.avnet.com", name = "soldToAddressCountry", scope = WebRequestObject.class)
    public JAXBElement<String> createWebRequestObjectSoldToAddressCountry(String value) {
        return new JAXBElement<String>(WEB_REQUEST_OBJECT_SOLD_TO_ADDRESS_COUNTERY_QNAME, String.class, WebRequestObject.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://remoting.qrt.avnet.com", name = "endCustomerAccountNo", scope = WebRequestObject.class)
    public JAXBElement<String> createWebRequestObjectEndCustomerAccountNo(String value) {
        return new JAXBElement<String>(WEB_REQUEST_OBJECT_END_COSTUMER_ACCOUNT_NO_QNAME, String.class, WebRequestObject.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://remoting.qrt.avnet.com", name = "contactName", scope = WebRequestObject.class)
    public JAXBElement<String> createWebRequestObjectContactName(String value) {
        return new JAXBElement<String>(WEB_REQUEST_OBJECT_CONTACT_NAME_QNAME, String.class, WebRequestObject.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://remoting.qrt.avnet.com", name = "source", scope = WebRequestObject.class)
    public JAXBElement<String> createWebRequestObjectSource(String value) {
        return new JAXBElement<String>(WEB_REQUEST_OBJECT_SOURCE_QNAME, String.class, WebRequestObject.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://remoting.qrt.avnet.com", name = "dateDuetoSales", scope = WebRequestObject.class)
    public JAXBElement<XMLGregorianCalendar> createWebRequestObjectDateDuetoSales(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(WEB_REQUEST_OBJECT_DATE_DUE_TO_SALE_QNAME, XMLGregorianCalendar.class, WebRequestObject.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://remoting.qrt.avnet.com", name = "quoteProjectOrBoardName", scope = WebRequestObject.class)
    public JAXBElement<String> createWebRequestObjectQuoteProjectOrBoardName(String value) {
        return new JAXBElement<String>(WEB_REQUEST_OBJECT_QUOTE_PROJECT_ON_BOARD_NAME_QNAME, String.class, WebRequestObject.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://remoting.qrt.avnet.com", name = "referenceId", scope = WebResponseObject.class)
    public JAXBElement<String> createWebResponseObjectReferenceId(String value) {
        return new JAXBElement<String>(WEB_RESPONSE_OBJECT_REFERENCE_ID_QNAME, String.class, WebResponseObject.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://remoting.qrt.avnet.com", name = "lineErrorDesc", scope = WebResponseObject.class)
    public JAXBElement<String> createWebResponseObjectLineErrorDesc(String value) {
        return new JAXBElement<String>(WEB_RESPONSE_OBJECT_LINE_ERROR_DESC_QNAME, String.class, WebResponseObject.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://remoting.qrt.avnet.com", name = "responseCode", scope = WebResponseObject.class)
    public JAXBElement<String> createWebResponseObjectResponseCode(String value) {
        return new JAXBElement<String>(WEB_RESPONSE_OBJECT_RESPONCE_CODE_QNAME, String.class, WebResponseObject.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://remoting.qrt.avnet.com", name = "operation", scope = WebResponseObject.class)
    public JAXBElement<String> createWebResponseObjectOperation(String value) {
        return new JAXBElement<String>(WEB_REQUEST_OBJECT_OPERATION_QNAME, String.class, WebResponseObject.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://remoting.qrt.avnet.com", name = "headerErrorCode", scope = WebResponseObject.class)
    public JAXBElement<String> createWebResponseObjectHeaderErrorCode(String value) {
        return new JAXBElement<String>(WEB_RESPONSE_OBJECT_HEADER_ERROR_CODE_QNAME, String.class, WebResponseObject.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://remoting.qrt.avnet.com", name = "lineErrorCode", scope = WebResponseObject.class)
    public JAXBElement<String> createWebResponseObjectLineErrorCode(String value) {
        return new JAXBElement<String>(WEB_RESPONSE_OBJECT_LINE_ERROR_CODE_QNAME, String.class, WebResponseObject.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://remoting.qrt.avnet.com", name = "headerErrorDesc", scope = WebResponseObject.class)
    public JAXBElement<String> createWebResponseObjectHeaderErrorDesc(String value) {
        return new JAXBElement<String>(WEB_RESPONSE_OBJECT_HEADER_ERROR_DESC_QNAME, String.class, WebResponseObject.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://remoting.qrt.avnet.com", name = "responseDesc", scope = WebResponseObject.class)
    public JAXBElement<String> createWebResponseObjectResponseDesc(String value) {
        return new JAXBElement<String>(WEB_RESPONSE_OBJECT_RESPONSE_DESC_QNAME, String.class, WebResponseObject.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://remoting.qrt.avnet.com", name = "quoteId", scope = WebResponseObject.class)
    public JAXBElement<String> createWebResponseObjectQuoteId(String value) {
        return new JAXBElement<String>(WEB_REQUEST_OBJECT_QUOTEID_QNAME, String.class, WebResponseObject.class, value);
    }

}
