//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.13 at 03:43:24 PM CST 
//


package com.avnet.emasia.webquote.dp.xml.requestquote;

import javax.validation.constraints.Digits;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WebQuoteLineRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WebQuoteLineRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="comments" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="lineStatusCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="lineStatusDesc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="quantity1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="quantity2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="quantity3" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="referenceLineID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="requestedDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="requestedManufacturer" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="requestedPart" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="requestedTLA" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="targetResale" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="currency" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WebQuoteLineRequest", propOrder = {
    "comments",
    "lineStatusCode",
    "lineStatusDesc",
    "quantity1",
    "quantity2",
    "quantity3",
    "referenceLineID",
    "requestedDescription",
    "requestedManufacturer",
    "requestedPart",
    "requestedTLA",
    "targetResale",
    "currency"
})
public class WebQuoteLineRequest {

/*    @XmlElementRef(name = "comments", namespace = "http://remoting.qrt.avnet.com", type = JAXBElement.class, required = false)
    protected JAXBElement<String> comments;
    @XmlElementRef(name = "lineStatusCode", namespace = "http://remoting.qrt.avnet.com", type = JAXBElement.class, required = false)
    protected JAXBElement<String> lineStatusCode;
    @XmlElementRef(name = "lineStatusDesc", namespace = "http://remoting.qrt.avnet.com", type = JAXBElement.class, required = false)
    protected JAXBElement<String> lineStatusDesc;
    @XmlElementRef(name = "quantity1", namespace = "http://remoting.qrt.avnet.com", type = JAXBElement.class, required = false)
    protected JAXBElement<String> quantity1;
    @XmlElementRef(name = "quantity2", namespace = "http://remoting.qrt.avnet.com", type = JAXBElement.class, required = false)
    protected JAXBElement<String> quantity2;
    @XmlElementRef(name = "quantity3", namespace = "http://remoting.qrt.avnet.com", type = JAXBElement.class, required = false)
    protected JAXBElement<String> quantity3;
    @XmlElementRef(name = "referenceLineID", namespace = "http://remoting.qrt.avnet.com", type = JAXBElement.class, required = false)
    protected JAXBElement<String> referenceLineID;
    @XmlElementRef(name = "requestedDescription", namespace = "http://remoting.qrt.avnet.com", type = JAXBElement.class, required = false)
    protected JAXBElement<String> requestedDescription;
    @XmlElementRef(name = "requestedManufacturer", namespace = "http://remoting.qrt.avnet.com", type = JAXBElement.class, required = false)
    protected JAXBElement<String> requestedManufacturer;
    @XmlElementRef(name = "requestedPart", namespace = "http://remoting.qrt.avnet.com", type = JAXBElement.class, required = false)
    protected JAXBElement<String> requestedPart;
    @XmlElementRef(name = "requestedTLA", namespace = "http://remoting.qrt.avnet.com", type = JAXBElement.class, required = false)
    protected JAXBElement<String> requestedTLA;
    @XmlElementRef(name = "targetResale", namespace = "http://remoting.qrt.avnet.com", type = JAXBElement.class, required = false)
    protected JAXBElement<String> targetResale;*/
	
    protected String comments;
    protected String lineStatusCode;
    protected String lineStatusDesc;
    
	@NotNull(message="quantity field is invalid.")
	@Size(min=1, message="quantity field is invalid.")
    protected String quantity1;
	
    protected String quantity2;
    protected String quantity3;
    
	@NotNull(message="referenceLineId field is invalid.")
	@Size(min=1, message="referenceLineId field is invalid.")
    protected String referenceLineID;
	
    protected String requestedDescription;
    
	@NotNull(message="requestedManufacturer field is invalid.")
	@Size(min=1, message="requestedManufacturer field is invalid.")
    protected String requestedManufacturer;
	
	@NotNull(message="requestedPart field is invalid.")
	@Size(min=1, message="requestedPart field is invalid.")
    protected String requestedPart;
	
    protected String requestedTLA;
    
	@NotNull(message="targetResale field is invalid.")
    protected String targetResale;

    @NotNull(message="currency field is invalid.")
	@Size(min=1, message="currency field is invalid.")
    protected String currency;
    
	public String getComments() {
		return comments;
	}
	public void setComments(String comments) {
		this.comments = comments;
	}
	public String getLineStatusCode() {
		return lineStatusCode;
	}
	public void setLineStatusCode(String lineStatusCode) {
		this.lineStatusCode = lineStatusCode;
	}
	public String getLineStatusDesc() {
		return lineStatusDesc;
	}
	public void setLineStatusDesc(String lineStatusDesc) {
		this.lineStatusDesc = lineStatusDesc;
	}
	public String getQuantity1() {
		return quantity1;
	}
	public void setQuantity1(String quantity1) {
		this.quantity1 = quantity1;
	}
	public String getQuantity2() {
		return quantity2;
	}
	public void setQuantity2(String quantity2) {
		this.quantity2 = quantity2;
	}
	public String getQuantity3() {
		return quantity3;
	}
	public void setQuantity3(String quantity3) {
		this.quantity3 = quantity3;
	}
	public String getReferenceLineID() {
		return referenceLineID;
	}
	public void setReferenceLineID(String referenceLineID) {
		this.referenceLineID = referenceLineID;
	}
	public String getRequestedDescription() {
		return requestedDescription;
	}
	public void setRequestedDescription(String requestedDescription) {
		this.requestedDescription = requestedDescription;
	}
	public String getRequestedManufacturer() {
		return requestedManufacturer;
	}
	public void setRequestedManufacturer(String requestedManufacturer) {
		this.requestedManufacturer = requestedManufacturer;
	}
	public String getRequestedPart() {
		return requestedPart;
	}
	public void setRequestedPart(String requestedPart) {
		this.requestedPart = requestedPart;
	}
	public String getRequestedTLA() {
		return requestedTLA;
	}
	public void setRequestedTLA(String requestedTLA) {
		this.requestedTLA = requestedTLA;
	}
	public String getTargetResale() {
		return targetResale;
	}
	public void setTargetResale(String targetResale) {
		this.targetResale = targetResale;
	}
	public String getCurrency() {
		return currency;
	}
	public void setCurrency(String currency) {
		this.currency = currency;
	}



}
