//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.13 at 03:43:24 PM CST 
//


package com.avnet.emasia.webquote.dp.xml.requestquote;

import java.util.List;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="contactEmailAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="contactName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="contactPhoneNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="customerOnDockDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="customerQuote" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dateDuetoCustomer" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="dateDuetoSales" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="endCustomerAccountNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="endUserAccountNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="headerStatusCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="headerStatusDesc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="inputMethod" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="operation" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Create Quote"/>
 *               &lt;enumeration value="Closure Request"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="quoteId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="quoteProjectOrBoardName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="quoteStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="referenceID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="salesOffice" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="salesOrganization" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="shipToAccountNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="shipToAddress1stLine" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="shipToAddress2ndLine" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="shipToAddress3rdLine" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="shipToAddressCity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="shipToAddressCountry" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="shipToAddressState" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="shipToAddresszipCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="shipToAttention" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="shipToCustomerName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="soldToAddress1stLine" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="soldToAddress2ndLine" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="soldToAddress3rdLine" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="soldToAddressCity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="soldToAddressCountry" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="soldToAddressState" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="soldToAddresszipCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="soldToAttention" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="soldToCustomerAccountNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="soldToCustomerName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="source" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="webQuoteLineRequest" type="{http://remoting.qrt.avnet.com}WebQuoteLineRequest" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="customerType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="segment" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="salesPersonId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="quoteType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="rfqCreationTimestamp" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "contactEmailAddress",
    "contactName",
    "contactPhoneNo",
    "customerOnDockDate",
    "customerQuote",
    "dateDuetoCustomer",
    "dateDuetoSales",
    "endCustomerAccountNo",
    "endUserAccountNo",
    "headerStatusCode",
    "headerStatusDesc",
    "inputMethod",
    "operation",
    "quoteId",
    "quoteProjectOrBoardName",
    "quoteStatus",
    "referenceID",
    "salesOffice",
    "salesOrganization",
    "shipToAccountNo",
    "shipToAddress1StLine",
    "shipToAddress2NdLine",
    "shipToAddress3RdLine",
    "shipToAddressCity",
    "shipToAddressCountry",
    "shipToAddressState",
    "shipToAddresszipCode",
    "shipToAttention",
    "shipToCustomerName",
    "soldToAddress1StLine",
    "soldToAddress2NdLine",
    "soldToAddress3RdLine",
    "soldToAddressCity",
    "soldToAddressCountry",
    "soldToAddressState",
    "soldToAddresszipCode",
    "soldToAttention",
    "soldToCustomerAccountNo",
    "soldToCustomerName",
    "source",
    "webQuoteLineRequest",
    "customerType",
    "segment",
    "salesPersonId",
    "quoteType",
    "rfqCreationTimestamp"
})
@XmlRootElement(name = "WebRequestObject")
public class WebRequestObject {
/*
    @XmlElementRef(name = "contactEmailAddress", namespace = "http://remoting.qrt.avnet.com", type = JAXBElement.class, required = false)
    protected String contactEmailAddress;
    @XmlElementRef(name = "contactName", namespace = "http://remoting.qrt.avnet.com", type = JAXBElement.class, required = false)
    protected String contactName;
    @XmlElementRef(name = "contactPhoneNo", namespace = "http://remoting.qrt.avnet.com", type = JAXBElement.class, required = false)
    protected String contactPhoneNo;
    @XmlElementRef(name = "customerOnDockDate", namespace = "http://remoting.qrt.avnet.com", type = JAXBElement.class, required = false)
    protected XMLGregorianCalendar> customerOnDockDate;
    @XmlElementRef(name = "customerQuote", namespace = "http://remoting.qrt.avnet.com", type = JAXBElement.class, required = false)
    protected String customerQuote;
    @XmlElementRef(name = "dateDuetoCustomer", namespace = "http://remoting.qrt.avnet.com", type = JAXBElement.class, required = false)
    protected XMLGregorianCalendar> dateDuetoCustomer;
    @XmlElementRef(name = "dateDuetoSales", namespace = "http://remoting.qrt.avnet.com", type = JAXBElement.class, required = false)
    protected XMLGregorianCalendar> dateDuetoSales;
    @XmlElementRef(name = "endCustomerAccountNo", namespace = "http://remoting.qrt.avnet.com", type = JAXBElement.class, required = false)
    protected String endCustomerAccountNo;
    @XmlElementRef(name = "endUserAccountNo", namespace = "http://remoting.qrt.avnet.com", type = JAXBElement.class, required = false)
    protected String endUserAccountNo;
    @XmlElementRef(name = "headerStatusCode", namespace = "http://remoting.qrt.avnet.com", type = JAXBElement.class, required = false)
    protected String headerStatusCode;
    @XmlElementRef(name = "headerStatusDesc", namespace = "http://remoting.qrt.avnet.com", type = JAXBElement.class, required = false)
    protected String headerStatusDesc;
    @XmlElementRef(name = "inputMethod", namespace = "http://remoting.qrt.avnet.com", type = JAXBElement.class, required = false)
    protected String inputMethod;
    @XmlElementRef(name = "operation", namespace = "http://remoting.qrt.avnet.com", type = JAXBElement.class, required = false)
    protected String operation;
    @XmlElementRef(name = "quoteId", namespace = "http://remoting.qrt.avnet.com", type = JAXBElement.class, required = false)
    protected String quoteId;
    @XmlElementRef(name = "quoteProjectOrBoardName", namespace = "http://remoting.qrt.avnet.com", type = JAXBElement.class, required = false)
    protected String quoteProjectOrBoardName;
    @XmlElementRef(name = "quoteStatus", namespace = "http://remoting.qrt.avnet.com", type = JAXBElement.class, required = false)
    protected String quoteStatus;
    @XmlElementRef(name = "referenceID", namespace = "http://remoting.qrt.avnet.com", type = JAXBElement.class, required = false)
    protected String referenceID;
    @XmlElementRef(name = "salesOffice", namespace = "http://remoting.qrt.avnet.com", type = JAXBElement.class, required = false)
    protected String salesOffice;
    @XmlElementRef(name = "salesOrganization", namespace = "http://remoting.qrt.avnet.com", type = JAXBElement.class, required = false)
    protected String salesOrganization;
    @XmlElementRef(name = "shipToAccountNo", namespace = "http://remoting.qrt.avnet.com", type = JAXBElement.class, required = false)
    protected String shipToAccountNo;
    @XmlElementRef(name = "shipToAddress1stLine", namespace = "http://remoting.qrt.avnet.com", type = JAXBElement.class, required = false)
    protected String shipToAddress1StLine;
    @XmlElementRef(name = "shipToAddress2ndLine", namespace = "http://remoting.qrt.avnet.com", type = JAXBElement.class, required = false)
    protected String shipToAddress2NdLine;
    @XmlElementRef(name = "shipToAddress3rdLine", namespace = "http://remoting.qrt.avnet.com", type = JAXBElement.class, required = false)
    protected String shipToAddress3RdLine;
    @XmlElementRef(name = "shipToAddressCity", namespace = "http://remoting.qrt.avnet.com", type = JAXBElement.class, required = false)
    protected String shipToAddressCity;
    @XmlElementRef(name = "shipToAddressCountry", namespace = "http://remoting.qrt.avnet.com", type = JAXBElement.class, required = false)
    protected String shipToAddressCountry;
    @XmlElementRef(name = "shipToAddressState", namespace = "http://remoting.qrt.avnet.com", type = JAXBElement.class, required = false)
    protected String shipToAddressState;
    @XmlElementRef(name = "shipToAddresszipCode", namespace = "http://remoting.qrt.avnet.com", type = JAXBElement.class, required = false)
    protected String shipToAddresszipCode;
    @XmlElementRef(name = "shipToAttention", namespace = "http://remoting.qrt.avnet.com", type = JAXBElement.class, required = false)
    protected String shipToAttention;
    @XmlElementRef(name = "shipToCustomerName", namespace = "http://remoting.qrt.avnet.com", type = JAXBElement.class, required = false)
    protected String shipToCustomerName;
    @XmlElementRef(name = "soldToAddress1stLine", namespace = "http://remoting.qrt.avnet.com", type = JAXBElement.class, required = false)
    protected String soldToAddress1StLine;
    @XmlElementRef(name = "soldToAddress2ndLine", namespace = "http://remoting.qrt.avnet.com", type = JAXBElement.class, required = false)
    protected String soldToAddress2NdLine;
    @XmlElementRef(name = "soldToAddress3rdLine", namespace = "http://remoting.qrt.avnet.com", type = JAXBElement.class, required = false)
    protected String soldToAddress3RdLine;
    @XmlElementRef(name = "soldToAddressCity", namespace = "http://remoting.qrt.avnet.com", type = JAXBElement.class, required = false)
    protected String soldToAddressCity;
    @XmlElementRef(name = "soldToAddressCountry", namespace = "http://remoting.qrt.avnet.com", type = JAXBElement.class, required = false)
    protected String soldToAddressCountry;
    @XmlElementRef(name = "soldToAddressState", namespace = "http://remoting.qrt.avnet.com", type = JAXBElement.class, required = false)
    protected String soldToAddressState;
    @XmlElementRef(name = "soldToAddresszipCode", namespace = "http://remoting.qrt.avnet.com", type = JAXBElement.class, required = false)
    protected String soldToAddresszipCode;
    @XmlElementRef(name = "soldToAttention", namespace = "http://remoting.qrt.avnet.com", type = JAXBElement.class, required = false)
    protected String soldToAttention;
    @XmlElementRef(name = "soldToCustomerAccountNo", namespace = "http://remoting.qrt.avnet.com", type = JAXBElement.class, required = false)
    protected String soldToCustomerAccountNo;
    @XmlElementRef(name = "soldToCustomerName", namespace = "http://remoting.qrt.avnet.com", type = JAXBElement.class, required = false)
    protected String soldToCustomerName;
    @XmlElementRef(name = "source", namespace = "http://remoting.qrt.avnet.com", type = JAXBElement.class, required = false)
    protected String source;*/

	@NotNull(message="contactEmailAddress is invalid.")
	@Size(min=1, max=256, message="contactEmailAddress is invalid.")
	protected String contactEmailAddress;
	
	@NotNull(message="contactName field is invalid.")
	@Size(min=1, max=128, message="contactName is invalid.")
    protected String contactName;
	
	@NotNull(message="contactPhoneNo field is invalid.")
	@Size(min=1, max=32, message="contactPhoneNo is invalid.")
	protected String contactPhoneNo;
	
    protected XMLGregorianCalendar customerOnDockDate;
    protected String customerQuote;
    protected XMLGregorianCalendar dateDuetoCustomer;
    protected XMLGregorianCalendar dateDuetoSales;
    protected String endCustomerAccountNo;
    protected String endUserAccountNo;
    protected String headerStatusCode;
    protected String headerStatusDesc;
    protected String inputMethod;

    @NotNull(message="operation field is invalid.")
	@Size(min=1, message="operation field is invalid.")
    protected String operation;
    
    protected String quoteId;
    protected String quoteProjectOrBoardName;
    protected String quoteStatus;

    @NotNull(message="referenceId field is invalid.")
	@Size(min=1, message="referenceId field is invalid.")
    protected String referenceID;
    
	@NotNull(message="salesOffice field is invalid.")
	@Size(min=1, message="salesOffice field is invalid.")
    protected String salesOffice;
	
	@NotNull(message="salesOrganization is invalid.")
	@Size(min=1, message="salesOrganization is inalid.")
    protected String salesOrganization;
	
    protected String shipToAccountNo;
    protected String shipToAddress1StLine;
    protected String shipToAddress2NdLine;
    protected String shipToAddress3RdLine;
    protected String shipToAddressCity;
    protected String shipToAddressCountry;
    protected String shipToAddressState;
    protected String shipToAddresszipCode;
    protected String shipToAttention;
    protected String shipToCustomerName;
    protected String soldToAddress1StLine;
    protected String soldToAddress2NdLine;
    protected String soldToAddress3RdLine;
    protected String soldToAddressCity;
    protected String soldToAddressCountry;
    protected String soldToAddressState;
    protected String soldToAddresszipCode;
    protected String soldToAttention;
    
	@NotNull(message="soldToCustomerAccountNo field is invalid.")
	@Size(min=1, max=128, message="soldToCustomerAccountNo field is invalid.")
    protected String soldToCustomerAccountNo;
	
	@NotNull(message="soldToCustomername field is invalid.")
	@Size(min=1, max=256, message="soldToCustomername field is invalid.")
	protected String soldToCustomerName;
	
    protected String source;	
    
	@XmlElement(nillable = true)
	@NotNull(message="webQuoteLineRequest is invalid.")
	@Size(min=1, message="webQuoteLineRequest is invalid.")
    protected List<WebQuoteLineRequest> webQuoteLineRequest;

	@NotNull(message="customerType field is invalid.")
	@Size(min=1, message="customerType field is invalid.")
	protected String customerType;
    
	@NotNull(message="segment field is invalid.")
	@Size(min=1, message="segment field is invalid.")
	protected String segment;

    @NotNull(message="salesPersonId field is invalid.")
	@Size(min=1, message="salesPersonId field is invalid.")
    protected String salesPersonId;

	@NotNull(message="quoteType field is invalid.")
	@Size(min=1, message="quoteType field is invalid.")
	protected String quoteType;
    
	@NotNull(message="rfqCreationTimestamp field is invalid.")
	protected String rfqCreationTimestamp;
    
	public String getContactEmailAddress() {
		return contactEmailAddress;
	}
	public void setContactEmailAddress(String contactEmailAddress) {
		this.contactEmailAddress = contactEmailAddress;
	}
	public String getContactName() {
		return contactName;
	}
	public void setContactName(String contactName) {
		this.contactName = contactName;
	}
	public String getContactPhoneNo() {
		return contactPhoneNo;
	}
	public void setContactPhoneNo(String contactPhoneNo) {
		this.contactPhoneNo = contactPhoneNo;
	}
	public XMLGregorianCalendar getCustomerOnDockDate() {
		return customerOnDockDate;
	}
	public void setCustomerOnDockDate(XMLGregorianCalendar customerOnDockDate) {
		this.customerOnDockDate = customerOnDockDate;
	}
	public String getCustomerQuote() {
		return customerQuote;
	}
	public void setCustomerQuote(String customerQuote) {
		this.customerQuote = customerQuote;
	}
	public XMLGregorianCalendar getDateDuetoCustomer() {
		return dateDuetoCustomer;
	}
	public void setDateDuetoCustomer(XMLGregorianCalendar dateDuetoCustomer) {
		this.dateDuetoCustomer = dateDuetoCustomer;
	}
	public XMLGregorianCalendar getDateDuetoSales() {
		return dateDuetoSales;
	}
	public void setDateDuetoSales(XMLGregorianCalendar dateDuetoSales) {
		this.dateDuetoSales = dateDuetoSales;
	}
	public String getEndCustomerAccountNo() {
		return endCustomerAccountNo;
	}
	public void setEndCustomerAccountNo(String endCustomerAccountNo) {
		this.endCustomerAccountNo = endCustomerAccountNo;
	}
	public String getEndUserAccountNo() {
		return endUserAccountNo;
	}
	public void setEndUserAccountNo(String endUserAccountNo) {
		this.endUserAccountNo = endUserAccountNo;
	}
	public String getHeaderStatusCode() {
		return headerStatusCode;
	}
	public void setHeaderStatusCode(String headerStatusCode) {
		this.headerStatusCode = headerStatusCode;
	}
	public String getHeaderStatusDesc() {
		return headerStatusDesc;
	}
	public void setHeaderStatusDesc(String headerStatusDesc) {
		this.headerStatusDesc = headerStatusDesc;
	}
	public String getInputMethod() {
		return inputMethod;
	}
	public void setInputMethod(String inputMethod) {
		this.inputMethod = inputMethod;
	}
	public String getOperation() {
		return operation;
	}
	public void setOperation(String operation) {
		this.operation = operation;
	}
	public String getQuoteId() {
		return quoteId;
	}
	public void setQuoteId(String quoteId) {
		this.quoteId = quoteId;
	}
	public String getQuoteProjectOrBoardName() {
		return quoteProjectOrBoardName;
	}
	public void setQuoteProjectOrBoardName(String quoteProjectOrBoardName) {
		this.quoteProjectOrBoardName = quoteProjectOrBoardName;
	}
	public String getQuoteStatus() {
		return quoteStatus;
	}
	public void setQuoteStatus(String quoteStatus) {
		this.quoteStatus = quoteStatus;
	}
	public String getReferenceID() {
		return referenceID;
	}
	public void setReferenceID(String referenceID) {
		this.referenceID = referenceID;
	}
	public String getSalesOffice() {
		return salesOffice;
	}
	public void setSalesOffice(String salesOffice) {
		this.salesOffice = salesOffice;
	}
	public String getSalesOrganization() {
		return salesOrganization;
	}
	public void setSalesOrganization(String salesOrganization) {
		this.salesOrganization = salesOrganization;
	}
	public String getShipToAccountNo() {
		return shipToAccountNo;
	}
	public void setShipToAccountNo(String shipToAccountNo) {
		this.shipToAccountNo = shipToAccountNo;
	}
	public String getShipToAddress1StLine() {
		return shipToAddress1StLine;
	}
	public void setShipToAddress1StLine(String shipToAddress1StLine) {
		this.shipToAddress1StLine = shipToAddress1StLine;
	}
	public String getShipToAddress2NdLine() {
		return shipToAddress2NdLine;
	}
	public void setShipToAddress2NdLine(String shipToAddress2NdLine) {
		this.shipToAddress2NdLine = shipToAddress2NdLine;
	}
	public String getShipToAddress3RdLine() {
		return shipToAddress3RdLine;
	}
	public void setShipToAddress3RdLine(String shipToAddress3RdLine) {
		this.shipToAddress3RdLine = shipToAddress3RdLine;
	}
	public String getShipToAddressCity() {
		return shipToAddressCity;
	}
	public void setShipToAddressCity(String shipToAddressCity) {
		this.shipToAddressCity = shipToAddressCity;
	}
	public String getShipToAddressCountry() {
		return shipToAddressCountry;
	}
	public void setShipToAddressCountry(String shipToAddressCountry) {
		this.shipToAddressCountry = shipToAddressCountry;
	}
	public String getShipToAddressState() {
		return shipToAddressState;
	}
	public void setShipToAddressState(String shipToAddressState) {
		this.shipToAddressState = shipToAddressState;
	}
	public String getShipToAddresszipCode() {
		return shipToAddresszipCode;
	}
	public void setShipToAddresszipCode(String shipToAddresszipCode) {
		this.shipToAddresszipCode = shipToAddresszipCode;
	}
	public String getShipToAttention() {
		return shipToAttention;
	}
	public void setShipToAttention(String shipToAttention) {
		this.shipToAttention = shipToAttention;
	}
	public String getShipToCustomerName() {
		return shipToCustomerName;
	}
	public void setShipToCustomerName(String shipToCustomerName) {
		this.shipToCustomerName = shipToCustomerName;
	}
	public String getSoldToAddress1StLine() {
		return soldToAddress1StLine;
	}
	public void setSoldToAddress1StLine(String soldToAddress1StLine) {
		this.soldToAddress1StLine = soldToAddress1StLine;
	}
	public String getSoldToAddress2NdLine() {
		return soldToAddress2NdLine;
	}
	public void setSoldToAddress2NdLine(String soldToAddress2NdLine) {
		this.soldToAddress2NdLine = soldToAddress2NdLine;
	}
	public String getSoldToAddress3RdLine() {
		return soldToAddress3RdLine;
	}
	public void setSoldToAddress3RdLine(String soldToAddress3RdLine) {
		this.soldToAddress3RdLine = soldToAddress3RdLine;
	}
	public String getSoldToAddressCity() {
		return soldToAddressCity;
	}
	public void setSoldToAddressCity(String soldToAddressCity) {
		this.soldToAddressCity = soldToAddressCity;
	}
	public String getSoldToAddressCountry() {
		return soldToAddressCountry;
	}
	public void setSoldToAddressCountry(String soldToAddressCountry) {
		this.soldToAddressCountry = soldToAddressCountry;
	}
	public String getSoldToAddressState() {
		return soldToAddressState;
	}
	public void setSoldToAddressState(String soldToAddressState) {
		this.soldToAddressState = soldToAddressState;
	}
	public String getSoldToAddresszipCode() {
		return soldToAddresszipCode;
	}
	public void setSoldToAddresszipCode(String soldToAddresszipCode) {
		this.soldToAddresszipCode = soldToAddresszipCode;
	}
	public String getSoldToAttention() {
		return soldToAttention;
	}
	public void setSoldToAttention(String soldToAttention) {
		this.soldToAttention = soldToAttention;
	}
	public String getSoldToCustomerAccountNo() {
		return soldToCustomerAccountNo;
	}
	public void setSoldToCustomerAccountNo(String soldToCustomerAccountNo) {
		this.soldToCustomerAccountNo = soldToCustomerAccountNo;
	}
	public String getSoldToCustomerName() {
		return soldToCustomerName;
	}
	public void setSoldToCustomerName(String soldToCustomerName) {
		this.soldToCustomerName = soldToCustomerName;
	}
	public String getSource() {
		return source;
	}
	public void setSource(String source) {
		this.source = source;
	}
	public List<WebQuoteLineRequest> getWebQuoteLineRequest() {
		return webQuoteLineRequest;
	}
	
	public String getCustomerType() {
		return customerType;
	}
	public void setCustomerType(String customerType) {
		this.customerType = customerType;
	}
	public String getSegment() {
		return segment;
	}
	public void setSegment(String segment) {
		this.segment = segment;
	}
	public String getSalesPersonId() {
		return salesPersonId;
	}
	public void setSalesPersonId(String salesPersonId) {
		this.salesPersonId = salesPersonId;
	}
	public String getQuoteType() {
		return quoteType;
	}
	public void setQuoteType(String quoteType) {
		this.quoteType = quoteType;
	}
	public String getRfqCreationTimestamp() {
		return rfqCreationTimestamp;
	}
	public void setRfqCreationTimestamp(String rfqCreationTimestamp) {
		this.rfqCreationTimestamp = rfqCreationTimestamp;
	}


}
