package com.sap.document.sap.soap.functions.mc_style;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2013-04-10T20:44:47.457+08:00
 * Generated source version: 2.4.6
 * 
 */
@WebServiceClient(name = "ZWQTOSAP", 
                  wsdlLocation = "file:/D:/work/jee/WQ_EJB_Quote/CreateQuoteInSAP-Dev.wsdl",
                  targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style") 
public class ZWQTOSAP_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZWQTOSAP");
    public final static QName ZWQTOSAP = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZWQTOSAP");
    public final static QName ZWQTOSAPSOAP12 = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZWQTOSAP_SOAP12");
    static {
        URL url = null;
        try {
//            url = new URL("file:/D:/work/jee/WQ_EJB_Quote/CreateQuoteInSAP-Dev.wsdl");
            url = ZWQTOSAP_Service.class.getClassLoader().getResource("CreateQuoteInSAP-Dev.wsdl");
        } catch (Exception e) {
            java.util.logging.Logger.getLogger(ZWQTOSAP_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/work/jee/WQ_EJB_Quote/CreateQuoteInSAP-Dev.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ZWQTOSAP_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ZWQTOSAP_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZWQTOSAP_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ZWQTOSAP_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ZWQTOSAP_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ZWQTOSAP_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ZWQTOSAP
     */
    @WebEndpoint(name = "ZWQTOSAP")
    public ZWQTOSAP getZWQTOSAP() {
        return super.getPort(ZWQTOSAP, ZWQTOSAP.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZWQTOSAP
     */
    @WebEndpoint(name = "ZWQTOSAP")
    public ZWQTOSAP getZWQTOSAP(WebServiceFeature... features) {
        return super.getPort(ZWQTOSAP, ZWQTOSAP.class, features);
    }
    /**
     *
     * @return
     *     returns ZWQTOSAP
     */
    @WebEndpoint(name = "ZWQTOSAP_SOAP12")
    public ZWQTOSAP getZWQTOSAPSOAP12() {
        return super.getPort(ZWQTOSAPSOAP12, ZWQTOSAP.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZWQTOSAP
     */
    @WebEndpoint(name = "ZWQTOSAP_SOAP12")
    public ZWQTOSAP getZWQTOSAPSOAP12(WebServiceFeature... features) {
        return super.getPort(ZWQTOSAPSOAP12, ZWQTOSAP.class, features);
    }

}
