alter table WEBQUOTE.ATTACHMENT add (state NUMBER(1,0) DEFAULT 1);

alter table WEBQUOTE.ATTACHMENT add (FILE_NAME_ACTUAL varchar2(1000));

alter table WEBQUOTE.ATTACHMENT add (FILE_PATH varchar2(500));

--run attachment convert program;

alter table WEBQUOTE.ATTACHMENT rename to ATTACHMENT_BAK;

CREATE TABLE "WEBQUOTE"."ATTACHMENT" 
   (	"ID" NUMBER(18,0) NOT NULL ENABLE, 
	"QUOTE_ITEM_ID" NUMBER(18,0), 
	"FILE_NAME" VARCHAR2(255 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"QUOTE_ID" NUMBER(18,0), 
	"STATE" NUMBER(1,0) DEFAULT 1, 
	"FILE_NAME_ACTUAL" VARCHAR2(1000 BYTE), 
	"FILE_PATH" VARCHAR2(500 BYTE), 
	 CONSTRAINT "ATTACHMENT_NEW_PK" PRIMARY KEY ("ID"), 
	 CONSTRAINT "ATTACHMENT_QUOTE_NEW_FK1" FOREIGN KEY ("QUOTE_ID")
	  REFERENCES "WEBQUOTE"."QUOTE" ("ID") ENABLE, 
	 CONSTRAINT "ATTACHMENT_QUOTE_ITEM_NEW_FK1" FOREIGN KEY ("QUOTE_ITEM_ID")
	  REFERENCES "WEBQUOTE"."QUOTE_ITEM" ("ID") ENABLE
   ) ;
  
  

  CREATE INDEX "WEBQUOTE"."ATTACHMENT_NEW_IDX1" ON "WEBQUOTE"."ATTACHMENT" ("QUOTE_ID", "TYPE")  ;

  CREATE INDEX "WEBQUOTE"."ATTACHMENT_NEW_IDX2" ON "WEBQUOTE"."ATTACHMENT" ("QUOTE_ITEM_ID", "TYPE") ;

 drop TRIGGER WEBQUOTE.UPDATE_ATTACHMENT_AVAILABLE  ;



insert into ATTACHMENT(ID,QUOTE_ITEM_ID,FILE_NAME,TYPE,QUOTE_ID,STATE,FILE_NAME_ACTUAL,FILE_PATH)
select ID,QUOTE_ITEM_ID,FILE_NAME,TYPE,QUOTE_ID,STATE,FILE_NAME_ACTUAL,FILE_PATH from ATTACHMENT_BAK;

INSERT INTO APP_PROPERTY (PROP_KEY,PROP_DESC,PROP_VALUE,PROP_RESERVED) values ('ATTACHMENT_ROOT_PATH',null,'/app/eap62/webquote/attachments','1');

commit;



