package com.avnet.emasia.webquote.entity;

// Generated 2014-6-23 14:41:12 by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FiscalMappingId generated by hbm2java
 */
@Embeddable
public class FiscalMappingId implements java.io.Serializable
{

	private Integer fisYearFrom;
	private String mth;
	private Integer fisMonthFrom;
	private Integer fisDayFrom;
	private Integer fisMonthTo;
	private Integer fisDayTo;
	private String fy;
	private String qtr;
	private Integer fisYearTo;

	public FiscalMappingId()
	{
	}

	public FiscalMappingId(Integer fisYearFrom, String mth,
			Integer fisMonthFrom, Integer fisDayFrom,
			Integer fisMonthTo, Integer fisDayTo, String fy, String qtr,
			Integer fisYearTo)
	{
		this.fisYearFrom = fisYearFrom;
		this.mth = mth;
		this.fisMonthFrom = fisMonthFrom;
		this.fisDayFrom = fisDayFrom;
		this.fisMonthTo = fisMonthTo;
		this.fisDayTo = fisDayTo;
		this.fy = fy;
		this.qtr = qtr;
		this.fisYearTo = fisYearTo;
	}

	@Column(name = "FIS_YEAR_FROM", nullable = false, precision = 22, scale = 0)
	public Integer getFisYearFrom()
	{
		return this.fisYearFrom;
	}

	public void setFisYearFrom(Integer fisYearFrom)
	{
		this.fisYearFrom = fisYearFrom;
	}

	@Column(name = "MTH", nullable = false, length = 6)
	public String getMth()
	{
		return this.mth;
	}

	public void setMth(String mth)
	{
		this.mth = mth;
	}

	@Column(name = "FIS_MONTH_FROM", nullable = false, precision = 22, scale = 0)
	public Integer getFisMonthFrom()
	{
		return this.fisMonthFrom;
	}

	public void setFisMonthFrom(Integer fisMonthFrom)
	{
		this.fisMonthFrom = fisMonthFrom;
	}

	@Column(name = "FIS_DAY_FROM", nullable = false, precision = 22, scale = 0)
	public Integer getFisDayFrom()
	{
		return this.fisDayFrom;
	}

	public void setFisDayFrom(Integer fisDayFrom)
	{
		this.fisDayFrom = fisDayFrom;
	}

	@Column(name = "FIS_MONTH_TO", nullable = false, precision = 22, scale = 0)
	public Integer getFisMonthTo()
	{
		return this.fisMonthTo;
	}

	public void setFisMonthTo(Integer fisMonthTo)
	{
		this.fisMonthTo = fisMonthTo;
	}

	@Column(name = "FIS_DAY_TO", nullable = false, precision = 22, scale = 0)
	public Integer getFisDayTo()
	{
		return this.fisDayTo;
	}

	public void setFisDayTo(Integer fisDayTo)
	{
		this.fisDayTo = fisDayTo;
	}

	@Column(name = "FY", nullable = false, length = 4)
	public String getFy()
	{
		return this.fy;
	}

	public void setFy(String fy)
	{
		this.fy = fy;
	}

	@Column(name = "QTR", nullable = false, length = 2)
	public String getQtr()
	{
		return this.qtr;
	}

	public void setQtr(String qtr)
	{
		this.qtr = qtr;
	}

	@Column(name = "FIS_YEAR_TO", nullable = false, precision = 22, scale = 0)
	public Integer getFisYearTo()
	{
		return this.fisYearTo;
	}

	public void setFisYearTo(Integer fisYearTo)
	{
		this.fisYearTo = fisYearTo;
	}

	public boolean equals(Object other)
	{
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FiscalMappingId))
			return false;
		FiscalMappingId castOther = (FiscalMappingId) other;

		return ((this.getFisYearFrom() == castOther.getFisYearFrom()) || (this
				.getFisYearFrom() != null && castOther.getFisYearFrom() != null && this
				.getFisYearFrom().equals(castOther.getFisYearFrom())))
				&& ((this.getMth() == castOther.getMth()) || (this.getMth() != null
						&& castOther.getMth() != null && this.getMth().equals(
						castOther.getMth())))
				&& ((this.getFisMonthFrom() == castOther.getFisMonthFrom()) || (this
						.getFisMonthFrom() != null
						&& castOther.getFisMonthFrom() != null && this
						.getFisMonthFrom().equals(castOther.getFisMonthFrom())))
				&& ((this.getFisDayFrom() == castOther.getFisDayFrom()) || (this
						.getFisDayFrom() != null
						&& castOther.getFisDayFrom() != null && this
						.getFisDayFrom().equals(castOther.getFisDayFrom())))
				&& ((this.getFisMonthTo() == castOther.getFisMonthTo()) || (this
						.getFisMonthTo() != null
						&& castOther.getFisMonthTo() != null && this
						.getFisMonthTo().equals(castOther.getFisMonthTo())))
				&& ((this.getFisDayTo() == castOther.getFisDayTo()) || (this
						.getFisDayTo() != null
						&& castOther.getFisDayTo() != null && this
						.getFisDayTo().equals(castOther.getFisDayTo())))
				&& ((this.getFy() == castOther.getFy()) || (this.getFy() != null
						&& castOther.getFy() != null && this.getFy().equals(
						castOther.getFy())))
				&& ((this.getQtr() == castOther.getQtr()) || (this.getQtr() != null
						&& castOther.getQtr() != null && this.getQtr().equals(
						castOther.getQtr())))
				&& ((this.getFisYearTo() == castOther.getFisYearTo()) || (this
						.getFisYearTo() != null
						&& castOther.getFisYearTo() != null && this
						.getFisYearTo().equals(castOther.getFisYearTo())));
	}

	public int hashCode()
	{
		int result = 17;

		result = 37
				* result
				+ (getFisYearFrom() == null ? 0 : this.getFisYearFrom()
						.hashCode());
		result = 37 * result
				+ (getMth() == null ? 0 : this.getMth().hashCode());
		result = 37
				* result
				+ (getFisMonthFrom() == null ? 0 : this.getFisMonthFrom()
						.hashCode());
		result = 37
				* result
				+ (getFisDayFrom() == null ? 0 : this.getFisDayFrom()
						.hashCode());
		result = 37
				* result
				+ (getFisMonthTo() == null ? 0 : this.getFisMonthTo()
						.hashCode());
		result = 37 * result
				+ (getFisDayTo() == null ? 0 : this.getFisDayTo().hashCode());
		result = 37 * result + (getFy() == null ? 0 : this.getFy().hashCode());
		result = 37 * result
				+ (getQtr() == null ? 0 : this.getQtr().hashCode());
		result = 37 * result
				+ (getFisYearTo() == null ? 0 : this.getFisYearTo().hashCode());
		return result;
	}

}
