
package com.sap.document.sap.soap.functions.mc_style;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.4.6
 * 2013-04-11T12:38:29.121+08:00
 * Generated source version: 2.4.6
 */

@WebFault(name = "ZsdWqCrCustomer.Exception", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style")
public class ZsdWqCrCustomerException extends Exception {
    
    private com.sap.document.sap.soap.functions.mc_style.ZsdWqCrCustomerRfcException zsdWqCrCustomerException;

    public ZsdWqCrCustomerException() {
        super();
    }
    
    public ZsdWqCrCustomerException(String message) {
        super(message);
    }
    
    public ZsdWqCrCustomerException(String message, Throwable cause) {
        super(message, cause);
    }

    public ZsdWqCrCustomerException(String message, com.sap.document.sap.soap.functions.mc_style.ZsdWqCrCustomerRfcException zsdWqCrCustomerException) {
        super(message);
        this.zsdWqCrCustomerException = zsdWqCrCustomerException;
    }

    public ZsdWqCrCustomerException(String message, com.sap.document.sap.soap.functions.mc_style.ZsdWqCrCustomerRfcException zsdWqCrCustomerException, Throwable cause) {
        super(message, cause);
        this.zsdWqCrCustomerException = zsdWqCrCustomerException;
    }

    public com.sap.document.sap.soap.functions.mc_style.ZsdWqCrCustomerRfcException getFaultInfo() {
        return this.zsdWqCrCustomerException;
    }
}
