package com.sap.document.sap.soap.functions.mc_style;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2013-04-11T12:38:29.497+08:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", name = "ZWQCUST")
@XmlSeeAlso({ObjectFactory.class})
public interface ZWQCUST {

    @RequestWrapper(localName = "ZsdWqCrCustomer", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZsdWqCrCustomer")
    @WebMethod(operationName = "ZsdWqCrCustomer")
    @ResponseWrapper(localName = "ZsdWqCrCustomerResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZsdWqCrCustomerResponse")
    public void zsdWqCrCustomer(
        @WebParam(name = "ICity", targetNamespace = "")
        java.lang.String iCity,
        @WebParam(name = "IDuplicateFlg", targetNamespace = "")
        java.lang.String iDuplicateFlg,
        @WebParam(name = "ILand", targetNamespace = "")
        java.lang.String iLand,
        @WebParam(name = "IName", targetNamespace = "")
        java.lang.String iName,
        @WebParam(name = "IName2", targetNamespace = "")
        java.lang.String iName2,
        @WebParam(name = "IPstlz", targetNamespace = "")
        java.lang.String iPstlz,
        @WebParam(name = "IRegio", targetNamespace = "")
        java.lang.String iRegio,
        @WebParam(name = "ISortl", targetNamespace = "")
        java.lang.String iSortl,
        @WebParam(name = "ISpart", targetNamespace = "")
        java.lang.String iSpart,
        @WebParam(name = "IStreet", targetNamespace = "")
        java.lang.String iStreet,
        @WebParam(name = "IVkbur", targetNamespace = "")
        java.lang.String iVkbur,
        @WebParam(name = "IVkorg", targetNamespace = "")
        java.lang.String iVkorg,
        @WebParam(name = "IVtweg", targetNamespace = "")
        java.lang.String iVtweg,
        @WebParam(name = "IWaers", targetNamespace = "")
        java.lang.String iWaers,
        @WebParam(name = "IAccgrp", targetNamespace = "")
        java.lang.String iAccgrp,
        @WebParam(mode = WebParam.Mode.OUT, name = "ECustdtl", targetNamespace = "")
        javax.xml.ws.Holder<ZwqCustomer> eCustdtl,
        @WebParam(mode = WebParam.Mode.OUT, name = "EKunnr", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> eKunnr
    ) throws ZsdWqCrCustomerException;
}
