
DB scheme change: 

//clear the data
Delete from COST_INDICATOR_RULE;

//added to columns
alter table COST_INDICATOR_RULE add (PRICE_LIST_REMARKS NUMBER(1,0));
alter table COST_INDICATOR_RULE add (PART_DESCRIPTION NUMBER(1,0));

// insert the data
Insert into COST_INDICATOR_RULE (COST_INDICATOR,MPQ,MOQ,MOV,LEAD_TIME,MPQ_VALUE,MOQ_VALUE,MOV_VALUE,PRICE_VALIDITY,SHIPMENT_VALIDITY,PRICE_LIST_REMARKS,PART_DESCRIPTION) values ('A-Book Cost',3,3,3,3,'MPQ','MOQ','MOV',3,3,3,3);
Insert into COST_INDICATOR_RULE (COST_INDICATOR,MPQ,MOQ,MOV,LEAD_TIME,MPQ_VALUE,MOQ_VALUE,MOV_VALUE,PRICE_VALIDITY,SHIPMENT_VALIDITY,PRICE_LIST_REMARKS,PART_DESCRIPTION) values ('A-Commodity Cost',3,3,3,3,'MPQ','MOQ','MOV',3,3,1,1);
Insert into COST_INDICATOR_RULE (COST_INDICATOR,MPQ,MOQ,MOV,LEAD_TIME,MPQ_VALUE,MOQ_VALUE,MOV_VALUE,PRICE_VALIDITY,SHIPMENT_VALIDITY,PRICE_LIST_REMARKS,PART_DESCRIPTION) values ('Z-N/A at Quote Stage',1,1,1,1,'MPQ','MOQ','MOV',3,3,1,1);
Insert into COST_INDICATOR_RULE (COST_INDICATOR,MPQ,MOQ,MOV,LEAD_TIME,MPQ_VALUE,MOQ_VALUE,MOV_VALUE,PRICE_VALIDITY,SHIPMENT_VALIDITY,PRICE_LIST_REMARKS,PART_DESCRIPTION) values ('A-MPP Cost',3,3,3,3,'MPQ','MOQ','MOV',3,3,1,1);
Insert into COST_INDICATOR_RULE (COST_INDICATOR,MPQ,MOQ,MOV,LEAD_TIME,MPQ_VALUE,MOQ_VALUE,MOV_VALUE,PRICE_VALIDITY,SHIPMENT_VALIDITY,PRICE_LIST_REMARKS,PART_DESCRIPTION) values ('A-Special Cost',1,3,1,1,'MPQ','MOQ','MOV',3,3,1,1);
Insert into COST_INDICATOR_RULE (COST_INDICATOR,MPQ,MOQ,MOV,LEAD_TIME,MPQ_VALUE,MOQ_VALUE,MOV_VALUE,PRICE_VALIDITY,SHIPMENT_VALIDITY,PRICE_LIST_REMARKS,PART_DESCRIPTION) values ('A-Contract Cost',1,1,1,1,'MPQ','MOQ','MOV',3,3,1,1);
Insert into COST_INDICATOR_RULE (COST_INDICATOR,MPQ,MOQ,MOV,LEAD_TIME,MPQ_VALUE,MOQ_VALUE,MOV_VALUE,PRICE_VALIDITY,SHIPMENT_VALIDITY,PRICE_LIST_REMARKS,PART_DESCRIPTION) values ('A-Inventory Cost',1,1,3,3,'MPQ','MPQ','MOV',3,3,1,1);
Insert into COST_INDICATOR_RULE (COST_INDICATOR,MPQ,MOQ,MOV,LEAD_TIME,MPQ_VALUE,MOQ_VALUE,MOV_VALUE,PRICE_VALIDITY,SHIPMENT_VALIDITY,PRICE_LIST_REMARKS,PART_DESCRIPTION) values ('A-XX00 Plant Inventory',1,1,3,3,'MPQ','MPQ','MOV',3,3,1,1);
Insert into COST_INDICATOR_RULE (COST_INDICATOR,MPQ,MOQ,MOV,LEAD_TIME,MPQ_VALUE,MOQ_VALUE,MOV_VALUE,PRICE_VALIDITY,SHIPMENT_VALIDITY,PRICE_LIST_REMARKS,PART_DESCRIPTION) values ('A-Rebate Cost',1,1,1,1,'MPQ','MOQ','MOV',3,3,1,1);
Insert into COST_INDICATOR_RULE (COST_INDICATOR,MPQ,MOQ,MOV,LEAD_TIME,MPQ_VALUE,MOQ_VALUE,MOV_VALUE,PRICE_VALIDITY,SHIPMENT_VALIDITY,PRICE_LIST_REMARKS,PART_DESCRIPTION) values ('B-S'||chr(38)||'D/DPA',1,1,1,1,'MPQ','MOQ','MOV',3,3,1,1);
Insert into COST_INDICATOR_RULE (COST_INDICATOR,MPQ,MOQ,MOV,LEAD_TIME,MPQ_VALUE,MOQ_VALUE,MOV_VALUE,PRICE_VALIDITY,SHIPMENT_VALIDITY,PRICE_LIST_REMARKS,PART_DESCRIPTION) values ('B-Contract DPA Cost',1,1,1,1,'MPQ','MOQ','MOV',3,3,1,1);
Insert into COST_INDICATOR_RULE (COST_INDICATOR,MPQ,MOQ,MOV,LEAD_TIME,MPQ_VALUE,MOQ_VALUE,MOV_VALUE,PRICE_VALIDITY,SHIPMENT_VALIDITY,PRICE_LIST_REMARKS,PART_DESCRIPTION) values ('C-QAS Cost',1,1,1,3,'MPQ','MOQ','MOV',3,3,1,1);
Insert into COST_INDICATOR_RULE (COST_INDICATOR,MPQ,MOQ,MOV,LEAD_TIME,MPQ_VALUE,MOQ_VALUE,MOV_VALUE,PRICE_VALIDITY,SHIPMENT_VALIDITY,PRICE_LIST_REMARKS,PART_DESCRIPTION) values ('C-ICST Cost - EMA',1,1,1,3,'MPQ','MOQ','MOV',3,3,1,1);
Insert into COST_INDICATOR_RULE (COST_INDICATOR,MPQ,MOQ,MOV,LEAD_TIME,MPQ_VALUE,MOQ_VALUE,MOV_VALUE,PRICE_VALIDITY,SHIPMENT_VALIDITY,PRICE_LIST_REMARKS,PART_DESCRIPTION) values ('C-ICST Cost - EMEA',1,1,1,3,'MPQ','MOQ','MOV',3,3,1,1);
Insert into COST_INDICATOR_RULE (COST_INDICATOR,MPQ,MOQ,MOV,LEAD_TIME,MPQ_VALUE,MOQ_VALUE,MOV_VALUE,PRICE_VALIDITY,SHIPMENT_VALIDITY,PRICE_LIST_REMARKS,PART_DESCRIPTION) values ('C-ICST Cost - TW',1,1,1,3,'MPQ','MOQ','MOV',3,3,1,1);
Insert into COST_INDICATOR_RULE (COST_INDICATOR,MPQ,MOQ,MOV,LEAD_TIME,MPQ_VALUE,MOQ_VALUE,MOV_VALUE,PRICE_VALIDITY,SHIPMENT_VALIDITY,PRICE_LIST_REMARKS,PART_DESCRIPTION) values ('C-ICST Cost - SOUTH',1,1,1,3,'MPQ','MOQ','MOV',3,3,1,1);
Insert into COST_INDICATOR_RULE (COST_INDICATOR,MPQ,MOQ,MOV,LEAD_TIME,MPQ_VALUE,MOQ_VALUE,MOV_VALUE,PRICE_VALIDITY,SHIPMENT_VALIDITY,PRICE_LIST_REMARKS,PART_DESCRIPTION) values ('C-ICST Cost - YEL',1,1,1,3,'MPQ','MOQ','MOV',3,3,1,1);
Insert into COST_INDICATOR_RULE (COST_INDICATOR,MPQ,MOQ,MOV,LEAD_TIME,MPQ_VALUE,MOQ_VALUE,MOV_VALUE,PRICE_VALIDITY,SHIPMENT_VALIDITY,PRICE_LIST_REMARKS,PART_DESCRIPTION) values ('C-ICST Cost - AEMC',1,1,1,3,'MPQ','MOQ','MOV',3,3,1,1);
Insert into COST_INDICATOR_RULE (COST_INDICATOR,MPQ,MOQ,MOV,LEAD_TIME,MPQ_VALUE,MOQ_VALUE,MOV_VALUE,PRICE_VALIDITY,SHIPMENT_VALIDITY,PRICE_LIST_REMARKS,PART_DESCRIPTION) values ('C-ICST Cost - AMC',1,1,1,3,'MPQ','MOQ','MOV',3,3,1,1);
Insert into COST_INDICATOR_RULE (COST_INDICATOR,MPQ,MOQ,MOV,LEAD_TIME,MPQ_VALUE,MOQ_VALUE,MOV_VALUE,PRICE_VALIDITY,SHIPMENT_VALIDITY,PRICE_LIST_REMARKS,PART_DESCRIPTION) values ('D-Programming Part',1,1,1,3,'MPQ','MOQ','MOV',3,3,1,1);
Insert into COST_INDICATOR_RULE (COST_INDICATOR,MPQ,MOQ,MOV,LEAD_TIME,MPQ_VALUE,MOQ_VALUE,MOV_VALUE,PRICE_VALIDITY,SHIPMENT_VALIDITY,PRICE_LIST_REMARKS,PART_DESCRIPTION) values ('E-Prelim Quote Cost',3,3,3,3,'MPQ','MOQ','MOV',3,3,null,null);

