alter table WEBQUOTE.CUSTOMER_ADDRESS  rename column "ADDRESS_NAME3" to "CUSTOMER_NAME3";
alter table WEBQUOTE.CUSTOMER_ADDRESS  rename column "ADDRESS_NAME4" to "CUSTOMER_NAME4";
alter table WEBQUOTE.CUSTOMER_ADDRESS  add STREET2 VARCHAR2(80 CHAR);
alter table WEBQUOTE.CUSTOMER_ADDRESS  add STREET3 VARCHAR2(80 CHAR);