--create table 
create table LOGIC_CAL_CONFIG (
  ID NUMBER(5,0) primary key,
  LOGIC_RESULT_REVERSE CHAR(1 BYTE) default 0,
  CONFIG_TYPE VARCHAR2(20) NOT NULL,
  LOGIC_ACTION VARCHAR2(20) NOT NULL,
   CONDITION_TYPE VARCHAR2(20)  NULL,
  CONDITION_VALUE VARCHAR2(200)  NULL,
  PARENT_ID NUMBER(5,0) NULL ,
  FOREIGN KEY (PARENT_ID) REFERENCES LOGIC_CAL_CONFIG(ID)
);

create table  PAGE_COMPONENT_ITEM (
  ID NUMBER(5,0) primary key,
  SHOW CHAR(1 BYTE) default 0,
  PAGE_NAME VARCHAR2(60) NOT NULL,
  COMPONENT_ID VARCHAR2(50) NOT NULL,
  PRIORITY NUMBER(5,0) DEFAULT 10000 NOT NULL ,
  LOGIC_CAL_CONFIG_ID NUMBER(5,0) NOT NULL ,
  FOREIGN KEY (LOGIC_CAL_CONFIG_ID) REFERENCES LOGIC_CAL_CONFIG(ID)
);

COMMENT ON COLUMN LOGIC_CAL_CONFIG.CONFIG_TYPE IS 'now support [CONNECTOR,CONDITION]';
COMMENT ON COLUMN LOGIC_CAL_CONFIG.LOGIC_ACTION IS 'now support [OR,AND] FOR [CONNECTOR],[ANYMATCH,ALLMATCH,NONEMATCH] FOR [CONDITION]';
COMMENT ON COLUMN LOGIC_CAL_CONFIG.CONDITION_TYPE IS 'for [CONDITION]. now support [ROLE,REGION]';
COMMENT ON COLUMN LOGIC_CAL_CONFIG.CONDITION_VALUE IS 'Can put multi value use [,] spilt them';