ALTER TABLE PRICER_DELETED DROP  (SUPPLIER_NUMBER, NCNR_FLAG, NCNR_VALID_FROM, COMMODITY_CODE, GREEN_PRODUCT_INDICATOR, PLANT_ID, LAST_BUY_DATE, LAST_SHIP_DATE, SHIP_DEBIT, ECCN, ALLOCATION_VALID_FROM, PRE_VALID_TO_DATE);
ALTER TABLE PRICER DROP (SUPPLIER_NUMBER, NCNR_FLAG, NCNR_VALID_FROM, COMMODITY_CODE, GREEN_PRODUCT_INDICATOR, PLANT_ID, LAST_BUY_DATE, LAST_SHIP_DATE, SHIP_DEBIT, ECCN, ALLOCATION_VALID_FROM, PRE_VALID_TO_DATE);



