
  CREATE TABLE "MFR_REQUEST_INFO" 
   (	"STATUS" VARCHAR2(30 BYTE) NOT NULL, 
	"BPM_CODE" VARCHAR2(35 BYTE), 
	"EC_BPM_CODE" VARCHAR2(35 BYTE), 
	"VENDOR_SHIP_TO" VARCHAR2(35 BYTE), 
	"BQ_NUMBER" VARCHAR2(35 BYTE), 
	"PROJECT_REGISTRATION_NUMBER" VARCHAR2(35 BYTE), 
	"ID" NUMBER NOT NULL ENABLE, 
	"BPM_NAME" VARCHAR2(35 BYTE), 
	"BPM_CNT_CODE" VARCHAR2(3 BYTE), 
	"EC_BPM_NAME" VARCHAR2(35 BYTE), 
	"ECBPM_CNT_CODE" VARCHAR2(3 BYTE), 
	"SENT_OUT_TIME" DATE, 
	"CREATE_TIME" DATE, 
	"REQ_QTY" NUMBER(20,0), 
	"CONTACT_NAME" VARCHAR2(17 BYTE), 
	"CONTACT_CHANNEL" VARCHAR2(512 BYTE), 
	"HEAD_REMARK" VARCHAR2(140 BYTE), 
	"TGT_RESALE" NUMBER(20,5), 
	"TGT_COST" NUMBER(20,5), 
	"QUOTE_ITEM_ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "MFR_REQUEST_INFO_PK" PRIMARY KEY ("ID")
   )


  CREATE TABLE "MFR_FEEDBACK_INFO" 
   (	"MFR" VARCHAR2(3 BYTE), 
	"ID" NUMBER NOT NULL ENABLE, 
	"SQ_NUMBER" VARCHAR2(35 BYTE), 
	"DEBIT_NUMBER" VARCHAR2(35 BYTE), 
	"QUOTE_TYPE" VARCHAR2(5 BYTE), 
	"STATUS" VARCHAR2(30 BYTE), 
	"PART_NUMBER" VARCHAR2(35 BYTE), 
	"AVNET_QUOTE_NUMBER" VARCHAR2(9 BYTE), 
	"BUYER" VARCHAR2(35 BYTE), 
	"SHIP_TO" VARCHAR2(35 BYTE), 
	"CONTACT_NAME" VARCHAR2(35 BYTE), 
	"CONTACT_EMAIL" VARCHAR2(512 BYTE), 
	"CUSTOMER" VARCHAR2(35 BYTE), 
	"END_CUSTOMER" VARCHAR2(35 BYTE), 
	"CURRENCY" VARCHAR2(3 BYTE), 
	"AUTH_QTY" NUMBER(15,0), 
	"SUGGESTED_RESALE" NUMBER(20,5), 
	"COST" NUMBER(20,5), 
	"VENDOR_REMARKS" VARCHAR2(350 BYTE), 
	"DEBIT_CREATE_DATE" DATE, 
	"DEBIT_EXPIRY_DATE" DATE, 
	"BIZ_UNIT" VARCHAR2(5 BYTE), 
	 CONSTRAINT "MFR_FEEDBACK_INFO_PK" PRIMARY KEY ("ID")
   );
   
  CREATE TABLE "SHIP_TO_CODE_MAPPING" 
   (	"TYPE" VARCHAR2(5 BYTE) NOT NULL ENABLE, 
	"SHIP_TO_CODE" VARCHAR2(35 BYTE), 
	"TEAM_ID" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "SHIP_TO_CODE_MAPPING_PK" PRIMARY KEY ("ID")

   );
   
 CREATE TABLE "SUBREGION_TEAM_MAPPING" 
   (	"VENDOR" VARCHAR2(3 BYTE) NOT NULL ENABLE, 
	"SUB_REGION" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"TEAM_ID" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"ID" NUMBER NOT NULL ENABLE, 
	"BIZ_UNIT" VARCHAR2(5 BYTE), 
	 CONSTRAINT "SUBREGION_TEAM_MAPPING_PK" PRIMARY KEY ("ID")
   );
   

  CREATE TABLE "SUBREGION_RECIPIENT_MAPPING" 
   (	"SUPPLIER" VARCHAR2(3 BYTE) NOT NULL ENABLE, 
	"SUB_REGION" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"RECIPIENT" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"ID" NUMBER NOT NULL ENABLE, 
	"BIZ_UNIT" VARCHAR2(5 BYTE), 
	 CONSTRAINT "SUBREGION_RECIPIENT_MAPPING_PK" PRIMARY KEY ("ID")
   );
   
  CREATE TABLE "VENDOR_BPM_CUSTOMER" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"DISTRIBUTOR_CODE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"DISTRIBUTOR_NAME" VARCHAR2(100 BYTE), 
	"BPM_CODE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"SHORTNAME" VARCHAR2(35 BYTE), 
	"BPM_NAME1" VARCHAR2(100 BYTE), 
	"BPM_NAME2" VARCHAR2(100 BYTE), 
	"CTRY" VARCHAR2(20 BYTE), 
	 CONSTRAINT "VERDOR_BPM_CUSTOMER_PK" PRIMARY KEY ("ID")
   );

     CREATE TABLE "DCODE_REGION_MAPPING" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"DISTRIBUTOR_CODE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"BIZ_UNIT" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "DCODE_REGION_MAPPING_PK" PRIMARY KEY ("ID")
   );
