package com.avnet.emasia.webquote.entity;

// Generated 2014-6-23 14:41:12 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * FiscalMapping generated by hbm2java
 */
@Entity
@Table(name = "FISCAL_MAPPING")
public class FiscalMapping implements java.io.Serializable
{

	private FiscalMappingId id;

	public FiscalMapping()
	{
	}

	public FiscalMapping(FiscalMappingId id)
	{
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "fisYearFrom", column = @Column(name = "FIS_YEAR_FROM", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "mth", column = @Column(name = "MTH", nullable = false, length = 6)),
			@AttributeOverride(name = "fisMonthFrom", column = @Column(name = "FIS_MONTH_FROM", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "fisDayFrom", column = @Column(name = "FIS_DAY_FROM", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "fisMonthTo", column = @Column(name = "FIS_MONTH_TO", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "fisDayTo", column = @Column(name = "FIS_DAY_TO", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "fy", column = @Column(name = "FY", nullable = false, length = 4)),
			@AttributeOverride(name = "qtr", column = @Column(name = "QTR", nullable = false, length = 2)),
			@AttributeOverride(name = "fisYearTo", column = @Column(name = "FIS_YEAR_TO", nullable = false, precision = 22, scale = 0)) })
	public FiscalMappingId getId()
	{
		return this.id;
	}

	public void setId(FiscalMappingId id)
	{
		this.id = id;
	}

}
