//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.13 at 03:43:52 PM CST 
//


package com.avnet.emasia.webquote.dp.xml.responsequote;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.avnet.emasia.webquote.dp.xml.responsequote package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName RESPONSE_QUOTE_QNAME = new QName("http://www.avnet.com/schema", "ResponseQuote");
    private final static QName RESPONSE_QUOTE_ACKNOWLEDGEMENT_QNAME = new QName("http://www.avnet.com/schema", "ResponseQuoteAcknowledgement");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.avnet.emasia.webquote.dp.xml.responsequote
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ResponseQuoteAcknowledgementType }
     * 
     */
    public ResponseQuoteAcknowledgementType createResponseQuoteAcknowledgementType() {
        return new ResponseQuoteAcknowledgementType();
    }

    /**
     * Create an instance of {@link ResponseQuoteType }
     * 
     */
    public ResponseQuoteType createResponseQuoteType() {
        return new ResponseQuoteType();
    }

    /**
     * Create an instance of {@link AvnQuoteIdentifierType }
     * 
     */
    public AvnQuoteIdentifierType createAvnQuoteIdentifierType() {
        return new AvnQuoteIdentifierType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResponseQuoteType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.avnet.com/schema", name = "ResponseQuote")
    public JAXBElement<ResponseQuoteType> createResponseQuote(ResponseQuoteType value) {
        return new JAXBElement<ResponseQuoteType>(RESPONSE_QUOTE_QNAME, ResponseQuoteType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResponseQuoteAcknowledgementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.avnet.com/schema", name = "ResponseQuoteAcknowledgement")
    public JAXBElement<ResponseQuoteAcknowledgementType> createResponseQuoteAcknowledgement(ResponseQuoteAcknowledgementType value) {
        return new JAXBElement<ResponseQuoteAcknowledgementType>(RESPONSE_QUOTE_ACKNOWLEDGEMENT_QNAME, ResponseQuoteAcknowledgementType.class, null, value);
    }

}
