
  CREATE TABLE "WEBQUOTE"."EXCEL_REPORT" 
   (	"ID" NUMBER(18,0) NOT NULL ENABLE, 
	"TEMPLATE_NAME" VARCHAR2(50 BYTE), 
	"REPORT_NAME" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"SHEET_NO" NUMBER(5,0), 
	 CONSTRAINT "EXCEL_REPORT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "WEBQUOTE_01"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "WEBQUOTE_01" ;

  CREATE UNIQUE INDEX "WEBQUOTE"."EXCEL_REPORT_INDEX1" ON "WEBQUOTE"."EXCEL_REPORT" ("REPORT_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "WEBQUOTE_01" ;

  
  CREATE TABLE "WEBQUOTE"."EXCEL_REPORT_COLUMN" 
   (	"ID" NUMBER(18,0) NOT NULL ENABLE, 
	"HEADER_NAME" VARCHAR2(50 BYTE), 
	"BEAN_PROPERTY" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"CELL_DATA_TYPE" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "EXCEL_REPORT_COLUMN_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "WEBQUOTE_01"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "WEBQUOTE_01" ;

  
  
  CREATE TABLE "WEBQUOTE"."EXCEL_REPORT_SEQ" 
   (	"ID" NUMBER(18,0) NOT NULL ENABLE, 
	"REPORT_ID" NUMBER(18,0) NOT NULL ENABLE, 
	"COLUMN_ID" NUMBER(18,0) NOT NULL ENABLE, 
	"SEQ_NO" NUMBER(5,0) NOT NULL ENABLE, 
	 CONSTRAINT "EXCEL_REPORT_SEQ_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "WEBQUOTE_01"  ENABLE, 
	 CONSTRAINT "EXCEL_REPORT_SEQ_FK1" FOREIGN KEY ("COLUMN_ID")
	  REFERENCES "WEBQUOTE"."EXCEL_REPORT_COLUMN" ("ID") ENABLE, 
	 CONSTRAINT "EXCEL_REPORT_SEQ_FK2" FOREIGN KEY ("REPORT_ID")
	  REFERENCES "WEBQUOTE"."EXCEL_REPORT" ("ID") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "WEBQUOTE_01" ;
