--[5.16.2 SAP Interface to WQ]

-->5.16.2: New Table for SAP Interface batches

  CREATE TABLE "WEBQUOTE"."SAP_INTERFACE_BATCHES" 
   (	"ID" NUMBER(38,0) NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"CREATED_ON" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE, 
	"PROCESS_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"START_TIME" TIMESTAMP (6) NOT NULL ENABLE, 
	"END_TIME" TIMESTAMP (6), 
	"PROCESS_STATUS" NUMBER(2,0) DEFAULT 0 NOT NULL ENABLE, 
	 CONSTRAINT "TABLE1_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WEBQUOTE_01"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WEBQUOTE_01" ;

   COMMENT ON COLUMN "WEBQUOTE"."SAP_INTERFACE_BATCHES"."PROCESS_ID" IS 'eg: SC_FLAG, SC_PRICER';
   COMMENT ON COLUMN "WEBQUOTE"."SAP_INTERFACE_BATCHES"."PROCESS_STATUS" IS '0=Processing; 1=Successful; 2=Failed;';


-->5.16.2: New Sequence for new table
CREATE SEQUENCE SAP_INTERFACE_BATCHES_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 999999999999999999999999999999 MINVALUE 1 CACHE 20 ORDER;
   
-->5.16.2: New DB data for SAP Interface batches

insert into schedule_config (ID, TYPE, KEY, VALUE) values ((select max(ID)+1 from schedule_config), 
'COMMON', 'JOB_TEMP_OUTPUT_PATH' , '/app/eap70/webquote/sapfiles/output/');

insert into schedule_config (ID, TYPE, KEY, VALUE) values ((select max(ID)+1 from schedule_config), 
'COMMON', 'ROW_LIMIT' , '100000');


insert into system_code_maintenance (ID, CATEGORY, VALUE, DESCRIPTION, CREATED, CREATED_BY, UPDATED_BY, LAST_UPDATED, VERSION, REGION) values 
((select max(ID)+1 from system_code_maintenance), 
'SAP_SFTP_CONFIG', 'qeuadm|emaqas0|22' , NULL, NULL, 1, 1, NULL, NULL, NULL);

insert into system_code_maintenance (ID, CATEGORY, VALUE, DESCRIPTION, CREATED, CREATED_BY, UPDATED_BY, LAST_UPDATED, VERSION, REGION) values 
((select max(ID)+1 from system_code_maintenance), 
'SAP_SFTP_DESTINATION_PATH', '/data1/asia/sd/sc/' , NULL, NULL, 1, 1, NULL, NULL, NULL);


--[5.16.2.1 Sales Cost Flag Interface DAT]

-->5.16.2.1: Modify table : Added a new column, remove a column and add index for batches process
ALTER TABLE MATERIAL_REGIONAL 
ADD (BATCH_STATUS NUMBER(4) DEFAULT 0 NOT NULL);

COMMENT ON COLUMN MATERIAL_REGIONAL.BATCH_STATUS IS '0=New;1=Update;';

ALTER TABLE MATERIAL_REGIONAL 
DROP COLUMN SAP_SEND_FLAG;

CREATE INDEX MATERIAL_REGIONAL_INDEX2 ON MATERIAL_REGIONAL (BATCH_STATUS ASC);


--[5.16.2.2 Sales Cost Flag Interface DAT]

-->5.16.2.2: New table 

  CREATE TABLE "WEBQUOTE"."PRICER_DELETED" 
   (	"DELETE_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"DELETED_BY" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"DELETED_ON" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE, 
	"DELETED_BATCH_STATUS" NUMBER(4,0) DEFAULT 0 NOT NULL ENABLE, 
	"ID" NUMBER(*,0) NOT NULL ENABLE, 
	"MATERIAL_ID" NUMBER(*,0), 
	"VERSION" NUMBER(*,0), 
	"COST" NUMBER(20,5), 
	"COST_INDICATOR" VARCHAR2(50 BYTE), 
	"QTY_INDICATOR" VARCHAR2(20 BYTE), 
	"PRICE_VALIDITY" VARCHAR2(10 BYTE), 
	"SUPPLIER_NUMBER" NUMBER(*,0), 
	"LEAD_TIME" VARCHAR2(255 BYTE), 
	"BOTTOM_PRICE" NUMBER(20,5), 
	"MOQ" NUMBER(10,3), 
	"MOV" NUMBER(11,2), 
	"MPQ" NUMBER(10,3), 
	"MIN_SELL_PRICE" NUMBER(20,5), 
	"FULL_MFR_PART_NUMBER" VARCHAR2(80 CHAR), 
	"PRICE_LIST_REMARKS1" VARCHAR2(255 CHAR), 
	"PRICE_LIST_REMARKS2" VARCHAR2(255 CHAR), 
	"PRICE_LIST_REMARKS3" VARCHAR2(255 CHAR), 
	"PRICE_LIST_REMARKS4" VARCHAR2(255 BYTE), 
	"SHIPMENT_VALIDITY" DATE, 
	"TERMS_AND_CONDITIONS" VARCHAR2(255 CHAR), 
	"ALLOCATION_FLAG" CHAR(1 BYTE), 
	"AVNET_QC_COMMENTS" VARCHAR2(255 BYTE), 
	"NCNR_FLAG" CHAR(1 BYTE), 
	"NCNR_VALID_FROM" DATE, 
	"RESCHEDULED_WINDOW" NUMBER(3,0), 
	"CANCELLATION_WINDOW" NUMBER(3,0), 
	"COMMODITY_CODE" VARCHAR2(2 BYTE), 
	"GREEN_PRODUCT_INDICATOR" VARCHAR2(2 BYTE), 
	"SALES_ORG" VARCHAR2(4 BYTE), 
	"CREATED_ON" TIMESTAMP (6), 
	"LAST_UPDATED_ON" TIMESTAMP (6), 
	"BIZ_UNIT" VARCHAR2(20 CHAR), 
	"PROGRAM_AVAILABLE_TO_SELL_QTY" NUMBER(15,0), 
	"PROGRAM_MINIMUM_COST" NUMBER(9,5), 
	"PROGRAM_TYPE_ID" NUMBER(15,0), 
	"PROGRAM_EFFECTIVE_DATE" DATE, 
	"PROGRAM_CLOSING_DATE" DATE, 
	"PROGRAM_CALL_FOR_QUOTE" CHAR(1 BYTE), 
	"PROGRAM_AQ_FLAG" CHAR(1 BYTE), 
	"CREATED_BY" VARCHAR2(10 BYTE), 
	"LAST_UPDATED_BY" VARCHAR2(10 BYTE), 
	"PLANT_ID" VARCHAR2(4 BYTE), 
	"MATERIAL_CATEGORY" VARCHAR2(20 BYTE), 
	"LAST_BUY_DATE" DATE, 
	"LAST_SHIP_DATE" DATE, 
	"SHIP_DEBIT" VARCHAR2(3 BYTE), 
	"ECCN" VARCHAR2(14 BYTE), 
	"ALLOCATION_VALID_FROM" DATE, 
	"PROGRAM_SPECIAL_ITEM_FLAG" NUMBER(*,0), 
	"RESALE_INDICATOR" VARCHAR2(50 BYTE), 
	"NEW_PROGRAM_MATERIAL_INDICATOR" CHAR(1 BYTE), 
	"PART_DESCRIPTION" VARCHAR2(512 BYTE), 
	"AVAILABLE_TO_SELL_MORE_FLAG" NUMBER, 
	"DISPLAY_QUOTE_EFF_DATE" DATE, 
	"QUOTATION_EFFECTIVE_DATE" DATE, 
	"QUOTATION_EFFECTIVE_TO" DATE, 
	"CURRENCY" VARCHAR2(5 BYTE), 
	"NORM_SELL" NUMBER(38,5), 
	"START_DATE" DATE, 
	"VENDOR_QUOTE_NUMBER" VARCHAR2(255 BYTE), 
	"SOLD_CUSTOMER_ID" VARCHAR2(10 BYTE), 
	"END_CUSTOMER_ID" VARCHAR2(10 BYTE), 
	"VENDOR_QUOTE_QUANTITY" NUMBER(38,0), 
	"END_CUSTOMER_NAME" VARCHAR2(200 CHAR), 
	"OVERRIDE_FLAG" NUMBER(1,0), 
	"PRICER_TYPE" VARCHAR2(20 BYTE), 
	"SALES_COST_TYPE" VARCHAR2(5 BYTE), 
	"QTY_CONTROL" NUMBER(10,0), 
	"DISPLAY_ON_TOP" NUMBER(1,0), 
	"BATCH_STATUS" NUMBER(4,0) DEFAULT 0 NOT NULL ENABLE, 
	"PRE_VALID_TO_DATE" DATE, 
	 CONSTRAINT "PRICER_DELETED_PK" PRIMARY KEY ("DELETE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WEBQUOTE_01"  ENABLE, 
	 CONSTRAINT "PRICER_DELETED_FK1" FOREIGN KEY ("MATERIAL_ID")
	  REFERENCES "WEBQUOTE"."MATERIAL" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WEBQUOTE_01" ;

   COMMENT ON COLUMN "WEBQUOTE"."PRICER_DELETED"."BATCH_STATUS" IS '0=New;1=Update;';

  CREATE INDEX "WEBQUOTE"."PRICER_DELETED_INDEX1" ON "WEBQUOTE"."PRICER_DELETED" ("DELETED_BATCH_STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WEBQUOTE_01" ;

  
-->5.16.2.2: New Sequence for new table
CREATE SEQUENCE PRICER_DELETED_SEQ INCREMENT BY 1 MAXVALUE 99999999999999999999999999999 MINVALUE 1 CACHE 20 ORDER;

  
-->5.16.2.2 : Modify table : Added a new column for batches process

ALTER TABLE PRICER 
ADD (BATCH_STATUS NUMBER(4) DEFAULT 0 NOT NULL);

COMMENT ON COLUMN PRICER.BATCH_STATUS IS '0=New;1=Update;';




