INSERT INTO MATERIAL_REGIONAL(ID,MATERIAL_ID,BIZ_UNIT,SALES_COST_FLAG,PRODUCT_GROUP2_ID,PRODUCT_GROUP1_ID,PRODUCT_GROUP3,
    PRODUCT_GROUP4,PRODUCT_CATEGORY_ID,DELETION_FLAG,CREATED_ON,LAST_UPDATED_ON,CREATED_BY,LAST_UPDATED_BY,BATCH_STATUS)
  
  SELECT WQ_SEQ.NEXTVAL,ID,P.BIZ_UNIT,0,PRODUCT_GROUP2_ID,PRODUCT_GROUP1_ID,PRODUCT_GROUP3,
    PRODUCT_GROUP4,PRODUCT_CATEGORY_ID,NVL(DELETION_FLAG,0),CREATED_ON,LAST_UPDATED_ON,CREATED_BY,LAST_UPDATED_BY,20
    FROM MATERIAL M INNER JOIN ( 
    SELECT DISTINCT MD.MATERIAL_ID,MD.BIZ_UNIT as BIZ_UNIT FROM MATERIAL_DETAIL MD WHERE  MD.LAST_UPDATED_ON >= TO_DATE('2016-01-01 00:00:00','yyyy-MM-dd HH24:mi:ss')
    UNION 
    SELECT DISTINCT CP.MATERIAL_ID,CP.BIZ_UNIT_ID as BIZ_UNIT FROM CONTRACT_PRICE CP WHERE  CP.LAST_UPDATED_ON >= TO_DATE('2016-01-01 00:00:00','yyyy-MM-dd HH24:mi:ss')
    ) P ON M.ID =P.MATERIAL_ID;

UPDATE QUOTE_ITEM SET SALES_COST_FLAG = 0,SALES_COST_TYPE ='NonSC';

UPDATE PRICER SET BATCH_STATUS = 20;
COMMIT;