package com.avnet.emasia.webquote.webservice.drmsagprea;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2013-12-06T15:00:30.696+08:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", name = "ZWQ_DR_AGP")
@XmlSeeAlso({ObjectFactory.class})
public interface ZWQDRAGP {

    @RequestWrapper(localName = "ZsdWqDrAgp", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.avnet.emasia.webquote.webservice.drmsagprea.ZsdWqDrAgp")
    @WebMethod(operationName = "ZsdWqDrAgp")
    @ResponseWrapper(localName = "ZsdWqDrAgpResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.avnet.emasia.webquote.webservice.drmsagprea.ZsdWqDrAgpResponse")
    public void zsdWqDrAgp(
        @WebParam(mode = WebParam.Mode.INOUT, name = "Return", targetNamespace = "")
        javax.xml.ws.Holder<TableOfZstruDrmsMsg> _return,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Zdrms", targetNamespace = "")
        javax.xml.ws.Holder<TableOfZstruDrms> zdrms
    );
}
