--------------------------------------------------------
--  DDL for View APP_USER_VIEW
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "WEBQUOTE"."APP_USER_VIEW" ("USER_ID", "NAME", "EMP_ID") AS 
  SELECT
ID AS USER_ID,
UPPER(NAME) AS NAME, 
UPPER(EMPLOYEE_ID) AS EMP_ID
FROM APP_USER;

--------------------------------------------------------
--  DDL for View MANUFACTURER_VIEW
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "WEBQUOTE"."MANUFACTURER_VIEW" ("ID", "NAME") AS 
  SELECT 
ID, 
UPPER(NAME) AS NAME
FROM MANUFACTURER;

--------------------------------------------------------
--  DDL for View MFR_BIZUNIT_VIEW
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "WEBQUOTE"."MFR_BIZUNIT_VIEW" ("MANUFACTURER_ID", "BIZ_UNIT_ID") AS 
  SELECT 
MANUFACTURER_ID, 
UPPER(BIZ_UNIT_ID) AS BIZ_UNIT_ID
FROM MANUFACTURER_BIZUNIT_MAPPING;

--------------------------------------------------------
--  DDL for View PROGRAM_TYPE_VIEW
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "WEBQUOTE"."PROGRAM_TYPE_VIEW" ("ID", "NAME") AS 
  SELECT 
ID, 
UPPER(NAME) AS NAME
FROM PROGRAM_TYPE;

--------------------------------------------------------
--  DDL for View MATERIAL_TYPE_VIEW
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "WEBQUOTE"."MATERIAL_TYPE_VIEW" ("MATERIAL_TYPE_ID", "DESCRIPTION") AS 
  SELECT 
UPPER(NAME) AS MATERIAL_TYPE_ID, 
UPPER(DESCRIPTION) AS DESCRIPTION
FROM MATERIAL_TYPE;


--------------------------------------------------------
--  DDL for View PRODUCT_GROUP_VIEW
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "WEBQUOTE"."PRODUCT_GROUP_VIEW" ("ID", "NAME") AS 
  SELECT 
ID, 
UPPER(NAME) AS NAME
FROM PRODUCT_GROUP;

--------------------------------------------------------
--  DDL for View QUOTE_ITEM_DESIGN_VIEW
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "WEBQUOTE"."QUOTE_ITEM_DESIGN_VIEW" ("BMT_FLAG_CODE", "DR_COMMENTS", "DR_COST", "DR_MFR_NO", "DR_RESALE", "QUOTE_ITEM_ID", "DELTA_DATE") AS 
  SELECT 
UPPER(DECODE(BMT_FLAG_CODE,'99', '{}', BMT_FLAG_CODE)) AS BMT_FLAG_CODE,
UPPER(DR_COMMENTS) AS DR_COMMENTS,
DR_COST,
UPPER(DR_MFR_NO) AS DR_MFR_NO,
DR_RESALE,
QUOTE_ITEM_ID,
TO_CHAR(NVL(LAST_UPDATED_TIME,CREATED_TIME), 'YYYYMMDD') AS DELTA_DATE
FROM QUOTE_ITEM_DESIGN;

--------------------------------------------------------
--  DDL for View QUOTE_ITEM_VIEW
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "WEBQUOTE"."QUOTE_ITEM_VIEW" ("BIZ_UNIT", "FORM_NUMBER", "USER_ID", "SOLD_2_CUST_NAME", "SOLD_2_CUST_NO", "TEAM_ID", "YOUR_REFERENCE", "AQCC", "BOM_NUMBER", "COST", "COST_INDICATOR", "CUSTOMER_TYPE", "DESIGN_IN_CAT", "DESIGN_LOCATION", "DESIGN_REGION", "END_CUST_NO", "END_CUST_NAME", "ENQ_SEGMENT", "FIRST_RFQ_CODE", "FIS_MTH", "FIS_QTR", "FIS_YEAR", "ID", "INT_COMMENT", "INT_TRF_COMMENT", "LAST_BMT_I_DATE", "LAST_BMT_O_DATE", "LAST_IT_UP_TIME", "LAST_QC_I_DATE", "LAST_QC_O_DATE", "LAST_RIT_UP_TIME", "LAST_SQ_I_DATE", "LAST_SQ_O_DATE", "LAST_UP_BMT_EID", "LAST_UP_PM_EID", "LAST_UP_QC_EID", "PRODUCT_GROUP1_ID", "PRODUCT_GROUP2_ID", "PROD_GRP3", "PROD_GRP4", "QUOTE_NUMBER", "QUOTE_TYPE", "QUOTED_PART_NUM", "QUOTED_PRICE", "QUOTED_QTY", "REQ_MFR_ID", "REQ_PART_NUM", "REQ_QTY", "REVERT_VER", "SENT_O_TIME", "STAGE", "STATUS", "SUBMISSION_DATE", "TARGET_RESALE", "DELTA_DATE", "PROGRAM_TYPE", "MATERIAL_TYPE_ID") AS 
  SELECT 
UPPER(QUOTE.BIZ_UNIT) AS BIZ_UNIT,
UPPER(QUOTE.FORM_NUMBER) AS FORM_NUMBER,
QUOTE.SALES_USER_ID AS USER_ID,
UPPER(QUOTE.SOLD_TO_CUSTOMER_NAME) AS SOLD_2_CUST_NAME,
UPPER(QUOTE.SOLD_TO_CUSTOMER_NUMBER) AS SOLD_2_CUST_NO,
UPPER(QUOTE.TEAM_ID) AS TEAM_ID,
UPPER(QUOTE.YOUR_REFERENCE) AS YOUR_REFERENCE,
UPPER(QUOTE_ITEM.AQCC) AS AQCC,
UPPER(QUOTE_ITEM.BOM_NUMBER) AS BOM_NUMBER,
QUOTE_ITEM.COST AS COST,
UPPER(QUOTE_ITEM.COST_INDICATOR) AS COST_INDICATOR,
UPPER(QUOTE_ITEM.CUSTOMER_TYPE) AS CUSTOMER_TYPE,
UPPER(QUOTE_ITEM.DESIGN_IN_CAT) AS DESIGN_IN_CAT,
UPPER(QUOTE_ITEM.DESIGN_LOCATION) AS DESIGN_LOCATION,
UPPER(QUOTE_ITEM.DESIGN_REGION) AS DESIGN_REGION,
UPPER(QUOTE_ITEM.END_CUSTOMER_NUMBER) AS END_CUST_NO,
UPPER(QUOTE_ITEM.END_CUSTOMER_NAME) AS END_CUST_NAME,
UPPER(QUOTE_ITEM.ENQUIRY_SEGMENT) AS ENQ_SEGMENT,
UPPER(QUOTE_ITEM.FIRST_RFQ_CODE) AS FIRST_RFQ_CODE,
UPPER(QUOTE_ITEM.FIS_MTH) AS FIS_MTH,
UPPER(QUOTE_ITEM.FIS_QTR) AS FIS_QTR,
UPPER(QUOTE_ITEM.FIS_YEAR) AS FIS_YEAR,
QUOTE_ITEM.ID AS ID,
UPPER(QUOTE_ITEM.INTERNAL_COMMENT) AS INT_COMMENT,
UPPER(QUOTE_ITEM.INTERNAL_TRANSFER_COMMENT) AS INT_TRF_COMMENT,
TO_CHAR(QUOTE_ITEM.LAST_BMT_IN_DATE, 'YYYYMMDDHH24MISS') AS LAST_BMT_I_DATE,
TO_CHAR(QUOTE_ITEM.LAST_BMT_OUT_DATE, 'YYYYMMDDHH24MISS') AS LAST_BMT_O_DATE,
TO_CHAR(QUOTE_ITEM.LAST_IT_UPDATE_TIME, 'YYYYMMDDHH24MISS') AS LAST_IT_UP_TIME,
TO_CHAR(QUOTE_ITEM.LAST_QC_IN_DATE, 'YYYYMMDDHH24MISS') AS LAST_QC_I_DATE,
TO_CHAR(QUOTE_ITEM.LAST_QC_OUT_DATE, 'YYYYMMDDHH24MISS') AS LAST_QC_O_DATE,
TO_CHAR(QUOTE_ITEM.LAST_RIT_UPDATE_TIME, 'YYYYMMDDHH24MISS') AS LAST_RIT_UP_TIME,
TO_CHAR(QUOTE_ITEM.LAST_SQ_IN_DATE, 'YYYYMMDDHH24MISS') AS LAST_SQ_I_DATE,
TO_CHAR(QUOTE_ITEM.LAST_SQ_OUT_DATE, 'YYYYMMDDHH24MISS') AS LAST_SQ_O_DATE,
UPPER(QUOTE_ITEM.LAST_UPDATED_BMT) AS LAST_UP_BMT_EID,
UPPER(QUOTE_ITEM.LAST_UPDATED_PM) AS LAST_UP_PM_EID,
UPPER(QUOTE_ITEM.LAST_UPDATED_QC) AS LAST_UP_QC_EID,
QUOTE_ITEM.PRODUCT_GROUP1_ID,
QUOTE_ITEM.PRODUCT_GROUP2_ID,
UPPER(QUOTE_ITEM.PRODUCT_GROUP3) AS PROD_GRP3,
UPPER(QUOTE_ITEM.PRODUCT_GROUP4) AS PROD_GRP4,
UPPER(QUOTE_ITEM.QUOTE_NUMBER) AS QUOTE_NUMBER,
UPPER(QUOTE_ITEM.QUOTE_TYPE) AS QUOTE_TYPE,
UPPER(QUOTE_ITEM.QUOTED_PART_NUMBER) AS QUOTED_PART_NUM,
QUOTE_ITEM.QUOTED_PRICE AS QUOTED_PRICE,
QUOTE_ITEM.QUOTED_QTY AS QUOTED_QTY,
QUOTE_ITEM.REQUESTED_MFR_ID AS REQ_MFR_ID,
UPPER(QUOTE_ITEM.REQUESTED_PART_NUMBER) AS REQ_PART_NUM,
QUOTE_ITEM.REQUESTED_QTY AS REQ_QTY,
UPPER(QUOTE_ITEM.REVERT_VERSION) AS REVERT_VER,
TO_CHAR(QUOTE_ITEM.SENT_OUT_TIME, 'YYYYMMDDHH24MISS') AS SENT_O_TIME,
UPPER(QUOTE_ITEM.STAGE) AS STAGE,
UPPER(QUOTE_ITEM.STATUS) AS STATUS,
TO_CHAR(QUOTE_ITEM.SUBMISSION_DATE, 'YYYYMMDDHH24MISS') AS SUBMISSION_DATE,
QUOTE_ITEM.TARGET_RESALE AS TARGET_RESALE,
TO_CHAR(NVL(QUOTE_ITEM.LAST_UPDATED_ON,QUOTE.CREATED_ON), 'YYYYMMDD') AS DELTA_DATE,
QUOTE_ITEM.PROGRAM_TYPE AS PROGRAM_TYPE,
UPPER(QUOTE_ITEM.MATERIAL_TYPE_ID) AS MATERIAL_TYPE_ID
FROM QUOTE, QUOTE_ITEM
WHERE QUOTE_ITEM.QUOTE_ID = QUOTE.ID;

--------------------------------------------------------
--  DDL for View SALES_ORDER_VIEW
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "WEBQUOTE"."SALES_ORDER_VIEW" ("QUOTE_NO", "SALES_ORD_NO", "SALES_ORD_QTY", "SALES_ORD_RESALE", "SALES_ORD_IT_NO", "DELTA_DATE") AS 
  SELECT
UPPER(QUOTE_NUMBER) AS QUOTE_NO,
UPPER(SALES_ORDER_NUMBER) AS SALES_ORD_NO,
SALES_ORDER_QTY AS SALES_ORD_QTY,
SALES_ORDER_RESALE AS SALES_ORD_RESALE,
SALES_ORDER_ITEM_NUMBER AS SALES_ORD_IT_NO,
TO_CHAR(NVL(LAST_UPDATED_ON,CREATED_ON), 'YYYYMMDD') AS DELTA_DATE
FROM SALES_ORDER;

--------------------------------------------------------
--  DDL for View TEAM_BIZUNIT_VIEW
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "WEBQUOTE"."TEAM_BIZUNIT_VIEW" ("TEAM_ID", "BIZ_UNIT_ID") AS 
  SELECT 
UPPER(NAME) AS TEAM_ID, 
UPPER(BIZ_UNIT_ID) AS BIZ_UNIT_ID
FROM TEAM;

--------------------------------------------------------
--  DDL for View USER_BIZUNIT_VIEW
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "WEBQUOTE"."USER_BIZUNIT_VIEW" ("USER_ID", "BIZ_UNIT_ID") AS 
  SELECT 
USER_ID, 
UPPER(BIZ_UNIT_ID) AS BIZ_UNIT_ID
FROM USER_BIZUNIT_MAPPING;


--------------------------------------------------------
--  DDL for View USER_DATA_ACCESS_VIEW
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "WEBQUOTE"."USER_DATA_ACCESS_VIEW" ("ACTIVE_USER", "USER_ID", "MANUFACTURER_ID", "PRODUCT_GROUP_ID", "TEAM_ID", "MATERIAL_TYPE_ID", "PROGRAM_TYPE_NAME") AS 
  SELECT 
AA.ACTIVE AS ACTIVE_USER,new.USER_ID,new.MANUFACTURER_ID,new.PRODUCT_GROUP_ID,new.TEAM_ID,new.MATERIAL_TYPE_ID,new.PROGRAM_TYPE_NAME FROM
(
SELECT 
M.USER_ID AS USER_ID,
D.MANUFACTURER_ID AS MANUFACTURER_ID,
D.PRODUCT_GROUP_ID AS PRODUCT_GROUP_ID,
UPPER (D.TEAM_ID) AS TEAM_ID,
UPPER (D.MATERIAL_TYPE_ID) AS MATERIAL_TYPE_ID,
UPPER (P.NAME) AS PROGRAM_TYPE_NAME
FROM USER_DATAACCESS_MAPPING M, DATA_ACCESS D

    LEFT JOIN PROGRAM_TYPE P ON P.ID=D.PROGRAM_TYPE_ID
    WHERE D.ID=M.DATA_ACCESS_ID
    ) new
      LEFT JOIN APP_USER AA ON AA.ID=new.USER_ID;



--------------------------------------------------------
--  DDL for View USER_ROLE_VIEW
--------------------------------------------------------

  CREATE OR REPLACE VIEW "WEBQUOTE"."USER_ROLE_VIEW" ("EMP_ID", "NAME", "USER_ID", "REPORT_TO", "DATA_SUPERVISOR") AS 
  SELECT
UPPER(APP_USER.EMPLOYEE_ID) AS EMP_ID,
UPPER(ROLE.NAME) AS NAME,
APP_USER.ID AS USER_ID,
APP_USER.REPORT_TO AS REPORT_TO,
APP_USER.DATA_SUPERVISOR AS DATA_SUPERVISOR
FROM USER_ROLE_MAPPING URM, APP_USER, ROLE
WHERE ROLE.ID = URM.ROLE_ID
AND URM.USER_ID = APP_USER.ID;


