--Changes on Biz_Unit Table
ALTER TABLE BIZ_UNIT ADD (HIGHER_BIZ_UNIT VARCHAR2(10) );

ALTER TABLE BIZ_UNIT ADD CONSTRAINT BIZ_UNIT_FK1 FOREIGN KEY (HIGHER_BIZ_UNIT) REFERENCES BIZ_UNIT (NAME) ENABLE;

INSERT INTO "WEBQUOTE"."BIZ_UNIT" (NAME) VALUES ('ASIA');

UPDATE "WEBQUOTE"."BIZ_UNIT" SET HIGHER_BIZ_UNIT = 'ASIA' WHERE NAME = 'CHINA';
UPDATE "WEBQUOTE"."BIZ_UNIT" SET HIGHER_BIZ_UNIT = 'ASIA' WHERE NAME = 'ASEAN';
UPDATE "WEBQUOTE"."BIZ_UNIT" SET HIGHER_BIZ_UNIT = 'ASIA' WHERE NAME = 'TW';
--... need more region?

COMMIT;

--Changes on PRICER Table
ALTER TABLE PRICER ADD (SALES_COST_TYPE VARCHAR2(5) );
ALTER TABLE PRICER ADD (QTY_CONTROL NUMBER(10) );
ALTER TABLE PRICER ADD (DISPLAY_ON_TOP NUMBER(1) );
---ALTER TABLE PRICER ADD (DISPLAY_ON_TOP NUMBER(1) );


--Changes on QUANTITY_BREAK_PRICE Table
ALTER TABLE QUANTITY_BREAK_PRICE ADD (SALES_COST NUMBER(15, 5) );
ALTER TABLE QUANTITY_BREAK_PRICE ADD (SUGGESTED_RESALE NUMBER(15, 5) );



--CREATE MATERIAL_REGIONAL TABLE

CREATE TABLE "WEBQUOTE"."MATERIAL_REGIONAL" 
   (	"ID" NUMBER(18,0), 
    MATERIAL_ID NUMBER(18,0),
    BIZ_UNIT VARCHAR(10),
    "SALES_COST_FLAG" CHAR(1 BYTE) NOT NULL, 
	"PRODUCT_GROUP2_ID" NUMBER(18,0), 
	"PRODUCT_GROUP1_ID" NUMBER(18,0), 
	"PRODUCT_GROUP3" VARCHAR2(250 BYTE), 
	"PRODUCT_GROUP4" VARCHAR2(250 BYTE),
  "PRODUCT_CATEGORY_ID" NUMBER(18,0), 
	"DELETION_FLAG" CHAR(1 BYTE) NOT NULL, 
  "SAP_SEND_FLAG" CHAR(1 BYTE) NOT NULL, 
	"CREATED_ON" TIMESTAMP (6), 
	"LAST_UPDATED_ON" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(20 BYTE), 
	"LAST_UPDATED_BY" VARCHAR2(10 BYTE)
   ) ;
   
ALTER TABLE MATERIAL_REGIONAL MODIFY DELETION_FLAG DEFAULT 0;
ALTER TABLE MATERIAL_REGIONAL MODIFY (ID NOT NULL);

ALTER TABLE MATERIAL_REGIONAL ADD CONSTRAINT MATERIAL_REGIONAL_PK PRIMARY KEY ( ID) ENABLE;

ALTER TABLE MATERIAL_REGIONAL ADD CONSTRAINT MATERIAL_REGIONAL_FK1 FOREIGN KEY (MATERIAL_ID) REFERENCES MATERIAL (ID) ENABLE;

ALTER TABLE MATERIAL_REGIONAL ADD CONSTRAINT MATERIAL_REGIONAL_FK2 FOREIGN KEY (BIZ_UNIT ) REFERENCES BIZ_UNIT( NAME) ENABLE;

ALTER TABLE MATERIAL_REGIONAL ADD CONSTRAINT MATERIAL_REGIONAL_FK3 FOREIGN KEY (PRODUCT_GROUP2_ID) REFERENCES PRODUCT_GROUP( ID) ENABLE;

ALTER TABLE MATERIAL_REGIONAL ADD CONSTRAINT MATERIAL_REGIONAL_FK4 FOREIGN KEY (PRODUCT_GROUP1_ID) REFERENCES PRODUCT_GROUP( ID) ENABLE;

ALTER TABLE MATERIAL_REGIONAL ADD CONSTRAINT MATERIAL_REGIONAL_FK5 FOREIGN KEY (PRODUCT_CATEGORY_ID) REFERENCES PRODUCT_CATEGORY (ID) ENABLE;

ALTER TABLE MATERIAL_REGIONAL ADD CONSTRAINT MATERIAL_REGIONAL_UK1 UNIQUE (MATERIAL_ID, BIZ_UNIT) ENABLE;


CREATE INDEX MATERIAL_REGIONAL_INDEX1 ON MATERIAL_REGIONAL (MATERIAL_ID);

-- change in quote_item and quote_item_his
ALTER TABLE QUOTE_ITEM ADD (SALES_COST_FLAG CHAR(1) );
ALTER TABLE QUOTE_ITEM ADD (SALES_COST_TYPE VARCHAR2(10) );
ALTER TABLE QUOTE_ITEM ADD (SALES_COST NUMBER(15, 5) );
ALTER TABLE QUOTE_ITEM ADD (SUGGESTED_RESALE NUMBER(15, 5) );
ALTER TABLE QUOTE_ITEM ADD (CUSTOMER_GROUP_ID VARCHAR2(10) );

ALTER TABLE QUOTE_ITEM_HIS ADD (SALES_COST_FLAG CHAR(1) );
ALTER TABLE QUOTE_ITEM_HIS ADD (SALES_COST_TYPE VARCHAR2(10) );
ALTER TABLE QUOTE_ITEM_HIS ADD (SALES_COST NUMBER(15, 5) );
ALTER TABLE QUOTE_ITEM_HIS ADD (SUGGESTED_RESALE NUMBER(15, 5) );
ALTER TABLE QUOTE_ITEM_HIS ADD (CUSTOMER_GROUP_ID VARCHAR2(10) );  

-- change in APP_USER table
ALTER TABLE APP_USER ADD (SALES_COST_ACCESS_FLAG CHAR(1));

-- create new SAP_DAP_CUST table
CREATE TABLE SAP_DPA_CUST 
(
  ID NUMBER(18) NOT NULL 
, CUST_GROUP_ID VARCHAR2(10) NOT NULL  
, NAME VARCHAR2(40)  
, SALES_ORG VARCHAR2(4) 
, BIZ_UNIT VARCHAR2(10) 
, SOLD_TO_CUST_NUMBER VARCHAR2(10)  
, SHIP_TO_CUST_NUMBER VARCHAR2(10) 
, END_CUST_NUMBER VARCHAR2(10) 
, CREATED_ON TIMESTAMP NOT NULL 
, LAST_UPDATED_ON TIMESTAMP NOT NULL 
, CONSTRAINT CUSTOMER_GROUP_PK PRIMARY KEY (ID) ENABLE 
);
ALTER TABLE SAP_DPA_CUST ADD CONSTRAINT CUSTOMER_GROUP_FK1 FOREIGN KEY( BIZ_UNIT) REFERENCES BIZ_UNIT ( NAME) ENABLE;

ALTER TABLE PRICER RENAME COLUMN DESCRIPTION TO PART_DESCRIPTION;

--change funtion name for change instance price to catalog search;
 UPDATE APP_FUNCTION SET NAME='Catalog Search' WHERE ID =(select ID from APP_FUNCTION WHERE NAME='Instant Price Check');
 INSERT INTO APP_PROPERTY(
	PROP_DESC,
	PROP_KEY,
	PROP_RESERVED,
	PROP_VALUE) VALUES(null,'CHART_ANALYTIC_URL',1,'https://app.powerbi.com/Redirect?action=OpenApp'||'&'||'appId=1c8df362-f316-4d74-9f76-8732195b5a45'||'&'||'ctid=8820279b-c0be-4bde-83ed-fe6b6f9724d5');


