package com.avnet.emasia.webquote.exception;

/**
 * The Interface CommonConstants.
 */
public interface CommonConstants {

	/** The Constant WQ_WEB_BACKUP_FILE_EXCEPTION. */
	String WQ_WEB_BACKUP_FILE_EXCEPTION = "wq.error.90000";

	/** The Constant COMMON_COULD_NT_DISCONNECT_SERVER. */
	String COMMON_COULD_NT_DISCONNECT_SERVER = "wq.error.101";

	/** The Constant COMMON_COULD_NT_INIT_TIMER. */
	String COMMON_COULD_NT_INIT_TIMER = "wq.error.102";

	/** The Constant WQ_WEB_COULD_NT_PUT_FILE_SERVER. */
	String WQ_WEB_COULD_NT_PUT_FILE_SERVER = "wq.error.90004";

	/** The Constant WQ_WEB_DATA_ERROR_PLEASE_CHECK. */
	String WQ_WEB_DATA_ERROR_PLEASE_CHECK = "wq.error.90006";

	/**
	 * The Constant COMMON_DP_ERROR_OCCURED_CONVERT_RESPONSEQUOTETYPE_TO_XML.
	 */
	String COMMON_DP_ERROR_OCCURED_CONVERT_RESPONSEQUOTETYPE_TO_XML = "wq.error.103";

	/** The Constant COMMON_FAILED_TO_ENQUIRY_AGP_IN_SAP. */
	String COMMON_FAILED_TO_ENQUIRY_AGP_IN_SAP = "wq.error.107";

	/**
	 * The Constant COMMON_FAILED_TO_SEND_THE_MAPPING_OF_MFR_AND_REGION_TO_SAP.
	 */
	String COMMON_FAILED_TO_SEND_THE_MAPPING_OF_MFR_AND_REGION_TO_SAP = "wq.error.108";

	/** The Constant WQ_WEB_FTP_SERVER_REFUSED_CONNECTION. */
	String WQ_WEB_FTP_SERVER_REFUSED_CONNECTION = "wq.error.90011";

	/** The Constant WQ_WEB_QUOTE_NUMBER_ERROR. */
	String WQ_WEB_QUOTE_NUMBER_ERROR = "wq.error.90024";

	/** The Constant COMMON_RFQS_QTY_INDICATOR_DOES_NOT_MATCH_PMOQ. */
	String COMMON_RFQS_QTY_INDICATOR_DOES_NOT_MATCH_PMOQ = "wq.error.123";

	/** The Constant WQ_WEB_SEND_EMAIL_FAILED_ERROR_MSG_. */
	String WQ_WEB_SEND_EMAIL_FAILED_ERROR_MSG_ = "wq.error.90027";

	/** The Constant WQ_WEB_SERVICE_. */
	String WQ_WEB_SERVICE_ = "wq.error.90028";

	/** The Constant COMMON_THE_SERVICE_IS_NOT_READY. */
	String COMMON_THE_SERVICE_IS_NOT_READY = "wq.error.126";

	/** The Constant COMMON_THE_SERVICE_IS_STILL_STARTED. */
	String COMMON_THE_SERVICE_IS_STILL_STARTED = "wq.error.127";

	/** The Constant WQ_WEB_TRANSFER_EXCPTION_. */
	String WQ_WEB_TRANSFER_EXCPTION = "wq.error.90031";

	/** The Constant WQ_WEB_TRANSFER_TO_QC_FAILED. */
	String COMMON_TRANSFER_TO_QC_FAILED = "wq.error.128";

	/** The Constant COMMON_WRITE_FILE_ERROR. */
	String COMMON_WRITE_FILE_ERROR = "wq.error.130";
	
	/** The wq web service failed send message to dp. */
	String WQ_WEB_SERVICE_FAILED_SEND_MESSAGE_TO_DP = "wq.error.90035";
	
	/** The Constant WQ_EJB_UTILITY_HA_TIMER_SERVICE_START_WITH_ERROR. */
	String WQ_EJB_UTILITY_HA_TIMER_SERVICE_START_WITH_ERROR = "wq.error.60004";

	/** The Constant WQ_EJB_USR_AUTH_ROLE_NAME_ALREADY_EXISTS. */
	String WQ_EJB_USR_AUTH_ROLE_NAME_ALREADY_EXISTS = "wq.error.50000";

	/** The Constant WQ_EJB_QUOTE_SEND_EMAIL_FAILED. */
	String WQ_EJB_QUOTE_SEND_EMAIL_FAILED = "wq.error.30000";

	/** The Constant COMMON_FAILED_TO_CREATE_PROSPECTIVE_CUSTOMER. */
	String COMMON_FAILED_TO_CREATE_PROSPECTIVE_CUSTOMER = "wq.error.105";

	/** The Constant COMMON_FAILED_TO_CREATE_PROSPECTIVE_CUSTOMER_. */
	String COMMON_FAILED_TO_CREATE_PROSPECTIVE_CUSTOMER_ = "wq.error.104";

	/** The Constant WQ_EJB_QUOTE_FAILED_TO_UPDATE_AGP_IN_SAP. */
	String WQ_EJB_QUOTE_FAILED_TO_UPDATE_AGP_IN_SAP = "wq.error.30006";

	/** The Constant COMMON_FIND_QUOTE_NUMBER_ERROR. */
	String COMMON_FIND_QUOTE_NUMBER_ERROR = "wq.error.109";

	/** The Constant COMMON_QUOTE_NUMBER_NOT_FOUND. */
	String COMMON_QUOTE_NUMBER_NOT_FOUND = "wq.error.121";

	/** The Constant COMMON_FAILED_TO_CREATE_UPDATE_QUOTE_IN_SAP. */
	String COMMON_FAILED_TO_CREATE_UPDATE_QUOTE_IN_SAP = "wq.error.106";

	/** The Constant WQ_EJB_MASTER_DATA_NO_FILE_FOUND_EXCEPTION. */
	String WQ_EJB_MASTER_DATA_NO_FILE_FOUND_EXCEPTION = "wq.error.20000";

	/** The Constant WQ_EJB_MASTER_DATA_CANNNOT_BE_FOUND. */
	String WQ_EJB_MASTER_DATA_CANNNOT_BE_FOUND = "wq.error.20001";

	/** The Constant WQ_EJB_MASTER_DATA_CANNOT_CREATE_THE_PATH. */
	String WQ_EJB_MASTER_DATA_CANNOT_CREATE_THE_PATH = "wq.error.20002";

	/** The Constant WQ_EJB_MASTER_DATA_CANNOT_FIND_COMPONENT_IN_VIEW. */
	String WQ_EJB_MASTER_DATA_CANNOT_FIND_COMPONENT_IN_VIEW = "wq.error.20003";

	/** The Constant WQ_EJB_MASTER_DATA_CANT_FIND_THE_QUOTEITEM. */
	String WQ_EJB_MASTER_DATA_CANT_FIND_THE_QUOTEITEM = "wq.error.20005";

	/** The Constant WQ_EJB_MASTER_DATA_COULD_NOT_CONNECT_TO_SERVER. */
	String WQ_EJB_MASTER_DATA_COULD_NOT_CONNECT_TO_SERVER = "wq.error.20006";

	/** The Constant WQ_EJB_MASTER_DATA_COULD_NOT_TO_SET_FILE_TYPE. */
	String WQ_EJB_MASTER_DATA_COULD_NOT_TO_SET_FILE_TYPE = "wq.error.20008";

	/** The Constant WQ_EJB_MASTER_DATA_COULDNT_CLOSE_FILEINPUTSTREAM. */
	String WQ_EJB_MASTER_DATA_COULDNT_CLOSE_FILEINPUTSTREAM = "wq.error.20009";

	/** The Constant WQ_EJB_MASTER_DATA_COULDNT_CLOSE_FILEOUTPUTSTREAM. */
	String WQ_EJB_MASTER_DATA_COULDNT_CLOSE_FILEOUTPUTSTREAM = "wq.error.20010";

	/** The Constant WQ_EJB_MASTER_DATA_COULDNT_DELETE_FILE_FROM_SERVER. */
	String WQ_EJB_MASTER_DATA_COULDNT_DELETE_FILE_FROM_SERVER = "wq.error.20011";

	/** The Constant WQ_EJB_MASTER_DATA_COULDNT_GET_FILE_FROM_SERVER. */
	String WQ_EJB_MASTER_DATA_COULDNT_GET_FILE_FROM_SERVER = "wq.error.20012";

	/**
	 * The Constant WQ_EJB_MASTER_DATA_DATE_FORMAT_ERROR_SUPPORT_FORMAT_LIKE.
	 */
	String WQ_EJB_MASTER_DATA_DATE_FORMAT_ERROR_SUPPORT_FORMAT_LIKE = "wq.error.20014";

	/**
	 * The Constant
	 * WQ_EJB_MASTER_DATA_DP_ERROR_OCCURED_WHEN_SENDING_OUT_MESSAGE.
	 */
	String WQ_EJB_MASTER_DATA_DP_ERROR_OCCURED_WHEN_SENDING_OUT_MESSAGE = "wq.error.20016";

	/**
	 * The Constant
	 * WQ_EJB_MASTER_DATA_DP_VALIDATION_ERROR_FOR_RESPONSEQUOTETYPE.
	 */
	String WQ_EJB_MASTER_DATA_DP_VALIDATION_ERROR_FOR_RESPONSEQUOTETYPE = "wq.error.20017";

	/**
	 * The Constant WQ_EJB_MASTER_DATA_DP_VALIDATION_ERROR_FOR_WEBREQUESTOBJECT.
	 */
	String WQ_EJB_MASTER_DATA_DP_VALIDATION_ERROR_FOR_WEBREQUESTOBJECT = "wq.error.20018";

	/** The Constant WQ_EJB_MASTER_DATA_ERROR_OCCURED_IN_AQ_LOGIC. */
	String WQ_EJB_MASTER_DATA_ERROR_OCCURED_IN_AQ_LOGIC = "wq.error.20019";

	/**
	 * The Constant
	 * WQ_EJB_MASTER_DATA_ERROR_OCCURED_WHEN_CONVERTING_CREATERFQXML_TO_WEBREQUESTOBJECT.
	 */
	String WQ_EJB_MASTER_DATA_ERROR_OCCURED_WHEN_CONVERTING_CREATERFQXML_TO_WEBREQUESTOBJECT = "wq.error.20020";

	/** The Constant COMMON_GET_CONFIG_HAS_EMPTY_KEY. */
	String COMMON_GET_CONFIG_HAS_EMPTY_KEY = "wq.error.110";

	/** The Constant COMMON_INCORRECT_BMT_FLAG_DESC. */
	String COMMON_INCORRECT_BMT_FLAG_DESC = "wq.error.111";
	/**
	 * The Constant
	 * WQ_EJB_MASTER_DATA_LISTED_ALL_THE_REMOTE_DIRECTORY_FILE_IS_ABNORMAL.
	 */
	String WQ_EJB_MASTER_DATA_LISTED_ALL_THE_REMOTE_DIRECTORY_FILE_IS_ABNORMAL = "wq.error.20031";

	/** The Constant COMMON_LOAD_DATA_ERROR. */
	String COMMON_LOAD_DATA_ERROR = "wq.error.112";

	/** The Constant WQ_EJB_MASTER_DATA_LOADFILES_EXCPTION_. */
	String WQ_EJB_MASTER_DATA_LOADFILES_EXCPTION = "wq.error.20033";

	/** The Constant WQ_EJB_MASTER_DATA_LOCAL_FILE_NOT_FOUND. */
	String WQ_EJB_MASTER_DATA_LOCAL_FILE_NOT_FOUND = "wq.error.20034";
	/**
	 * The Constant
	 * WQ_EJB_MASTER_DATA_METHOD_TRANSFER_INVOCATIONTARGETEXCEPTION.
	 */
	String WQ_EJB_MASTER_DATA_METHOD_TRANSFER_INVOCATIONTARGETEXCEPTION = "wq.error.20044";
	/** The Constant WQ_EJB_MASTER_DATA_QUANTITY_IS_NOT_IN_ANY_RANGE. */
	String WQ_EJB_MASTER_DATA_QUANTITY_IS_NOT_IN_ANY_RANGE = "wq.error.20050";

	/** The Constant WQ_EJB_MASTER_DATA_QUOTATION_PRICE_IS_BLANK. */
	String WQ_EJB_MASTER_DATA_QUOTATION_PRICE_IS_BLANK = "wq.error.20051";

	/**
	 * The Constant
	 * COMMON_RESALEINDICATOR_MUST_BE_4_CHARATERS_LANG_FOR_PROGRAMMATERIAL.
	 */
	String COMMON_RESALEINDICATOR_MUST_BE_4_CHARATERS_LANG_FOR_PROGRAMMATERIAL = "wq.error.122";

	/** The Constant COMMON_SERVICE_NOT_FOUND. */
	String COMMON_SERVICE_NOT_FOUND = "wq.error.124";

	/** The Constant WQ_EJB_MASTER_DATA_SET_TIMEOUT_ERROR. */
	String WQ_EJB_MASTER_DATA_SET_TIMEOUT_ERROR = "wq.error.20057";

	/** The Constant WQ_EJB_MASTER_DATA_TASK_ALREADY_EXIST. */
	String COMMON_TASK_ALREADY_EXIST = "wq.error.125";

	/**
	 * The Constant COMMON_UPDATE_TASKSERVICE_NOT_INSTALLEDSERVICE.
	 */
	String COMMON_UPDATE_TASKSERVICE_NOT_INSTALLEDSERVICE = "wq.error.129";

	/** The Constant WQ_EJB_MASTER_DATA_VALUE_OF_MUST_BE_A_LIST_OR_AN_ARRAY. */
	String WQ_EJB_MASTER_DATA_VALUE_OF_MUST_BE_A_LIST_OR_AN_ARRAY = "wq.error.20062";
	/** The wq ejb master data cant find address number. */
	String WQ_EJB_MASTER_DATA_CANT_FIND_ADDRESS_NUMBER = "wq.error.20068";
	
	/** The Constant WQ_WEB_PATH_IS_NOT_RIGHT. */
	String WQ_EJB_MASTER_DATA_PATH_IS_NOT_RIGHT = "wq.error.20069";

	/** The Constant WQ_EJB_MASTER_DATA_TXT_FILE_READ_ERROR. */
	String WQ_EJB_MASTER_DATA_TXT_FILE_READ_ERROR = "wq.error.20070";
	/**
	 * The constant wq jpa entity msg check msg
	 */
	String WQ_JPA_ENTITY_MSG_CHECK_MSG="wq.message.checkMsg";
	
	/** The constant wq web final quotation price has been updated*/
	String WQ_WEB_FINAL_QUOTATION_PRICE_HAS_BEEN_UPDATED="wq.error.90032";
}
