package com.avnet.emasia.webquote.webservice.zwqrmtosap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.7.redhat-1
 * 2014-11-25T11:39:33.895+08:00
 * Generated source version: 2.7.7.redhat-1
 * 
 */
@WebServiceClient(name = "ZWQRMTOSAP", 
                  wsdlLocation = "file:/D:/trunk/WQ_EJB_Quote/ejbModule/zwqrmtosap.wsdl",
                  targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style") 
public class ZWQRMTOSAP_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZWQRMTOSAP");
    public final static QName ZWQRMTOSAPSOAP12 = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZWQRMTOSAP_SOAP12");
    public final static QName ZWQRMTOSAP = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZWQRMTOSAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/trunk/WQ_EJB_Quote/ejbModule/zwqrmtosap.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ZWQRMTOSAP_Service.class.getName())
                .log(java.util.logging.Level.WARNING, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/trunk/WQ_EJB_Quote/ejbModule/zwqrmtosap.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ZWQRMTOSAP_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ZWQRMTOSAP_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZWQRMTOSAP_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ZWQRMTOSAP_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ZWQRMTOSAP_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ZWQRMTOSAP_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ZWQRMTOSAP
     */
    @WebEndpoint(name = "ZWQRMTOSAP_SOAP12")
    public ZWQRMTOSAP getZWQRMTOSAPSOAP12() {
        return super.getPort(ZWQRMTOSAPSOAP12, ZWQRMTOSAP.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZWQRMTOSAP
     */
    @WebEndpoint(name = "ZWQRMTOSAP_SOAP12")
    public ZWQRMTOSAP getZWQRMTOSAPSOAP12(WebServiceFeature... features) {
        return super.getPort(ZWQRMTOSAPSOAP12, ZWQRMTOSAP.class, features);
    }
    /**
     *
     * @return
     *     returns ZWQRMTOSAP
     */
    @WebEndpoint(name = "ZWQRMTOSAP")
    public ZWQRMTOSAP getZWQRMTOSAP() {
        return super.getPort(ZWQRMTOSAP, ZWQRMTOSAP.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZWQRMTOSAP
     */
    @WebEndpoint(name = "ZWQRMTOSAP")
    public ZWQRMTOSAP getZWQRMTOSAP(WebServiceFeature... features) {
        return super.getPort(ZWQRMTOSAP, ZWQRMTOSAP.class, features);
    }

}
