ALTER TABLE Quote_item add 	"DESIGN_REGION" VARCHAR2(20);
ALTER TABLE Quote_item add 	"LAST_QC_IN_DATE" DATE;
ALTER TABLE Quote_item add 	"LAST_QC_OUT_DATE" DATE;
ALTER TABLE Quote_item add 	"LAST_SQ_IN_DATE" DATE;
ALTER TABLE Quote_item add 	"LAST_SQ_OUT_DATE" DATE;
ALTER TABLE Quote_item add 	"LAST_BMT_IN_DATE" DATE;
ALTER TABLE Quote_item add 	"LAST_BMT_OUT_DATE" DATE;
ALTER TABLE Quote_item add 	"LAST_UPDATED_BMT" VARCHAR2(20);
ALTER TABLE Quote_item add 	"LAST_BMT_UPDATE_TIME" DATE;
alter table quote_item add ATTACHMENT_FLAG char(5) default '00000' not null;


--ALTER TABLE Quote_item add 	CONSTRAINT "QUOTE_ITEM_FK1" FOREIGN KEY ("QUOTE_RELEASED_BY") REFERENCES "WEBQUOTE"."APP_USER" ("EMPLOYEE_ID") ENABLE;
ALTER TABLE Quote_item add 	CONSTRAINT "QUOTE_ITEM_FK2" FOREIGN KEY ("LAST_UPDATED_BMT") REFERENCES "WEBQUOTE"."APP_USER" ("EMPLOYEE_ID") ENABLE;

 
ALTER TABLE QUOTE add "DESIGN_REGION" VARCHAR2(20);  