CREATE TABLE TI_3A1_5D1_R1 (
  ID NUMBER(38,0) NOT NULL PRIMARY KEY,
  PO_NUM VARCHAR2(35) NOT NULL,
  PO_ITEM_NUM VARCHAR2(5) NOT NULL,
  QUOTE_NUM	VARCHAR2 (20 BYTE) NOT NULL,
  TI_QUOTE_NUM	VARCHAR2 (20 BYTE) NULL,
  TI_QUOTE_ITEM_NUM	VARCHAR2 (10 BYTE) NULL,
  TI_PART_NUM	VARCHAR2 (50 BYTE) NULL,
  MESG_TYPE	VARCHAR2 (10 BYTE) NOT NULL,
  STATUS	VARCHAR2 (20 BYTE) NULL,
  REASON	VARCHAR2 (250 BYTE) NULL,
  CREATED_DATE	TIMESTAMP (2) NOT NULL
  );

  CREATE TABLE TI_3A1_R2(
    ID NUMBER(38,0) NOT NULL PRIMARY KEY,
    PO_NUM VARCHAR2(35) NOT NULL Unique,
    PO_ITEM_NUM VARCHAR2(5) NOT NULL,
    QUOTE_NUM	VARCHAR2 (20 BYTE) NOT NULL,
    TI_QUOTE_NUM	VARCHAR2 (20 BYTE) NOT NULL,
    TI_QUOTE_ITEM_NUM	VARCHAR2 (10 BYTE) NOT NULL,
    TI_PART_NUM	VARCHAR2 (50 BYTE) NOT NULL,
    START_DATE  DATE NOT NULL,
    END_DATE  DATE NOT NULL,
    STATUS_DESC	VARCHAR2 (250 BYTE)	NULL,
    QTY	NUMBER (38,0)	NULL,
    STATUS	VARCHAR2 (20 BYTE)	NOT NULL,
    ZCPC	NUMBER (15,5)	  NULL,
    ZCPC_CURR	VARCHAR2 (10 BYTE)	NULL,
    OFFER_PRICE	NUMBER (15,5)	NULL,
    OFFER_PRICE_CURR	VARCHAR2 (10 BYTE)	NULL,
    RESALES_PRICE	NUMBER (15,5)	NULL,
    RESALES_PRICE_CURR	VARCHAR2 (10 BYTE)	NULL,
    CREATED_DATE	TIMESTAMP (2)	NOT NULL
  );
  
  CREATE TABLE TI_5D1_R2(
    ID NUMBER(38,0) NOT NULL PRIMARY KEY,
    PO_NUM VARCHAR2(35) NOT NULL Unique,
    PO_ITEM_NUM VARCHAR2(5) NOT NULL,
    QUOTE_NUM	VARCHAR2 (20 BYTE) NOT NULL,
    TI_QUOTE_NUM	VARCHAR2 (20 BYTE) NOT NULL,
    TI_QUOTE_ITEM_NUM	VARCHAR2 (10 BYTE) NOT NULL,
    TI_PART_NUM	VARCHAR2 (50 BYTE) NOT NULL,
    STATUS_DESC	VARCHAR2 (250 BYTE)	NULL,
    VALID_START_DATE	DATE	NULL,
    VALID_END_DATE	DATE	NULL,
    TI_AUTH_NUM	VARCHAR2 (20 BYTE)	NULL,
    AUTH_QTY	NUMBER (38,0)	NULL,
    OFFER_PRICE	NUMBER (15,5)	NULL,
    OFFER_PRICE_CURR VARCHAR2 (10 BYTE)	NULL,
    TI_COMMENT	VARCHAR2 (500 BYTE)	NULL,
    CREATED_DATE	TIMESTAMP (2)	NOT NULL
  );

  create table TI_3A1 (
ID NUMBER(38,0) NOT NULL PRIMARY KEY,
FILE_NAME VARCHAR(100) NOT NULL,
USER_NAME VARCHAR(100) ,
USER_EMAIL	VARCHAR2 (50),
USER_TEL	VARCHAR2 (20),
PO_NUM	VARCHAR2 (35) NOT NULL,
PO_LINE_ITEM	VARCHAR2 (5),
CONTRACT_QUOTE	VARCHAR2 (10),
CM_NAME	VARCHAR2 (50),
CM_AVNET_CUST_CODE	VARCHAR2 (10),
TI_EC_NUM	VARCHAR2 (10),
TI_SOLD_TO_NUM	VARCHAR2 (10),
CM_CITY	VARCHAR2 (20),
CM_COUNTRY_CODE	VARCHAR2 (5),
CM_POSTAL_CODE	VARCHAR2 (10),
UC_NAME	VARCHAR2 (50),
UC_AVNET_CUST_NO	VARCHAR2 (10),
EMSI_NUM	VARCHAR2 (10),
UC_CITY	VARCHAR2 (20),
UC_COUNTRY_CODE	VARCHAR2 (5),
UC_POSTAL_CODE	VARCHAR2 (10),
TI_PN	VARCHAR2 (50),
PN_CONTROLLED_ITEM	VARCHAR2 (10),
COMPETITOR_NAME	VARCHAR2 (50),
COMPETITOR_MATERIAL	VARCHAR2 (20),
COMPETITOR_CURRENCY	VARCHAR2 (10),
COMPETITOR_AMOUNT	VARCHAR2 (10),
REQUESTED_QUANTITY	VARCHAR2 (10),
UNIT_MEASUREMENT	VARCHAR2 (10),
ZCPR_CURRENCY	VARCHAR2 (10),
ZCPR_PRICE	VARCHAR2 (10),
ZCPC_CURRENCY	VARCHAR2 (10),
ZCPC_PRICE	VARCHAR2 (10),
COMMENTS	VARCHAR2 (500),
CREATED_DATE	TIMESTAMP(2),
UNIQUE(PO_NUM)
);
  CREATE TABLE TI_MESSAGE_LOG (
    ID NUMBER(38,0) NOT NULL PRIMARY KEY,
    PO_NUM VARCHAR2(35) NOT NULL ,
    READ_TI_MESG	CLOB	NULL,
    TI_MESG_FILE_NAME	VARCHAR2 (100 BYTE)	NOT NULL,
    MESG_TYPE	VARCHAR2 (10 BYTE)	NOT NULL,
    STATUS	VARCHAR2 (20 BYTE)	NOT NULL,
    CREATED_DATE	TIMESTAMP (2)	NOT NULL,
	ERROR_MESG VARCHAR2 (500 BYTE)	 NULL
    );
    --create index
    CREATE INDEX TI_3A1_5D1_R1_CO_INDEX1 ON TI_3A1_5D1_R1 (CREATED_DATE);
    CREATE INDEX TI_3A1_R2_CO_INDEX1 ON TI_3A1_R2 (CREATED_DATE);
    CREATE INDEX TI_5D1_R2_CO_INDEX1 ON TI_5D1_R2 (CREATED_DATE);
    CREATE INDEX TI_5D1_R2_TIPARTNUM_INDEX ON TI_5D1_R2(TI_PART_NUM);
CREATE INDEX TI_3A1_R2_TIPARTNUM_INDEX ON TI_3A1_R2(TI_PART_NUM);
CREATE INDEX TI_3A1_5D1_R1_TIPARTNUM_INDEX ON TI_3A1_5D1_R1(TI_PART_NUM);
CREATE INDEX TI_3A1_CREATEDDATE_INDEX ON TI_3A1(CREATED_DATE);
CREATE INDEX TI_3A1_5D1_R1_PO_NUM_INDEX ON TI_3A1_5D1_R1(PO_NUM);
 
   --mail when error 
 INSERT INTO APP_PROPERTY(
        PROP_RESERVED,
        PROP_KEY,
        PROP_VALUE) 
VALUES(1,'TI_RECIEVER_EMAILS','Ivy.Yap@AVNET.COM;David.Zheng@AVNET.COM;Shary.Su@AVNET.COM;Dennis.Soh@AVNET.COM;');
-- create new function 
INSERT INTO  APP_FUNCTION(ID,NAME) VALUES((SELECT MAX(ID) FROM APP_FUNCTION)+1 ,'TI Quote Response');
commit;
-- create page and the fuction relation
INSERT INTO APP_RESOURCE(ID,RESOURCE_TYPE,PATH,APP_FUNCTION_ID,Version,Path_Order) 
VALUES((SELECT MAX(ID) FROM APP_RESOURCE)+1,'SCREEN','/Report/TiLoadPage.jsf',
(SELECT ID FROM APP_FUNCTION where name ='TI Quote Response'),1,1);
commit;
-- create  wq.label.tiQuoteResponse and messages
Insert into APP_LABEL (ID,LOCALE_ID,MESSAGE_CODE,MESSAGE) values ((select max(id)+1 from APP_LABEL),
'en','wq.label.tiQuoteResponse','TI Quote Response');
--mesgs
Insert into APP_LABEL (ID,LOCALE_ID,MESSAGE_CODE,MESSAGE) values ((select max(id)+1 from APP_LABEL),
'en','wq.label.timesgtype','Message Type');
Insert into APP_LABEL (ID,LOCALE_ID,MESSAGE_CODE,MESSAGE) values ((select max(id)+1 from APP_LABEL),
'en','wq.label.tiponumber','Po Number');
Insert into APP_LABEL (ID,LOCALE_ID,MESSAGE_CODE,MESSAGE) values ((select max(id)+1 from APP_LABEL),
'en','wq.label.tiquotenumber','Quote Number');
Insert into APP_LABEL (ID,LOCALE_ID,MESSAGE_CODE,MESSAGE) values ((select max(id)+1 from APP_LABEL),
'en','wq.label.tipartnumber','TI Part Number');
Insert into APP_LABEL (ID,LOCALE_ID,MESSAGE_CODE,MESSAGE) values ((select max(id)+1 from APP_LABEL),
'en','wq.label.tidatefrom','Date From');
Insert into APP_LABEL (ID,LOCALE_ID,MESSAGE_CODE,MESSAGE) values ((select max(id)+1 from APP_LABEL),
'en','wq.label.tidateto','Date To');
--messages
Insert into APP_MESSAGES (ID,LOCALE_ID,MESSAGE_CODE,MESSAGE) values ((select max(id)+1 from APP_MESSAGES),
'en','wq.message.tidatetoblank',' [Date To] Should not be blank.');
Insert into APP_MESSAGES (ID,LOCALE_ID,MESSAGE_CODE,MESSAGE) values ((select max(id)+1 from APP_MESSAGES),
'en','wq.message.tidateafterfrom',' [Date To] should be after [Date From].');
Insert into APP_MESSAGES (ID,LOCALE_ID,MESSAGE_CODE,MESSAGE) values ((select max(id)+1 from APP_MESSAGES),
'en','wq.message.tisepcialchar',' [Po Number] should not be contain [*] or [#].');
Insert into APP_MESSAGES (ID,LOCALE_ID,MESSAGE_CODE,MESSAGE) values ((select max(id)+1 from APP_MESSAGES),
'en','wq.message.tiqnumsepcialchar',' [Quote Number] should not be contain [*] or [#].');
Insert into APP_MESSAGES (ID,LOCALE_ID,MESSAGE_CODE,MESSAGE) values ((select max(id)+1 from APP_MESSAGES),
'en','wq.message.tidownloaderr',' download error!');
-- CREATE ROLE ROLE_VENDOR_QUOTE_TI
INSERT INTO "WEBQUOTE"."ROLE" (ID,CREATED_ON,"VERSION","NAME",CREATED_BY, LAST_UDPATED_BY,ACTIVE,DESCRIPTION)
VALUES((SELECT MAX(ID) + 1 FROM ROLE), sysdate, 1, 'ROLE_VENDOR_QUOTE_TI', (SELECT ID FROM APP_USER WHERE EMPLOYEE_ID = '044878')
, null,1,'CREATE FOR TI B2B project');

INSERT INTO APP_FUNCTION_ROLE_MAPPING (FUNCTION_ID,ROLE_ID) 
	VALUES((SELECT ID FROM APP_FUNCTION WHERE NAME ='TI Quote Response'), 
	(SELECT ID FROM ROLE WHERE NAME ='ROLE_VENDOR_QUOTE_TI'));
COMMIT;

--insert into APP_PROPERTY(prop_key,prop_desc,prop_value,prop_reserved)  values ('TIS_FILE_DIR_INBOUND',null,'/app/eap62/webquote/b2bfiles/TIS/inbound',1);
--insert into APP_PROPERTY(prop_key,prop_desc,prop_value,prop_reserved)  values ('TIS_FILE_DIR_EXCEPTION',null,'/app/eap62/webquote/b2bfiles/TIS/exception',1);
--insert into APP_PROPERTY(prop_key,prop_desc,prop_value,prop_reserved)  values ('TIS_FILE_DIR_BACKUP',null,'/app/eap62/webquote/b2bfiles/TIS/backup',1);

UPDATE APP_LABEL SET MESSAGE = substr(MESSAGE, 0, length(MESSAGE)-1)||'3'  WHERE MESSAGE_CODE = 'wq.title.webQuoteVersion' ;
COMMIT;

UPDATE "APP_FUNCTION" SET NAME = 'CataLogMaintain' WHERE name ='CatalogMaintain';
Insert into app_resource(RESOURCE_TYPE,ID,PATH,APP_FUNCTION_ID,PATH_ORDER,VERSION)
values ('SCREEN',WQ_SEQ.NEXTVAL,'/WebPromo/CataLogMaintain.jsf',(select t.id from app_function t 
where t.NAME='CataLogMaintain'),1,1); 
COMMIT;

