alter table program_type drop CONSTRAINT "PROGRAM_TYPE_BIZ_UNIT_FK1";
alter table program_type drop CONSTRAINT "PROGRAM_TYPE_UK1";
alter table program_type drop column BIZ_UNIT_ID;
alter table program_type  ADD CONSTRAINT  "PROGRAM_TYPE_UK1" UNIQUE ("NAME");
ALTER TABLE MATERIAL_DETAIL DROP CONSTRAINT "MATERIAL_DETAIL_UK1" ;
ALTER TABLE  MATERIAL_DETAIL ADD CONSTRAINT "MATERIAL_DETAIL_UK1" UNIQUE ("MATERIAL_ID","PROGRAM_TYPE_ID", "COST_INDICATOR", "SALES_ORG", "PLANT_ID", "BIZ_UNIT", "MATERIAL_CATEGORY");
