--------------------------------------------------------
--  DDL for Table APP_LABEL
--------------------------------------------------------

  CREATE TABLE "APP_LABEL" 
   (	"ID" NUMBER(*,0), 
	"LOCALE_ID" VARCHAR2(5 BYTE), 
	"MESSAGE_CODE" VARCHAR2(60 BYTE), 
	"MESSAGE" NVARCHAR2(512)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 0 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WEBQUOTE_01" ;
REM INSERTING into WEBQUOTE.APP_LABEL
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index APP_LABEL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "APP_LABEL_PK" ON "APP_LABEL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 0 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WEBQUOTE_01" ;
--------------------------------------------------------
--  DDL for Index APP_LABEL_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "APP_LABEL_UK1" ON "APP_LABEL" ("LOCALE_ID", "MESSAGE_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 0 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WEBQUOTE_01" ;
--------------------------------------------------------
--  Constraints for Table APP_LABEL
--------------------------------------------------------

  ALTER TABLE "APP_LABEL" ADD CONSTRAINT "APP_LABEL_UK1" UNIQUE ("LOCALE_ID", "MESSAGE_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 0 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WEBQUOTE_01"  ENABLE;
  ALTER TABLE "APP_LABEL" ADD CONSTRAINT "APP_LABEL_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 0 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WEBQUOTE_01"  ENABLE;
  ALTER TABLE "APP_LABEL" MODIFY ("MESSAGE_CODE" NOT NULL ENABLE);
  ALTER TABLE "APP_LABEL" MODIFY ("LOCALE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table APP_MESSAGES
--------------------------------------------------------

  ALTER TABLE "APP_LABEL" ADD CONSTRAINT "APP_LABEL_FK1" FOREIGN KEY ("LOCALE_ID")
	  REFERENCES "LOCALE_MASTER" ("LOCALE_ID") ENABLE;
--------------------------------------------------------
--  DDL for Trigger APP_MESSAGES_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APP_LABEL_TRG" 
BEFORE INSERT ON APP_LABEL 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT APP_LABEL_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "APP_LABEL_TRG" ENABLE;


--------------------------------------------------------
--  DDL for Trigger APP_LABEL_SEQ
--------------------------------------------------------

 CREATE SEQUENCE  "APP_LABEL_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
 
 
 
 --------------------------------------------------------
--  DDL for Table APP_MESSAGES
--------------------------------------------------------


--------------------------------------------------------
--  DDL for DROP TABLE INDEX AND CONSTRAINT
--------------------------------------------------------
DROP TABLE APP_MESSAGES PURGE;
ALTER TABLE APP_MESSAGES DROP CONSTRAINT APP_MESSAGES_PK;
ALTER TABLE APP_MESSAGES DROP CONSTRAINT APP_MESSAGES_UK;
DROP sequence APP_MESSAGES_SEQ;
DROP TRIGGER APP_MESSAGES_TRG;


  CREATE TABLE "APP_MESSAGES" 
   (	"ID" NUMBER(*,0), 
	"LOCALE_ID" VARCHAR2(5 BYTE), 
	"MESSAGE_CODE" VARCHAR2(60 BYTE), 
	"MESSAGE" NVARCHAR2(512)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 0 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WEBQUOTE_01" ;
REM INSERTING into WEBQUOTE.APP_MESSAGES
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index APP_MESSAGES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "APP_MESSAGES_PK" ON "APP_MESSAGES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 0 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WEBQUOTE_01" ;
--------------------------------------------------------
--  DDL for Index APP_MESSAGES_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "APP_MESSAGES_UK" ON "APP_MESSAGES" ("LOCALE_ID", "MESSAGE_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 0 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WEBQUOTE_01" ;
--------------------------------------------------------
--  Constraints for Table APP_MESSAGES
--------------------------------------------------------

  ALTER TABLE "APP_MESSAGES" ADD CONSTRAINT "APP_MESSAGES_UK" UNIQUE ("LOCALE_ID", "MESSAGE_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 0 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WEBQUOTE_01"  ENABLE;
  ALTER TABLE "APP_MESSAGES" ADD CONSTRAINT "APP_MESSAGES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 0 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WEBQUOTE_01"  ENABLE;
  ALTER TABLE "APP_MESSAGES" MODIFY ("MESSAGE_CODE" NOT NULL ENABLE);
  ALTER TABLE "APP_MESSAGES" MODIFY ("LOCALE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table APP_MESSAGES
--------------------------------------------------------

  ALTER TABLE "APP_MESSAGES" ADD CONSTRAINT "APP_MESSAGES_FK" FOREIGN KEY ("LOCALE_ID")
	  REFERENCES "LOCALE_MASTER" ("LOCALE_ID") ENABLE;
--------------------------------------------------------
--  DDL for Trigger APP_MESSAGES_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APP_MESSAGES_TRG" 
BEFORE INSERT ON APP_MESSAGES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT APP_MESSAGES_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "APP_MESSAGES_TRG" ENABLE;


--------------------------------------------------------
--  DDL for Trigger APP_MESSAGES_SEQ
--------------------------------------------------------

 CREATE SEQUENCE  "APP_MESSAGES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;

