CREATE TABLE "WEBQUOTE"."SAP_PCN_MATERIAL"
    (
      "MATNR"        VARCHAR2(100 BYTE) NOT NULL,
      "MTART"        VARCHAR2(100 BYTE),
      "LVORM"        VARCHAR2(100 BYTE),
      "MSTAV"        VARCHAR2(100 BYTE),
      "MFRNR"        VARCHAR2(100 BYTE),
      "MFRPN"        VARCHAR2(100 BYTE),
      "MAKTX"        VARCHAR2(100 BYTE),
      "ZZPROD_CAT"   VARCHAR2(100 BYTE),
      "PRDHA"        VARCHAR2(100 BYTE),
      "ZZCMC_KEY"    VARCHAR2(100 BYTE),
	  "ZZCOMM"       VARCHAR2(100 BYTE),
      "VERSION"      NUMBER,
      "CREATED_BY"   VARCHAR2(50 BYTE) DEFAULT 'system' NOT NULL,
      "CREATE_DATE" DATE DEFAULT sysdate NOT NULL,
      "UPDATED_BY"   VARCHAR2(50 BYTE) DEFAULT 'system' NOT NULL,
      "UPDATE_DATE" DATE DEFAULT sysdate NOT NULL,
      CONSTRAINT "SAP_PCN_MATERIAL_PK1" PRIMARY KEY ("MATNR")
    );
CREATE INDEX "WEBQUOTE"."SAP_PCN_MATERIAL_MFRNR_ID1" ON "WEBQUOTE"."SAP_PCN_MATERIAL"
    (
      "MFRNR"
    );
CREATE INDEX "WEBQUOTE"."SAP_PCN_MATERIAL_MFRPN_ID2" ON "WEBQUOTE"."SAP_PCN_MATERIAL"
    (
      "MFRPN"
    ); 