CREATE TABLE PG_MASTER_MAPPING 
(
  ID NUMBER NOT NULL 
, BIZ_UNIT VARCHAR2(10) NOT NULL 
, MANUFACTURER_ID NUMBER NOT NULL 
, CONSTRAINT PG_MASTER_MAPPING_PK PRIMARY KEY 
  (
    ID 
  ), CONSTRAINT "PG_MASTER_MAPPING_UK1" UNIQUE ("BIZ_UNIT", "MANUFACTURER_ID")

  ENABLE 
);
