//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.13 at 03:43:24 PM CST 
//


package com.avnet.emasia.webquote.dp.xml.requestquote;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="headerErrorCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="headerErrorDesc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="lineErrorCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="lineErrorDesc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="lineItemNum" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="operation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="quoteId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="referenceId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="referenceLineId" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="responseCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="responseDesc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "headerErrorCode",
    "headerErrorDesc",
    "lineErrorCode",
    "lineErrorDesc",
    "lineItemNum",
    "operation",
    "quoteId",
    "referenceId",
    "referenceLineId",
    "responseCode",
    "responseDesc"
})
@XmlRootElement(name = "WebResponseObject")
public class WebResponseObject {

    @XmlElementRef(name = "headerErrorCode", namespace = "http://remoting.qrt.avnet.com", type = JAXBElement.class, required = false)
    protected JAXBElement<String> headerErrorCode;
    @XmlElementRef(name = "headerErrorDesc", namespace = "http://remoting.qrt.avnet.com", type = JAXBElement.class, required = false)
    protected JAXBElement<String> headerErrorDesc;
    @XmlElementRef(name = "lineErrorCode", namespace = "http://remoting.qrt.avnet.com", type = JAXBElement.class, required = false)
    protected JAXBElement<String> lineErrorCode;
    @XmlElementRef(name = "lineErrorDesc", namespace = "http://remoting.qrt.avnet.com", type = JAXBElement.class, required = false)
    protected JAXBElement<String> lineErrorDesc;
    @XmlElement(nillable = true)
    protected List<String> lineItemNum;
    @XmlElementRef(name = "operation", namespace = "http://remoting.qrt.avnet.com", type = JAXBElement.class, required = false)
    protected JAXBElement<String> operation;
    @XmlElementRef(name = "quoteId", namespace = "http://remoting.qrt.avnet.com", type = JAXBElement.class, required = false)
    protected JAXBElement<String> quoteId;
    @XmlElementRef(name = "referenceId", namespace = "http://remoting.qrt.avnet.com", type = JAXBElement.class, required = false)
    protected JAXBElement<String> referenceId;
    @XmlElement(nillable = true)
    protected List<String> referenceLineId;
    @XmlElementRef(name = "responseCode", namespace = "http://remoting.qrt.avnet.com", type = JAXBElement.class, required = false)
    protected JAXBElement<String> responseCode;
    @XmlElementRef(name = "responseDesc", namespace = "http://remoting.qrt.avnet.com", type = JAXBElement.class, required = false)
    protected JAXBElement<String> responseDesc;

    /**
     * Gets the value of the headerErrorCode property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getHeaderErrorCode() {
        return headerErrorCode;
    }

    /**
     * Sets the value of the headerErrorCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setHeaderErrorCode(JAXBElement<String> value) {
        this.headerErrorCode = value;
    }

    /**
     * Gets the value of the headerErrorDesc property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getHeaderErrorDesc() {
        return headerErrorDesc;
    }

    /**
     * Sets the value of the headerErrorDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setHeaderErrorDesc(JAXBElement<String> value) {
        this.headerErrorDesc = value;
    }

    /**
     * Gets the value of the lineErrorCode property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getLineErrorCode() {
        return lineErrorCode;
    }

    /**
     * Sets the value of the lineErrorCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setLineErrorCode(JAXBElement<String> value) {
        this.lineErrorCode = value;
    }

    /**
     * Gets the value of the lineErrorDesc property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getLineErrorDesc() {
        return lineErrorDesc;
    }

    /**
     * Sets the value of the lineErrorDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setLineErrorDesc(JAXBElement<String> value) {
        this.lineErrorDesc = value;
    }

    /**
     * Gets the value of the lineItemNum property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lineItemNum property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLineItemNum().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getLineItemNum() {
        if (lineItemNum == null) {
            lineItemNum = new ArrayList<String>();
        }
        return this.lineItemNum;
    }

    /**
     * Gets the value of the operation property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getOperation() {
        return operation;
    }

    /**
     * Sets the value of the operation property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setOperation(JAXBElement<String> value) {
        this.operation = value;
    }

    /**
     * Gets the value of the quoteId property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getQuoteId() {
        return quoteId;
    }

    /**
     * Sets the value of the quoteId property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setQuoteId(JAXBElement<String> value) {
        this.quoteId = value;
    }

    /**
     * Gets the value of the referenceId property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getReferenceId() {
        return referenceId;
    }

    /**
     * Sets the value of the referenceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setReferenceId(JAXBElement<String> value) {
        this.referenceId = value;
    }

    /**
     * Gets the value of the referenceLineId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the referenceLineId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReferenceLineId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getReferenceLineId() {
        if (referenceLineId == null) {
            referenceLineId = new ArrayList<String>();
        }
        return this.referenceLineId;
    }

    /**
     * Gets the value of the responseCode property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getResponseCode() {
        return responseCode;
    }

    /**
     * Sets the value of the responseCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setResponseCode(JAXBElement<String> value) {
        this.responseCode = value;
    }

    /**
     * Gets the value of the responseDesc property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getResponseDesc() {
        return responseDesc;
    }

    /**
     * Sets the value of the responseDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setResponseDesc(JAXBElement<String> value) {
        this.responseDesc = value;
    }

}
