---UPDATE QUOTE_ITEM SET BUY_CURR='USD' WHERE BUY_CURR IS NULL;
---UPDATE QUOTE_ITEM SET RFQ_CURR='USD' WHERE RFQ_CURR IS NULL;
---UPDATE QUOTE_ITEM SET EX_RATE_BUY=1;
---UPDATE QUOTE_ITEM SET EX_RATE_RFQ=1;
---UPDATE QUOTE_ITEM SET HANDLING=1;
---UPDATE QUOTE_ITEM SET VAT=1;
---UPDATE QUOTE_ITEM SET EX_RATE_FNL=1 WHERE t.FINAL_QUOTATION_PRICE is not null;

---COMMIT;

--moved to 008.sql by damon
