drop view QUOTE_ITEM_VIEW;

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "WEBQUOTE"."QUOTE_ITEM_VIEW" ("BIZ_UNIT", "FORM_NUMBER", "USER_ID", "SOLD_2_CUST_NAME", "SOLD_2_CUST_NO", "TEAM_ID", "YOUR_REFERENCE", "AQCC", "BOM_NUMBER"
  , "COST_INDICATOR", "CUSTOMER_TYPE", "DESIGN_IN_CAT", "DESIGN_LOCATION", "DESIGN_REGION", "END_CUST_NO", "END_CUST_NAME", "ENQ_SEGMENT", "FIRST_RFQ_CODE", "FIS_MTH", "FIS_QTR", "FIS_YEAR"
  , "ID", "INT_COMMENT", "INT_TRF_COMMENT", "LAST_BMT_I_DATE", "LAST_BMT_O_DATE", "LAST_IT_UP_TIME", "LAST_QC_I_DATE", "LAST_QC_O_DATE", "LAST_RIT_UP_TIME", "LAST_SQ_I_DATE", "LAST_SQ_O_DATE"
  , "LAST_UP_BMT_EID", "LAST_UP_PM_EID", "LAST_UP_QC_EID", "PRODUCT_GROUP1_ID", "PRODUCT_GROUP2_ID", "PROD_GRP3", "PROD_GRP4", "QUOTE_NUMBER", "QUOTE_TYPE", "QUOTED_PART_NUM"
  , "QUOTED_QTY", "REQ_MFR_ID", "REQ_PART_NUM", "REQ_QTY", "REVERT_VER", "SENT_O_TIME", "STAGE", "STATUS", "SUBMISSION_DATE", "DELTA_DATE", "PROGRAM_TYPE", "MATERIAL_TYPE_ID", "QUOTATION_EFFECTIVE_DATE", "PRICE_VALIDITY", "PO_EXPIRY_DATE"
  , "RESALE_MARGIN", "QUOTE_EXPIRY_DATE", "SHIPMENT_VALIDITY", "DR_NEDA_ID", "DR_EXPIRY_DATE", "PROJECT_NAME", "APPLICATION", "SUPPLIER_DR_NUMBER", "VENDOR_DEBIT_NUMBER", "VENDOR_QUOTE_NUMBER"
  , "VENDOR_QUOTE_QTY", "PP_SCHEDULE", "MP_SCHEDULE", "LOA_FLAG", "EAU", "COMPETITOR_INFORMATION", "REMARKS", "REASON_FOR_REFRESH", "CREATED_BY", "LAST_UPDATED_BY", "PRODUCT_GROUP2"
  , "MFR_NAME", "SAP_PART_NUMBER", "SALES_NAME", "SALES_EID", "SPR_FLAG", "QUOTED_BY", "SOLD_2_CUST_NAME_CHINESE", "PMOQ", "MPQ", "MOQ", "MOV", "LEAD_TIME"
  , "MULTI_USAGE_FLAG", "QTY_INDICATOR", "RESALE_INDICATOR", "RESALE_MAX", "RESALE_MIN", "RESCHEDULE_WINDOW", "CANCELLATION_WINDOW", "TERMS_AND_CONDITIONS", "ALLOCATION_FLAG"
  , "SHIP_2_CUST_NAME", "SHIP_2_CUST_NO", "AUTH_GP", "AUTH_GP_REASON_DESC", "ATTACHMENT_FLAG"
  , "SALES_COST_TYPE", "SALES_COST_FLAG", "CUSTOMER_GROUP_ID"
  , "SALES_COST", "SUGGESTED_RESALE", "COST", "QUOTED_PRICE", "FINAL_QUOTATION_PRICE", "TARGET_RESALE", "REF_EX_RATE", "REF_EX_CURR"
  ) AS 
  SELECT 
 UPPER(QUOTE.BIZ_UNIT) AS BIZ_UNIT
,UPPER(QUOTE.FORM_NUMBER) AS FORM_NUMBER
,QUOTE.SALES_USER_ID AS USER_ID
,UPPER(QUOTE.SOLD_TO_CUSTOMER_NAME) AS SOLD_2_CUST_NAME
,UPPER(QUOTE.SOLD_TO_CUSTOMER_NUMBER) AS SOLD_2_CUST_NO
,UPPER(QUOTE.TEAM_ID) AS TEAM_ID
,UPPER(QUOTE.YOUR_REFERENCE) AS YOUR_REFERENCE
,UPPER(QUOTE_ITEM.AQCC) AS AQCC
,UPPER(QUOTE_ITEM.BOM_NUMBER) AS BOM_NUMBER
,UPPER(QUOTE_ITEM.COST_INDICATOR) AS COST_INDICATOR
,UPPER(QUOTE_ITEM.CUSTOMER_TYPE) AS CUSTOMER_TYPE
,UPPER(QUOTE_ITEM.DESIGN_IN_CAT) AS DESIGN_IN_CAT
,UPPER(QUOTE_ITEM.DESIGN_LOCATION) AS DESIGN_LOCATION
,UPPER(QUOTE_ITEM.DESIGN_REGION) AS DESIGN_REGION
,UPPER(QUOTE_ITEM.END_CUSTOMER_NUMBER) AS END_CUST_NO
,UPPER(QUOTE_ITEM.END_CUSTOMER_NAME) AS END_CUST_NAME
,UPPER(QUOTE_ITEM.ENQUIRY_SEGMENT) AS ENQ_SEGMENT
,UPPER(QUOTE_ITEM.FIRST_RFQ_CODE) AS FIRST_RFQ_CODE
,UPPER(QUOTE_ITEM.FIS_MTH) AS FIS_MTH
,UPPER(QUOTE_ITEM.FIS_QTR) AS FIS_QTR
,UPPER(QUOTE_ITEM.FIS_YEAR) AS FIS_YEAR
,QUOTE_ITEM.ID AS ID
,UPPER(QUOTE_ITEM.INTERNAL_COMMENT) AS INT_COMMENT
,UPPER(QUOTE_ITEM.INTERNAL_TRANSFER_COMMENT) AS INT_TRF_COMMENT
,TO_CHAR(QUOTE_ITEM.LAST_BMT_IN_DATE, 'YYYYMMDDHH24MISS') AS LAST_BMT_I_DATE
,TO_CHAR(QUOTE_ITEM.LAST_BMT_OUT_DATE, 'YYYYMMDDHH24MISS') AS LAST_BMT_O_DATE
,TO_CHAR(QUOTE_ITEM.LAST_IT_UPDATE_TIME, 'YYYYMMDDHH24MISS') AS LAST_IT_UP_TIME
,TO_CHAR(QUOTE_ITEM.LAST_QC_IN_DATE, 'YYYYMMDDHH24MISS') AS LAST_QC_I_DATE
,TO_CHAR(QUOTE_ITEM.LAST_QC_OUT_DATE, 'YYYYMMDDHH24MISS') AS LAST_QC_O_DATE
,TO_CHAR(QUOTE_ITEM.LAST_RIT_UPDATE_TIME, 'YYYYMMDDHH24MISS') AS LAST_RIT_UP_TIME
,TO_CHAR(QUOTE_ITEM.LAST_SQ_IN_DATE, 'YYYYMMDDHH24MISS') AS LAST_SQ_I_DATE
,TO_CHAR(QUOTE_ITEM.LAST_SQ_OUT_DATE, 'YYYYMMDDHH24MISS') AS LAST_SQ_O_DATE
,UPPER(QUOTE_ITEM.LAST_UPDATED_BMT) AS LAST_UP_BMT_EID
,UPPER(QUOTE_ITEM.LAST_UPDATED_PM) AS LAST_UP_PM_EID
,UPPER(QUOTE_ITEM.LAST_UPDATED_QC) AS LAST_UP_QC_EID
,QUOTE_ITEM.PRODUCT_GROUP1_ID
,QUOTE_ITEM.PRODUCT_GROUP2_ID
,UPPER(QUOTE_ITEM.PRODUCT_GROUP3) AS PROD_GRP3
,UPPER(QUOTE_ITEM.PRODUCT_GROUP4) AS PROD_GRP4
,UPPER(QUOTE_ITEM.QUOTE_NUMBER) AS QUOTE_NUMBER
,UPPER(QUOTE_ITEM.QUOTE_TYPE) AS QUOTE_TYPE
,UPPER(QUOTE_ITEM.QUOTED_PART_NUMBER) AS QUOTED_PART_NUM
,QUOTE_ITEM.QUOTED_QTY AS QUOTED_QTY
,QUOTE_ITEM.REQUESTED_MFR_ID AS REQ_MFR_ID
,UPPER(QUOTE_ITEM.REQUESTED_PART_NUMBER) AS REQ_PART_NUM
,QUOTE_ITEM.REQUESTED_QTY AS REQ_QTY
,UPPER(QUOTE_ITEM.REVERT_VERSION) AS REVERT_VER
,TO_CHAR(QUOTE_ITEM.SENT_OUT_TIME, 'YYYYMMDDHH24MISS') AS SENT_O_TIME
,UPPER(QUOTE_ITEM.STAGE) AS STAGE
,UPPER(QUOTE_ITEM.STATUS) AS STATUS
,TO_CHAR(QUOTE_ITEM.SUBMISSION_DATE, 'YYYYMMDDHH24MISS') AS SUBMISSION_DATE
,TO_CHAR(NVL(QUOTE_ITEM.LAST_UPDATED_ON,QUOTE.CREATED_ON), 'YYYYMMDD') AS DELTA_DATE
,QUOTE_ITEM.PROGRAM_TYPE AS PROGRAM_TYPE
,UPPER(QUOTE_ITEM.MATERIAL_TYPE_ID) AS MATERIAL_TYPE_ID
-- *** GSB: BW Hit Rate Report @ 05-01-2017 
,TO_CHAR(QUOTE_ITEM.QUOTATION_EFFECTIVE_DATE, 'YYYYMMDDHH24MISS') AS QUOTATION_EFFECTIVE_DATE
,UPPER(QUOTE_ITEM.PRICE_VALIDITY) AS PRICE_VALIDITY
,TO_CHAR(QUOTE_ITEM.PO_EXPIRY_DATE, 'YYYYMMDD') AS PO_EXPIRY_DATE
-- MS: Added new fields for SR103916 @ 21-03-2017
,QUOTE_ITEM.RESALE_MARGIN AS RESALE_MARGIN
,TO_CHAR(QUOTE_ITEM.QUOTE_EXPIRY_DATE, 'YYYYMMDDHH24MISS') AS QUOTE_EXPIRY_DATE
,TO_CHAR(QUOTE_ITEM.SHIPMENT_VALIDITY, 'YYYYMMDDHH24MISS') AS SHIPMENT_VALIDITY
,QUOTE_ITEM.DR_NEDA_ID AS DR_NEDA_ID
,TO_CHAR(QUOTE_ITEM.DR_EXPIRY_DATE, 'YYYYMMDDHH24MISS') AS DR_EXPIRY_DATE
,UPPER(QUOTE_ITEM.PROJECT_NAME) AS PROJECT_NAME
,UPPER(QUOTE_ITEM.APPLICATION) AS APPLICATION
,UPPER(QUOTE_ITEM.SUPPLIER_DR_NUMBER) AS SUPPLIER_DR_NUMBER
,UPPER(QUOTE_ITEM.VENDOR_DEBIT_NUMBER) AS VENDOR_DEBIT_NUMBER
,UPPER(QUOTE_ITEM.VENDOR_QUOTE_NUMBER) AS VENDOR_QUOTE_NUMBER
,QUOTE_ITEM.VENDOR_QUOTE_QTY AS VENDOR_QUOTE_QTY
,UPPER(QUOTE_ITEM.PP_SCHEDULE) AS PP_SCHEDULE
,UPPER(QUOTE_ITEM.MP_SCHEDULE) AS MP_SCHEDULE
,QUOTE_ITEM.LOA_FLAG AS LOA_FLAG
,QUOTE_ITEM.EAU AS EAU
,UPPER(QUOTE_ITEM.COMPETITOR_INFORMATION) AS COMPETITOR_INFORMATION
,UPPER(QUOTE_ITEM.REMARKS) AS REMARKS
,UPPER(QUOTE_ITEM.REASON_FOR_REFRESH) AS REASON_FOR_REFRESH
,QUOTE.CREATED_BY AS CREATED_BY
,QUOTE_ITEM.LAST_UPDATED_BY AS LAST_UPDATED_BY
-- MS: Added new fields for SR104294 @ 28-11-2017
,UPPER(PRODUCT_GROUP.NAME) AS PRODUCT_GROUP2
,UPPER(MANUFACTURER.NAME) AS MFR_NAME
,UPPER(QUOTE_ITEM.SAP_PART_NUMBER) AS SAP_PART_NUMBER
,au1.NAME AS SALES_NAME
,au1.EMPLOYEE_ID AS SALES_EID
,QUOTE_ITEM.SPR_FLAG AS SPR_FLAG
,au2.NAME AS QUOTED_BY
,UPPER(QUOTE.SOLD_TO_CUSTOMER_NAME_CHINESE) AS SOLD_2_CUST_NAME_CHINESE
,QUOTE_ITEM.PMOQ AS PMOQ
,QUOTE_ITEM.MPQ AS MPQ
,QUOTE_ITEM.MOQ AS MOQ
,QUOTE_ITEM.MOV AS MOV
,UPPER(QUOTE_ITEM.LEAD_TIME) AS LEAD_TIME
,QUOTE_ITEM.MULTI_USAGE_FLAG AS MULTI_USAGE_FLAG
,UPPER(QUOTE_ITEM.QTY_INDICATOR) AS QTY_INDICATOR
,UPPER(QUOTE_ITEM.RESALE_INDICATOR) AS RESALE_INDICATOR
,QUOTE_ITEM.RESALE_MAX AS RESALE_MAX
,QUOTE_ITEM.RESALE_MIN AS RESALE_MIN
,QUOTE_ITEM.RESCHEDULE_WINDOW AS RESCHEDULE_WINDOW
,QUOTE_ITEM.CANCELLATION_WINDOW AS CANCELLATION_WINDOW
,UPPER(QUOTE_ITEM.TERMS_AND_CONDITIONS) AS TERMS_AND_CONDITIONS
,QUOTE_ITEM.ALLOCATION_FLAG AS ALLOCATION_FLAG
,UPPER(QUOTE_ITEM.SHIP_TO_CUSTOMER_NAME) AS SHIP_2_CUST_NAME
,UPPER(QUOTE_ITEM.SHIP_TO_CUSTOMER_NUMBER) AS SHIP_2_CUST_NO
,QUOTE_ITEM.AUTH_GP AS AUTH_GP
,UPPER(QUOTE_ITEM.AUTH_GP_REASON_DESC) AS AUTH_GP_REASON_DESC
,SIGN(QUOTE_ITEM.ATTACHMENT_FLAG) AS ATTACHMENT_FLAG
---------------------------------------------------
-- MS: Added new fields on 2018-07-26 for SR104761
--,QUOTE_ITEM.SALES_COST AS SALES_COST
--,QUOTE_ITEM.SUGGESTED_RESALE AS SUGGESTED_RESALE
,QUOTE_ITEM.SALES_COST_TYPE AS SALES_COST_TYPE
,QUOTE_ITEM.SALES_COST_FLAG AS SALES_COST_FLAG
,QUOTE_ITEM.CUSTOMER_GROUP_ID AS CUSTOMER_GROUP_ID
---------------------------------------------------
-- GSB: MultiCurrency (Pricing in USD) @ 06-12-2018
--,(QUOTE_ITEM.EX_RATE_TO*QUOTE_ITEM.HANDLING*QUOTE_ITEM.VAT) AS REF_EX_RATE
--,QUOTE_ITEM.CURR_TO AS REF_EX_CURR
,CAST(ROUND(QUOTE_ITEM.SALES_COST/QUOTE_ITEM.EX_RATE_BUY,5) AS NUMBER(15,5)) SALES_COST
,CAST(ROUND(QUOTE_ITEM.SUGGESTED_RESALE/QUOTE_ITEM.EX_RATE_BUY,5) AS NUMBER(15,5)) SUGGESTED_RESALE
,CAST(ROUND(QUOTE_ITEM.COST/QUOTE_ITEM.EX_RATE_BUY,5) AS NUMBER(15,5)) COST
,CAST(ROUND(QUOTE_ITEM.QUOTED_PRICE/QUOTE_ITEM.EX_RATE_BUY,5) AS NUMBER(20,10)) QUOTED_PRICE
,CAST(ROUND(QUOTE_ITEM.FINAL_QUOTATION_PRICE/QUOTE_ITEM.EX_RATE_FNL,5) AS NUMBER(15,5)) FINAL_QUOTATION_PRICE
,CAST(ROUND(QUOTE_ITEM.TARGET_RESALE/QUOTE_ITEM.EX_RATE_RFQ,5) AS NUMBER(15,5)) TARGET_RESALE
,CAST(ROUND(QUOTE_ITEM.EX_RATE_RFQ * QUOTE_ITEM.HANDLING,5) AS NUMBER(12,5)) REF_EX_RATE 
,QUOTE_ITEM.RFQ_CURR AS REF_EX_CURR
---------------------------------------------------
FROM QUOTE_ITEM
LEFT JOIN QUOTE ON QUOTE_ITEM.QUOTE_ID = QUOTE.ID
LEFT JOIN MANUFACTURER ON QUOTE_ITEM.REQUESTED_MFR_ID = MANUFACTURER.ID
LEFT JOIN APP_USER au1 ON QUOTE.SALES_USER_ID = au1.ID
LEFT JOIN APP_USER au2 ON QUOTE_ITEM.LAST_UPDATED_QC = au2.EMPLOYEE_ID
LEFT JOIN PRODUCT_GROUP ON QUOTE_ITEM.PRODUCT_GROUP2_ID = PRODUCT_GROUP.ID;
