UPDATE BIZ_UNIT SET DEFAULT_CURRENCY = 'USD', ALLOW_CURRENCIES='USD' WHERE NAME IN ('ASEAN','ANZ','KOREA','INDIA');
UPDATE BIZ_UNIT SET DEFAULT_CURRENCY = 'USD', ALLOW_CURRENCIES='USD,RMB,HKD' WHERE NAME IN ('CHINA');
UPDATE BIZ_UNIT SET DEFAULT_CURRENCY = 'USD', ALLOW_CURRENCIES='USD,SGD' WHERE NAME IN ('TW');
UPDATE BIZ_UNIT SET DEFAULT_CURRENCY = 'JPY', ALLOW_CURRENCIES='USD,JPY' WHERE NAME IN ('JAPAN');
COMMIT;