CREATE TABLE "WEBQUOTE"."ADMIN_BIZUNIT_MAPPING" 
   (	"BIZ_UNIT_ID" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"USER_ID" VARCHAR2(19 BYTE) NOT NULL ENABLE
   );
   
ALTER TABLE ADMIN_BIZUNIT_MAPPING
ADD CONSTRAINT ADMIN_BIZUNIT_MAPPING_PK PRIMARY KEY 
(
  BIZ_UNIT_ID 
, USER_ID 
)
ENABLE;
  